"""Driver toolkit — numbers, colours, days, affirmations (no gems/mantras)."""
from __future__ import annotations

from typing import Any, Dict

from numerology.core.digits import ARCHETYPE_BY_DRIVER

LUCKY: Dict[int, Dict[str, Any]] = {
    1: {
        "numbers": [1, 4, 10, 13, 19, 22, 28, 31],
        "days": ["Sunday", "Monday"],
        "days_hi": ["रविवार", "सोमवार"],
        "colors": ["Gold", "Orange", "Yellow", "Royal Blue"],
        "colors_hi": ["सुनहरा", "नारंगी", "पीला", "गहरा नीला"],
        "direction": "East",
        "avoid_numbers": [8, 17, 26],
        "avoid_days": ["Saturday"],
        "affirmation": "I lead with clarity; my decisions create momentum.",
        "practice": "5-minute morning intention + one bold priority before noon.",
        "lifestyle": "Structured morning routine; warm accent in workspace.",
    },
    2: {
        "numbers": [2, 7, 11, 16, 20, 25, 29],
        "days": ["Monday", "Friday"],
        "days_hi": ["सोमवार", "शुक्रवार"],
        "colors": ["Cream", "White", "Silver", "Light Green"],
        "colors_hi": ["क्रीम", "श्वेत", "रजत", "हल्का हरा"],
        "direction": "North-West",
        "avoid_numbers": [9, 18, 27],
        "avoid_days": ["Tuesday"],
        "affirmation": "I listen deeply; my empathy is a professional strength.",
        "practice": "2-minute breathing before important conversations.",
        "lifestyle": "Soft lighting, hydration, uncluttered desk.",
    },
    3: {
        "numbers": [3, 6, 9, 12, 15, 21, 24, 30],
        "days": ["Tuesday", "Thursday", "Friday"],
        "days_hi": ["मंगलवार", "गुरुवार", "शुक्रवार"],
        "colors": ["Yellow", "Saffron", "Gold", "Pink"],
        "colors_hi": ["पीला", "केसरी", "सुनहरा", "गुलाबी"],
        "direction": "North-East",
        "avoid_numbers": [5, 14, 23],
        "avoid_days": ["Wednesday"],
        "affirmation": "I express ideas clearly; my voice opens doors.",
        "practice": "Daily 10-line journal or voice note.",
        "lifestyle": "Visible goals board; creative break every 90 min.",
    },
    4: {
        "numbers": [4, 1, 13, 22, 31],
        "days": ["Sunday", "Monday", "Saturday"],
        "days_hi": ["रविवार", "सोमवार", "शनिवार"],
        "colors": ["Grey", "Khaki", "Electric Blue", "Navy"],
        "colors_hi": ["स्लेटी", "खाकी", "बिजली नीला", "गहरा नीला"],
        "direction": "South-West",
        "avoid_numbers": [5, 14, 23],
        "avoid_days": ["Wednesday"],
        "affirmation": "I build systems that last; steady work compounds.",
        "practice": "25-minute focus blocks; checklist for recurring tasks.",
        "lifestyle": "Minimal desk; digital hygiene every Friday.",
    },
    5: {
        "numbers": [5, 14, 23, 32, 41, 50],
        "days": ["Wednesday", "Friday"],
        "days_hi": ["बुधवार", "शुक्रवार"],
        "colors": ["Light Green", "Sky Blue", "White"],
        "colors_hi": ["हल्का हरा", "आसमानी नीला", "श्वेत"],
        "direction": "North",
        "avoid_numbers": [4, 13, 22],
        "avoid_days": ["Tuesday"],
        "affirmation": "I adapt fast and connect people; variety fuels my best work.",
        "practice": "Walk-and-talk for brainstorming.",
        "lifestyle": "Green plants; travel buffer in calendar.",
    },
    6: {
        "numbers": [6, 15, 24, 33, 42, 51],
        "days": ["Friday", "Tuesday", "Thursday"],
        "days_hi": ["शुक्रवार", "मंगलवार", "गुरुवार"],
        "colors": ["Pink", "Light Blue", "White", "Pastel Green"],
        "colors_hi": ["गुलाबी", "हल्का नीला", "श्वेत", "पेस्टल हरा"],
        "direction": "South-East",
        "avoid_numbers": [8, 17, 26],
        "avoid_days": ["Saturday"],
        "affirmation": "I create harmony; care and quality show in my results.",
        "practice": "One gratitude note to a colleague daily.",
        "lifestyle": "Pleasant scents; organised home corner.",
    },
    7: {
        "numbers": [7, 16, 25, 34, 43, 52],
        "days": ["Sunday", "Monday"],
        "days_hi": ["रविवार", "सोमवार"],
        "colors": ["Sea Green", "Cream", "Smokey Grey"],
        "colors_hi": ["समुद्री हरा", "क्रीम", "धुएँदार स्लेटी"],
        "direction": "South",
        "avoid_numbers": [9, 18, 27],
        "avoid_days": ["Tuesday"],
        "affirmation": "I think before I act; depth beats noise.",
        "practice": "20-minute silent focus — no phone.",
        "lifestyle": "Quiet zone; protected sleep schedule.",
    },
    8: {
        "numbers": [8, 17, 26, 35, 44, 53],
        "days": ["Saturday", "Sunday"],
        "days_hi": ["शनिवार", "रविवार"],
        "colors": ["Black", "Dark Blue", "Purple", "Charcoal"],
        "colors_hi": ["काला", "गहरा नीला", "बैंगनी", "स्याही"],
        "direction": "West",
        "avoid_numbers": [1, 10, 19],
        "avoid_days": ["Sunday"],
        "affirmation": "I earn through discipline; authority grows with integrity.",
        "practice": "End-of-day 3-line log: done / blocked / tomorrow.",
        "lifestyle": "Ergonomic setup; Sunday financial snapshot.",
    },
    9: {
        "numbers": [9, 18, 27, 36, 45, 54],
        "days": ["Tuesday", "Thursday", "Friday"],
        "days_hi": ["मंगलवार", "गुरुवार", "शुक्रवार"],
        "colors": ["Red", "Crimson", "Pink", "Maroon"],
        "colors_hi": ["लाल", "गहरा लाल", "गुलाबी", "मरून"],
        "direction": "South",
        "avoid_numbers": [2, 11, 20],
        "avoid_days": ["Monday"],
        "affirmation": "I channel intensity into impact; completion matters.",
        "practice": "24-hour pause before reactive messages.",
        "lifestyle": "Cooldown walk after heated meetings.",
    },
}


def affirmations_pack(driver: int) -> Dict[str, str]:
    base = LUCKY.get(driver, LUCKY[1])
    return {
        "archetype": ARCHETYPE_BY_DRIVER.get(driver, "—"),
        "affirmation": base.get("affirmation", ""),
        "practice": base.get("practice", ""),
        "lifestyle": base.get("lifestyle", ""),
        "color_focus": f"Wear palette colours on power days for Driver {driver}.",
        "habit": base.get("practice", ""),
    }
