"""
Cosmic Lens — Risk Text Engine
==============================
Enriches the existing energy-engine Risk Radar output with personalised
"KYA RISK / DHYAN / AVOID / KARNA / UPAY" text and Choghadiya-based
"BEST TIME / AVOID TIME" windows.

Brand voice  : Hinglish, supportive, never reveals planet/dasha names.
                Tagline reference: "Powered by Advanced Cosmic Intelligence".
Real engine  : All triggers come from energy_engine signals (Chandrashtama,
                Tara Bal, Sade Sati phase, Mars affliction, PD weakness,
                Tithi type, Rahukal, Volatile day). NO random fallbacks.

Inputs
------
- energy_result    : dict from energy_engine.calculate_energy(...)
- radar            : dict from energy_engine.compute_risk_radar(...)
- weekday          : int 0..6 (Mon..Sun) — local
- sunrise, sunset  : decimal local hours (e.g. 6.42, 18.83)
- current_hour     : decimal local hour for the "next upcoming" window
                      selection (e.g. 14.5 for 2:30 PM); pass 0 to start
                      from sunrise of the same day.

Output (merged into the API response)
-------------------------------------
    {
      "top_risk": {
        "trigger":   "<signal-id>",
        "category":  "Money / Conflict / Relations / Health / ...",
        "kya_risk_hai":          "...",
        "kya_dhyan_rakhna_hai":  "...",
        "kya_avoid_karna_hai":   "...",
        "kya_karna_hai":         "...",
        "upay":                  "..."
      },
      "best_time":  {"window": "10:42 AM — 12:18 PM", "label": "Amrit"},
      "avoid_time": {"window": "1:54 PM — 3:30 PM",   "label": "Rahukaal"},
      "choghadiya_today": [
        {"start": "06:25", "end": "07:48", "name": "Amrit", "period": "day", "quality": "best"},
        ...
      ]
    }
"""

from __future__ import annotations

import logging
from typing import Any, Dict, List, Optional, Tuple

# Module logger — used for non-fatal diagnostics inside per-day enrichment
# (e.g. lucky_engine missing or a single-day calc failing). Keep at debug:
# the route always continues and returns null lucky fields rather than
# escalating to enriched=False (NO fake fallbacks).
log = logging.getLogger(__name__)

# Reuse the canonical Choghadiya tables + Rahukal segment map already
# defined in energy_engine.py — single source of truth.
from energy_engine import (
    _DAY_CHOGHADIYA,
    _NIGHT_CHOGHADIYA,
    _RAHUKAL_SEGMENT,
    NAKSHATRAS,
)


# ──────────────────────────────────────────────────────────────────────────────
# AI-vs-template text resolver.
#
# Primary path: friendly Hinglish text generated by the Cosmic Intelligence
# layer (risk_text_ai.get_text), cached per-trigger across the process.
#
# Engineering fallback: the deterministic _TEXT_MAP defined below — used
# only when the AI layer is unavailable (e.g. OpenAI down) so the UI never
# shows a broken card. NOT random / fake data — these are the same hand-
# written supportive Hinglish texts the engine has always shipped.
# ──────────────────────────────────────────────────────────────────────────────
def _resolve_text(trigger: str) -> Dict[str, str]:
    """Return the 6-field guidance dict for the trigger.

    AI-first; falls through to _TEXT_MAP on any failure. Always returns a
    valid dict so callers can do ``text["category"]`` etc. without guards.
    """
    try:
        from risk_text_ai import get_text as _ai_get_text  # type: ignore

        ai_text = _ai_get_text(trigger)
        if ai_text is not None:
            return ai_text
    except Exception:
        # Module import or runtime issue — fall through to template.
        pass
    return _TEXT_MAP.get(trigger) or _TEXT_MAP["stable_day"]

# ──────────────────────────────────────────────────────────────────────────────
# 1. TRIGGER → PERSONALISED TEXT MAP
#    Each trigger key matches the signal logic inside compute_risk_radar.
#    Voice = supportive Hinglish, no jargon, no destiny language.
# ──────────────────────────────────────────────────────────────────────────────

_TEXT_MAP: Dict[str, Dict[str, str]] = {
    # ── 1. Volatile day (multiple negative signals stacked) ─────────────────
    "volatile_day": {
        "category":            "Mixed Energy",
        "kya_risk_hai":        "Aaj kaafi mixed energy hai — ek ghante mein "
                                "achha lagega, agle ghante mein heavy. Ups aur "
                                "downs ke beech khud ko anchored rakhna zaroori hai.",
        "kya_dhyan_rakhna_hai":"Reactions slow karein. Ek pause-breath-respond "
                                "rule follow karein. Doosron ki mood swings ko "
                                "personally mat lein.",
        "kya_avoid_karna_hai": "Bade financial commitments, public arguments, "
                                "important emails jaldi mein send karna, aur "
                                "social media par strong opinions.",
        "kya_karna_hai":       "Routine kaam, journaling, light exercise, aur "
                                "ek trusted person se baat. Observation > reaction.",
        "upay":                "Subah aur shaam dono time 5 minute deep breathing. "
                                "Ek glass paani mein chutki haldi — body ko ground karega.",
    },

    # ── 2. Chandrashtama (Moon in 8th from natal Moon) — severity 9 ─────────
    "chandrashtama": {
        "category":            "Emotional Sensitivity",
        "kya_risk_hai":        "Aaj mann ki energy thodi disturbed hai. Chhoti "
                                "baat bhi badi feel ho sakti hai, aur emotional "
                                "matters mein clarity kam rahegi.",
        "kya_dhyan_rakhna_hai":"Apne mann ko quiet rakhein. Doosron ke comments "
                                "ko literal mat lein — aaj filter zaroori hai.",
        "kya_avoid_karna_hai": "Emotional decisions, family confrontations, "
                                "relationship 'serious talks', aur late-night "
                                "social media scrolling.",
        "kya_karna_hai":       "Solo kaam, journaling, gentle walk, ya koi "
                                "creative outlet. Apne thoughts ko process karein.",
        "upay":                "Subah ek glass paani mein 2 chamach gulab jal "
                                "milake piye — mann ko sheetal karega. Shaam ko "
                                "chandra mantra 'Om Som Somaya Namah' 11 baar.",
    },

    # ── 3. Tara Bal — Naidhana/Vadha (worst) — severity 8 ───────────────────
    "tara_naidhana": {
        "category":            "Reflective / Slow Day",
        "kya_risk_hai":        "Aaj nakshatra balance reflective mode mein hai. "
                                "Energy reserve mein rakhne ka din — naye "
                                "ventures stuck feel ho sakte hain.",
        "kya_dhyan_rakhna_hai":"Ek baat 2 baar sochein. Slow pace ko weakness "
                                "mat samjhein — yeh aaj ki strength hai.",
        "kya_avoid_karna_hai": "Naye contracts sign karna, public appearances, "
                                "interviews, ya important launches.",
        "kya_karna_hai":       "Existing kaam complete karein, planning "
                                "documents likhein, research aur reading.",
        "upay":                "Shaam ko ghee ka diya jalaayein, aur Hanuman "
                                "Chalisa ek baar. Naidhana energy ko soft karta hai.",
    },

    # ── 4. Saturn heavy (Sade Sati Madhya / Ashtam Shani) — severity 8 ─────
    "saturn_heavy": {
        "category":            "Pressure / Patience",
        "kya_risk_hai":        "Background mein heavy responsibility ki feeling "
                                "chal rahi hai. Aaj zyada thakaan, slow progress, "
                                "aur authority figures se friction ho sakta hai.",
        "kya_dhyan_rakhna_hai":"Patience top priority. Slow aur steady approach "
                                "se aaj ka kaam aage badhega. Discipline help karegi.",
        "kya_avoid_karna_hai": "Shortcuts, jaldbaazi, bosses ya elders se "
                                "argument, aur 'main hi sahi hu' attitude.",
        "kya_karna_hai":       "Structured kaam, routines maintain karein, "
                                "ek senior se guidance lein, aur kisi zaroori "
                                "person ki seva karein.",
        "upay":                "Shani mantra 'Om Sham Shanaishcharaya Namah' 11 "
                                "baar. Saturday ko kaale til ka daan ya kisi "
                                "needy ko khaana khilaayein.",
    },

    # ── 5. Mars affliction (Mars in 1/4/7/8/12 OR jup_mars delta < -3) — 7 ──
    "mars_active": {
        "category":            "Conflict / Anger",
        "kya_risk_hai":        "Aaj jaldbaazi aur frustration ki energy active "
                                "hai. Words sharp ho sakte hain, aur conflicts "
                                "(road, office, ghar mein) ka risk zyada.",
        "kya_dhyan_rakhna_hai":"Apni reactions slow karein. Bolne se pehle 3 "
                                "second pause. Anger physical channel mein nikalo "
                                "(walk, exercise) — words mein nahi.",
        "kya_avoid_karna_hai": "Arguments, sharp emails, impulsive driving, "
                                "alcohol, aur 'main right hu' wala ego mode.",
        "kya_karna_hai":       "Physical exercise, controlled venting (gym, "
                                "running), detail wala focused kaam, aur "
                                "competitive sports (constructive outlet).",
        "upay":                "Tuesday ko laal masoor ki dal kisi needy ko "
                                "daan. Hanuman Chalisa subah ek baar — Mangal "
                                "ki energy ko balance karta hai.",
    },

    # ── 6. Tara mild (Vipat / Pratyak) — severity 6 ─────────────────────────
    "tara_mild": {
        "category":            "Mental Drain",
        "kya_risk_hai":        "Aaj overthinking aur thakaan zyada feel hogi. "
                                "Productivity normal se kam rahegi, irritation "
                                "easily trigger ho sakti hai.",
        "kya_dhyan_rakhna_hai":"Apne body ke signals ko sune. Mind ko force "
                                "mat karein — break lena weakness nahi hai.",
        "kya_avoid_karna_hai": "Marathon meetings, multi-tasking, caffeine "
                                "overdose, aur emotionally draining conversations.",
        "kya_karna_hai":       "Power-naps, light meals, ek walk fresh air mein, "
                                "aur jo kaam asaan hain wo pehle nipta dein.",
        "upay":                "Shaam ko 10 minute meditation ya pranayam "
                                "(anulom-vilom). Mind reset karega.",
    },

    # ── 7. PD weak (Pratyantar dasha lord delta ≤ -4) — severity 6 ──────────
    "pd_weak": {
        "category":            "Delays / Effort vs Results",
        "kya_risk_hai":        "Aaj effort to chal raha hai par results dheere "
                                "milenge. Important kaam mein delays, follow-ups "
                                "mein silence, aur small obstacles ho sakte hain.",
        "kya_dhyan_rakhna_hai":"Process pe focus karein, outcome pe nahi. "
                                "Results timeline mein flexibility rakhein.",
        "kya_avoid_karna_hai": "Tight deadlines commit karna, panic karna, "
                                "ek hi din mein 10 kaam list karna.",
        "kya_karna_hai":       "Buffer time rakhein, ek kaam ek time, follow-ups "
                                "consistent rakhein, aur planning detailed karein.",
        "upay":                "Apne ishtadev ka 5 minute dhyan subah. Patience "
                                "aur consistency ki energy strong hogi.",
    },

    # ── 8. Tithi Amavasya — severity 6 ─────────────────────────────────────
    "amavasya": {
        "category":            "Introspective / Low Energy",
        "kya_risk_hai":        "Aaj din heavy aur introspective rahega. Energy "
                                "naturally slow hogi, mood thoda heavy. Body "
                                "rest maang rahi hai.",
        "kya_dhyan_rakhna_hai":"Body ke signals sune, naye kaam start mat "
                                "karein. Aaj 'restoration day' samjhein.",
        "kya_avoid_karna_hai": "Naye purchases, contracts, travel start, aur "
                                "important launches.",
        "kya_karna_hai":       "Existing kaam smoothly nipta dein, light "
                                "saatvik food, family ke saath quiet time.",
        "upay":                "Shaam ko ghee ka diya pitr-sthan (north-east) "
                                "mein. Amavasya par pitru-tarpan se peace milti hai.",
    },

    # ── 9. Saturn mild (Sade Sati Phase 1/3 or Kantaka) — severity 5 ───────
    "saturn_mild": {
        "category":            "Background Pressure",
        "kya_risk_hai":        "Background mein thoda burden chal raha hai. "
                                "Heavy nahi par steady — thakaan slowly build "
                                "ho sakti hai.",
        "kya_dhyan_rakhna_hai":"Steady aur consistent rahein. Shortcuts ki "
                                "tempt ho sakti hai — avoid karein.",
        "kya_avoid_karna_hai": "Cutting corners, deadlines miss karna, elders "
                                "ki advice ignore karna.",
        "kya_karna_hai":       "Long-term planning, organising, decluttering, "
                                "aur structured routine maintain karein.",
        "upay":                "Saturday ko kaale til + sarso ka tel kisi shani "
                                "mandir mein. Discipline ke saath kaam karna sabse "
                                "bada upay hai.",
    },

    # ── 10. Tithi Rikta (drain) — severity 5 ───────────────────────────────
    "tithi_rikta": {
        "category":            "Energy Drain",
        "kya_risk_hai":        "Aaj body aur mind dono mein energy thodi kam "
                                "hogi. Heavy commitments ka burden feel hoga.",
        "kya_dhyan_rakhna_hai":"Aaj 'less is more'. Jo critical hai wahi karein, "
                                "baki kal ke liye rakhein.",
        "kya_avoid_karna_hai": "Heavy workload, late nights, junk food, aur "
                                "draining social commitments.",
        "kya_karna_hai":       "Light meals, hydration, kaam mein breaks, aur "
                                "early sleep.",
        "upay":                "Shaam ko warm haldi-doodh. Energy restore karega "
                                "aur immunity boost karega.",
    },

    # ── 11. Rahukal active — severity 4 ────────────────────────────────────
    "rahukal_active": {
        "category":            "Sensitive Time Window",
        "kya_risk_hai":        "Aaj din mein ek window thodi sensitive hai "
                                "(Rahukaal). Iss samay liye decisions later mein "
                                "complications la sakte hain.",
        "kya_dhyan_rakhna_hai":"Important calls, signatures, aur naye kaam "
                                "Rahukaal ke baad ke liye rakhein.",
        "kya_avoid_karna_hai": "Naye ventures Rahukaal ke beech mein, important "
                                "meetings, aur major financial transactions.",
        "kya_karna_hai":       "Existing routine kaam continue karein, planning "
                                "aur reading kaam Rahukaal mein safe hai.",
        "upay":                "Rahukaal ke samay Hanuman Chalisa ya Maha "
                                "Mrityunjaya 11 baar — protective shield banti hai.",
    },

    # ── 12. Stable / Smooth Day — fallback when no risks active ─────────────
    "stable_day": {
        "category":            "Smooth Flow",
        "kya_risk_hai":        "Aaj koi major risk signal nahi mil raha — "
                                "energies aapke favor mein hain. Smooth flow ka din.",
        "kya_dhyan_rakhna_hai":"Opportunities ko khule mann se accept karein, "
                                "momentum banaye rakhein. Khud pe trust rakhein.",
        "kya_avoid_karna_hai": "Negative self-talk, doosron ki pessimism, aur "
                                "'kuch galat ho jayega' wali sochein.",
        "kya_karna_hai":       "Naye projects start, networking, important "
                                "calls, presentations, aur growth-oriented kaam.",
        "upay":                "Subah Surya ko jal arghya — energy boost ke liye. "
                                "Din ki shuruwat gratitude ke saath karein.",
    },
}


# ──────────────────────────────────────────────────────────────────────────────
# 2. CHOGHADIYA → QUALITY MAP (best/neutral/avoid)
# ──────────────────────────────────────────────────────────────────────────────

_CHOGHADIYA_QUALITY: Dict[str, str] = {
    "Amrit": "best",  "Shubh": "best",  "Labh": "best",
    "Char":  "neutral",
    "Udveg": "avoid", "Rog":   "avoid", "Kaal": "avoid",
}
# Higher = better when picking "best_time"
_BEST_RANK: Dict[str, int] = {"Amrit": 3, "Shubh": 2, "Labh": 2, "Char": 0,
                              "Udveg": -2, "Rog": -3, "Kaal": -3}


# ──────────────────────────────────────────────────────────────────────────────
# 3. UTIL — format decimal hour as "h:mm AM/PM"
# ──────────────────────────────────────────────────────────────────────────────

def _fmt_time(decimal_hour: float) -> str:
    """Format decimal hour as 'h:mm AM/PM'. Wraps over 24h cleanly."""
    h = decimal_hour % 24.0
    hh = int(h)
    mm = int(round((h - hh) * 60))
    if mm == 60:
        mm = 0
        hh = (hh + 1) % 24
    period = "AM" if hh < 12 else "PM"
    disp = hh % 12
    if disp == 0:
        disp = 12
    return f"{disp}:{mm:02d} {period}"


# ──────────────────────────────────────────────────────────────────────────────
# 4. BUILD FULL DAY+NIGHT CHOGHADIYA SCHEDULE (16 segments)
# ──────────────────────────────────────────────────────────────────────────────

def build_choghadiya_schedule(weekday: int,
                              sunrise: float,
                              sunset: float
                              ) -> List[Dict[str, Any]]:
    """
    Build full 16-segment Choghadiya schedule for the given weekday.
    Each segment includes start/end times (decimal + display) and quality.

    weekday : 0=Mon..6=Sun  (Python datetime.weekday())
    """
    segments: List[Dict[str, Any]] = []
    day_length   = max(0.5, sunset - sunrise)
    night_length = 24.0 - day_length

    # ── 8 day-time segments ────────────────────────────────────────────────
    day_seg_len = day_length / 8.0
    day_names   = _DAY_CHOGHADIYA.get(weekday, [])
    for i, name in enumerate(day_names):
        start = sunrise + i * day_seg_len
        end   = start + day_seg_len
        segments.append({
            "start_h": round(start, 4),
            "end_h":   round(end, 4),
            "start":   _fmt_time(start),
            "end":     _fmt_time(end),
            "name":    name,
            "period":  "day",
            "quality": _CHOGHADIYA_QUALITY.get(name, "neutral"),
            "rank":    _BEST_RANK.get(name, 0),
        })

    # ── 8 night-time segments ──────────────────────────────────────────────
    night_seg_len = night_length / 8.0
    night_names   = _NIGHT_CHOGHADIYA.get(weekday, [])
    for i, name in enumerate(night_names):
        start = sunset + i * night_seg_len
        end   = start + night_seg_len
        segments.append({
            "start_h": round(start, 4),
            "end_h":   round(end, 4),
            "start":   _fmt_time(start),
            "end":     _fmt_time(end),
            "name":    name,
            "period":  "night",
            "quality": _CHOGHADIYA_QUALITY.get(name, "neutral"),
            "rank":    _BEST_RANK.get(name, 0),
        })

    return segments


def compute_rahukaal_window(weekday: int,
                            sunrise: float,
                            sunset: float
                            ) -> Optional[Dict[str, Any]]:
    """
    Return the day's Rahukaal window as {start, end, label}.
    Returns None for Sunday only if not in segment map.
    """
    seg = _RAHUKAL_SEGMENT.get(weekday)
    if seg is None:
        return None
    day_length = max(0.1, sunset - sunrise)
    seg_len    = day_length / 8.0
    start      = sunrise + (seg - 1) * seg_len
    end        = start + seg_len
    return {
        "start_h": round(start, 4),
        "end_h":   round(end, 4),
        "start":   _fmt_time(start),
        "end":     _fmt_time(end),
        "label":   "Rahukaal",
    }


# ──────────────────────────────────────────────────────────────────────────────
# 5. PICK BEST + AVOID TIME WINDOWS
# ──────────────────────────────────────────────────────────────────────────────

def _windows_overlap(a_start: float, a_end: float,
                     b_start: float, b_end: float) -> bool:
    """Half-open interval overlap: True iff [a_start,a_end) ∩ [b_start,b_end) ≠ ∅."""
    return (a_start < b_end) and (b_start < a_end)


def pick_best_avoid_times(schedule: List[Dict[str, Any]],
                          rahukaal: Optional[Dict[str, Any]],
                          current_h: float
                          ) -> Tuple[Dict[str, str], Dict[str, str]]:
    """
    From today's Choghadiya schedule, pick:
      - avoid_time : Rahukaal if upcoming; else earliest upcoming
                      Rog/Kaal/Udveg window.
      - best_time  : earliest UPCOMING "best" (Amrit > Shubh = Labh) window
                      that DOES NOT OVERLAP the chosen avoid window. If all
                      best windows have passed today, return the best-ranked
                      one of the day (still avoiding overlap).

    AVOID is selected first so BEST can be filtered against it — this
    prevents the user from seeing an identical pair when Rahukaal happens
    to fall on the same Choghadiya slot as the next Amrit (rare but
    possible at certain weekday/season combinations).

    Both windows are returned as user-facing strings:
      {"window": "10:42 AM — 12:18 PM", "label": "Amrit"}
    """
    # ── 1. Avoid time: Rahukaal first, then earliest upcoming "avoid" ──────
    avoid_start_h = avoid_end_h = None
    if rahukaal and rahukaal["end_h"] > current_h:
        avoid_out = {
            "window": f"{rahukaal['start']} — {rahukaal['end']}",
            "label":  "Rahukaal",
            "period": "day",
        }
        avoid_start_h = rahukaal["start_h"]
        avoid_end_h   = rahukaal["end_h"]
    else:
        upcoming_avoid = [s for s in schedule
                          if s["quality"] == "avoid" and s["end_h"] > current_h]
        if upcoming_avoid:
            # Earliest, then by rank (most negative first)
            upcoming_avoid.sort(key=lambda s: (s["start_h"], s["rank"]))
            av = upcoming_avoid[0]
            avoid_out = {
                "window": f"{av['start']} — {av['end']}",
                "label":  av["name"],
                "period": av["period"],
            }
            avoid_start_h = av["start_h"]
            avoid_end_h   = av["end_h"]
        elif rahukaal:
            avoid_out = {
                "window": f"{rahukaal['start']} — {rahukaal['end']}",
                "label":  "Rahukaal",
                "period": "day",
            }
            avoid_start_h = rahukaal["start_h"]
            avoid_end_h   = rahukaal["end_h"]
        else:
            # Last resort: any avoid segment in schedule
            any_avoid = [s for s in schedule if s["quality"] == "avoid"]
            if any_avoid:
                any_avoid.sort(key=lambda s: s["rank"])  # most negative first
                av = any_avoid[0]
                avoid_out = {
                    "window": f"{av['start']} — {av['end']}",
                    "label":  av["name"],
                    "period": av["period"],
                }
                avoid_start_h = av["start_h"]
                avoid_end_h   = av["end_h"]
            else:
                avoid_out = {"window": "", "label": "", "period": ""}

    # Filter helper: True iff window does NOT overlap the chosen avoid window
    def _no_overlap(seg: Dict[str, Any]) -> bool:
        if avoid_start_h is None or avoid_end_h is None:
            return True
        return not _windows_overlap(
            seg["start_h"], seg["end_h"], avoid_start_h, avoid_end_h,
        )

    # ── 2. Best time: prefer upcoming, highest rank, NON-OVERLAPPING ───────
    upcoming_best = [s for s in schedule
                     if s["quality"] == "best"
                     and s["end_h"] > current_h
                     and _no_overlap(s)]
    if upcoming_best:
        # Sort by (rank desc, start asc) so Amrit beats Shubh/Labh ties
        upcoming_best.sort(key=lambda s: (-s["rank"], s["start_h"]))
        best = upcoming_best[0]
    else:
        all_best = [s for s in schedule
                    if s["quality"] == "best" and _no_overlap(s)]
        if all_best:
            all_best.sort(key=lambda s: (-s["rank"], s["start_h"]))
            best = all_best[0]
        else:
            # Fallback: earliest neutral window (Char) — never lies, never
            # overlaps avoid. If even neutrals all overlap, take the
            # earliest segment that doesn't overlap; finally, schedule[0].
            neutral_ok = [s for s in schedule
                          if s["quality"] == "neutral" and _no_overlap(s)]
            if neutral_ok:
                best = neutral_ok[0]
            else:
                non_overlap = [s for s in schedule if _no_overlap(s)]
                best = non_overlap[0] if non_overlap else schedule[0]

    best_out = {
        "window": f"{best['start']} — {best['end']}",
        "label":  best["name"],
        "period": best["period"],
    }

    return best_out, avoid_out


# ──────────────────────────────────────────────────────────────────────────────
# 6. PICK DOMINANT TRIGGER FROM ENERGY-ENGINE SIGNALS
#    Mirrors compute_risk_radar's signal logic; ranks by severity.
# ──────────────────────────────────────────────────────────────────────────────

def detect_dominant_trigger(energy_result: Dict[str, Any]) -> str:
    """
    Inspect energy_result overlays/components and return the highest-severity
    trigger key from _TEXT_MAP. Returns 'stable_day' if no risk signals fire.
    """
    components = energy_result.get("components", {}) or {}
    overlays   = energy_result.get("overlays", {}) or {}
    flags      = energy_result.get("active_flags", []) or []

    moon_d     = components.get("moon_transit", {}) or {}
    tara_d     = components.get("tara_bal", {}) or {}
    saturn_d   = overlays.get("saturn", {}) or {}
    tithi_d    = overlays.get("tithi", {}) or {}
    pd_d       = overlays.get("pd_transit", {}) or {}
    jup_mars_d = overlays.get("jupiter_mars", {}) or {}
    time_q_d   = overlays.get("time_quality", {}) or {}

    volatile = bool(overlays.get("volatile_day", False))
    saturn_phase = saturn_d.get("phase", "") if saturn_d.get("active") else ""
    tara_idx     = tara_d.get("tara_idx", -1)
    tithi_type   = tithi_d.get("type", "") or ""
    tithi_idx    = tithi_d.get("tithi_idx", -1)
    pd_delta     = pd_d.get("delta", 0) or 0
    jup_mars_delta = jup_mars_d.get("delta", 0) or 0
    mars_house     = (jup_mars_d.get("mars_house")
                      or jup_mars_d.get("mars_house_lagna"))

    # Severity-ranked candidate list (same scores as compute_risk_radar)
    cands: List[Tuple[int, str]] = []
    if volatile:
        cands.append((10, "volatile_day"))
    if moon_d.get("chandrashtama"):
        cands.append((9,  "chandrashtama"))
    if tara_idx == 6:
        cands.append((8,  "tara_naidhana"))
    if "Madhya" in saturn_phase or "Ashtam" in saturn_phase:
        cands.append((8,  "saturn_heavy"))
    if jup_mars_delta < -3 or mars_house in (1, 4, 7, 8, 12):
        cands.append((7,  "mars_active"))
    if tara_idx in (2, 4):
        cands.append((6,  "tara_mild"))
    if pd_delta <= -4:
        cands.append((6,  "pd_weak"))
    # Tithi: Rikta takes precedence over Amavasya when both present
    # (mirrors compute_risk_radar's `if Rikta ... elif Amavasya` ordering)
    if tithi_type == "Rikta (drain)":
        cands.append((6,  "tithi_rikta"))
    elif tithi_idx == 30:
        cands.append((6,  "amavasya"))
    if ("Phase 1" in saturn_phase or "Phase 3" in saturn_phase
            or "Kantaka" in saturn_phase):
        cands.append((5,  "saturn_mild"))
    if bool(time_q_d.get("rahukal")) or "rahukal" in flags:
        cands.append((4,  "rahukal_active"))

    if not cands:
        return "stable_day"
    cands.sort(key=lambda c: -c[0])
    return cands[0][1]


# ──────────────────────────────────────────────────────────────────────────────
# 7. PER-DAY PROJECTION — real engine signals for each of the next 7 days
# ──────────────────────────────────────────────────────────────────────────────

# Severity → 1-10 risk score mapping (severity 0 = stable/low baseline)
def _severity_to_score(sev: int) -> int:
    if sev <= 0:
        return 2
    return max(1, min(10, sev - 1))


def _score_to_level(score: int) -> str:
    return "high" if score >= 7 else "med" if score >= 4 else "low"


def _resolve_birth_nakshatra_idx(birth_chart: Dict[str, Any]) -> int:
    """Resolve birth nakshatra index (0..26) from birth chart, or -1 if missing."""
    if not birth_chart:
        return -1
    nak = birth_chart.get("nakshatra")
    if isinstance(nak, str):
        try:
            return NAKSHATRAS.index(nak)
        except ValueError:
            pass
    for p in (birth_chart.get("planets") or []):
        if p.get("name") == "Moon":
            lon = p.get("longitude")
            if isinstance(lon, (int, float)):
                return int(lon / (360.0 / 27.0)) % 27
    return -1


def compute_per_day_enrichment(
    energy_result: Dict[str, Any],
    birth_chart:   Dict[str, Any],
    today_planets: Optional[Dict[str, Dict[str, Any]]],
    weekday_today: int,
    sunrise:       float,
    sunset:        float,
    current_h:     float,
    days:          int = 7,
    birth_data:    Optional[Dict[str, Any]] = None,
    today_date_iso: Optional[str] = None,
) -> List[Dict[str, Any]]:
    """
    Compute REAL per-day enrichment for the next `days` days starting today.

    Each day gets:
      - Per-day Tara Bal (projected Moon nakshatra vs natal nakshatra)
      - Per-day Tithi (projected Sun-Moon longitude difference)
      - Per-day Choghadiya schedule (advancing weekday)
      - Per-day BEST/AVOID time windows
      - Persistent signals carried forward (Saturn phase, Mars affliction,
        PD weakness — slow movers don't change appreciably in a week)
      - Day-0-only signals (volatile_day, chandrashtama — exact today only)
      - Dominant trigger + 5-field personalised text from _TEXT_MAP
      - Risk score (1-10) + level (low/med/high)

    All signals derive from the user's primary kundli (`birth_chart`) and
    today's transit positions (`today_planets`). NO random data, NO
    template fallback — if positions are missing, returns "stable_day"
    explicitly so the client knows.
    """
    components   = energy_result.get("components", {}) or {}
    overlays     = energy_result.get("overlays", {}) or {}
    moon_d_today = components.get("moon_transit", {}) or {}
    saturn_d     = overlays.get("saturn", {}) or {}
    jup_mars_d   = overlays.get("jupiter_mars", {}) or {}
    pd_d         = overlays.get("pd_transit", {}) or {}

    # Persistent signals (slow movers — same across the 7-day window).
    # Parity with detect_dominant_trigger(): saturn_heavy on Madhya/Ashtam,
    # saturn_mild specifically on Phase 1 / Phase 3 / Kantaka (NOT just
    # "active and not heavy"), mars active on -3 delta or houses 1/4/7/8/12.
    saturn_phase = saturn_d.get("phase", "") if saturn_d.get("active") else ""
    saturn_heavy = ("Madhya" in saturn_phase or "Ashtam" in saturn_phase)
    saturn_mild  = ("Phase 1" in saturn_phase or "Phase 3" in saturn_phase
                    or "Kantaka" in saturn_phase)
    mars_house   = (jup_mars_d.get("mars_house")
                    or jup_mars_d.get("mars_house_lagna"))
    mars_active  = ((jup_mars_d.get("delta", 0) or 0) < -3
                    or mars_house in (1, 4, 7, 8, 12))
    pd_weak        = (pd_d.get("delta", 0) or 0) <= -4
    volatile_today = bool(overlays.get("volatile_day", False))

    # Real natal anchor for Tara Bal projection
    birth_nak = _resolve_birth_nakshatra_idx(birth_chart)

    # Today's Moon + Sun longitudes for forward projection
    today_moon_lon = None
    today_sun_lon  = None
    if today_planets:
        m = today_planets.get("Moon")
        if isinstance(m, dict) and isinstance(m.get("longitude"), (int, float)):
            today_moon_lon = float(m["longitude"])
        s = today_planets.get("Sun")
        if isinstance(s, dict) and isinstance(s.get("longitude"), (int, float)):
            today_sun_lon = float(s["longitude"])

    # Lazy import — avoid circular import + keeps module light if lucky
    # engine isn't on the path during isolated tests.
    _compute_lucky = None
    if birth_data and today_date_iso:
        try:
            from lucky_engine import compute_daily_lucky as _compute_lucky  # type: ignore
        except Exception as _exc:
            log.debug("per_day: lucky_engine unavailable (%s) — skipping lucky", _exc)
            _compute_lucky = None

    # Resolve a base date for forward projection (today + i days). Falls
    # back to None when no date_iso passed → per-day lucky becomes None
    # for all days (no fake values).
    _base_date = None
    if today_date_iso:
        try:
            from datetime import datetime as _dt_local, timedelta as _td_local
            _base_date = _dt_local.strptime(today_date_iso, "%Y-%m-%d")
            _td_cls = _td_local
        except Exception:
            _base_date = None

    out: List[Dict[str, Any]] = []
    for i in range(days):
        # Project positions forward (Moon ~13.176°/day, Sun ~0.9856°/day)
        proj_moon = (
            (today_moon_lon + i * 13.176) % 360.0
            if today_moon_lon is not None else None
        )
        proj_sun = (
            (today_sun_lon + i * 0.9856) % 360.0
            if today_sun_lon is not None else None
        )
        proj_weekday = (weekday_today + i) % 7

        # Per-day Tara Bal (nakshatra-distance friendship)
        tara_idx = -1
        if proj_moon is not None and birth_nak >= 0:
            day_nak  = int(proj_moon / (360.0 / 27.0)) % 27
            tara_idx = (day_nak - birth_nak + 27) % 27 % 9

        # Per-day Tithi (Rikta / Amavasya from Sun-Moon angular difference)
        tithi_rikta    = False
        tithi_amavasya = False
        if proj_moon is not None and proj_sun is not None:
            diff   = (proj_moon - proj_sun) % 360.0
            t_idx  = int(diff / 12.0) % 30          # 0..29
            t_in_p = (t_idx % 15) + 1               # 1..15 within paksha
            tithi_rikta    = t_in_p in (4, 9, 14)   # Chaturthi/Navami/Chaturdashi
            tithi_amavasya = (t_idx == 29)          # last tithi of krishna paksha

        # Per-day Rahukaal window (always present every weekday — varies by
        # weekday). For Day 0 only we honour the time-of-day check (only
        # active when the current local hour is inside the window). For
        # Days 1-6 we treat Rahukaal as "applicable to the day" since the
        # user is reading ahead — same precedence (severity 4) as canonical.
        rahukal_today_d = compute_rahukaal_window(proj_weekday, sunrise, sunset)
        rahukal_active  = False
        if rahukal_today_d:
            if i == 0:
                rahukal_active = (
                    rahukal_today_d["start_h"] <= current_h <= rahukal_today_d["end_h"]
                )
            else:
                rahukal_active = True

        # Severity-ranked candidate triggers (mirrors detect_dominant_trigger)
        cands: List[Tuple[int, str]] = []
        # Day-0-only signals (exact today's transit conditions)
        if i == 0 and volatile_today:
            cands.append((10, "volatile_day"))
        if i == 0 and moon_d_today.get("chandrashtama"):
            cands.append((9, "chandrashtama"))
        # Per-day signals
        if tara_idx == 6:
            cands.append((8, "tara_naidhana"))
        # Persistent signals (slow movers)
        if saturn_heavy:
            cands.append((8, "saturn_heavy"))
        if mars_active:
            cands.append((7, "mars_active"))
        if tara_idx in (2, 4):
            cands.append((6, "tara_mild"))
        if pd_weak:
            cands.append((6, "pd_weak"))
        # Tithi: Rikta wins over Amavasya per canonical precedence
        if tithi_rikta:
            cands.append((6, "tithi_rikta"))
        elif tithi_amavasya:
            cands.append((6, "amavasya"))
        if saturn_mild:
            cands.append((5, "saturn_mild"))
        if rahukal_active:
            cands.append((4, "rahukal_active"))

        if cands:
            cands.sort(key=lambda c: -c[0])
            severity, trigger = cands[0]
        else:
            severity, trigger = 0, "stable_day"

        text       = _resolve_text(trigger)
        risk_score = _severity_to_score(severity)
        risk_level = _score_to_level(risk_score)

        # Per-day Choghadiya schedule + best/avoid windows
        # (sunrise/sunset of today is a reasonable proxy for adjacent days
        # — drift is < ~2 minutes/day. For perfect accuracy we'd compute
        # per-date sun times, but that requires lat/lon ephemeris per day.)
        sched    = build_choghadiya_schedule(proj_weekday, sunrise, sunset)
        rahukal  = compute_rahukaal_window(proj_weekday, sunrise, sunset)
        # Day 0 uses real current_h (filter to upcoming windows). Future
        # days start from sunrise so user sees the day's first window.
        eff_h    = current_h if i == 0 else sunrise
        best_t, avoid_t = pick_best_avoid_times(sched, rahukal, eff_h)

        # Per-day "Aaj Ka Shubh Ank + Rang" — same canonical engine the
        # /api/lucky/today route uses, just driven by the projected Moon
        # / Sun longitudes for this future date. NEVER inserts fake values:
        # if any input is missing or the engine returns ok=False, we leave
        # the lucky fields as None so the client renders an explicit
        # "unavailable" state instead of a placeholder.
        shubh_ank: Optional[int] = None
        shubh_rang_name: Optional[str] = None
        shubh_rang_hex: Optional[str] = None
        if (_compute_lucky is not None and _base_date is not None
                and proj_moon is not None and proj_sun is not None
                and birth_data and birth_chart):
            try:
                proj_date_iso = (_base_date + _td_cls(days=i)).strftime("%Y-%m-%d")
                lucky = _compute_lucky(
                    birth_data, birth_chart, proj_date_iso,
                    proj_moon, proj_sun,
                )
                if isinstance(lucky, dict) and lucky.get("ok"):
                    shubh_ank       = lucky.get("shubh_ank")
                    shubh_rang_name = lucky.get("shubh_rang_name")
                    shubh_rang_hex  = lucky.get("shubh_rang_hex")
            except Exception as _exc:
                log.debug("per_day: lucky calc failed for day %d: %s", i, _exc)

        out.append({
            "day_idx":              i,
            "trigger":              trigger,
            "severity":             severity,
            "category":             text["category"],
            "risk_score":           risk_score,
            "risk_level":           risk_level,
            "summary":              text["category"],
            "kya_risk_hai":         text["kya_risk_hai"],
            "kya_dhyan_rakhna_hai": text["kya_dhyan_rakhna_hai"],
            "kya_avoid_karna_hai":  text["kya_avoid_karna_hai"],
            "kya_karna_hai":        text["kya_karna_hai"],
            "upay":                 text["upay"],
            "best_time":            best_t,
            "avoid_time":           avoid_t,
            "tara_idx":             tara_idx,
            "weekday":              proj_weekday,
            "shubh_ank":            shubh_ank,
            "shubh_rang_name":      shubh_rang_name,
            "shubh_rang_hex":       shubh_rang_hex,
        })
    return out


# ──────────────────────────────────────────────────────────────────────────────
# 8. PUBLIC API — enrich the existing Risk Radar response
# ──────────────────────────────────────────────────────────────────────────────

def enrich_risk_radar(radar:         Dict[str, Any],
                      energy_result: Dict[str, Any],
                      weekday:       int,
                      sunrise:       float,
                      sunset:        float,
                      current_h:     float = 0.0,
                      birth_chart:   Optional[Dict[str, Any]] = None,
                      today_planets: Optional[Dict[str, Dict[str, Any]]] = None,
                      birth_data:    Optional[Dict[str, Any]] = None,
                      today_date_iso: Optional[str] = None,
                      ) -> Dict[str, Any]:
    """
    Merge personalised top-level text + Choghadiya timing into the Risk
    Radar dict produced by energy_engine.compute_risk_radar.

    The original `risk_radar_24h` array is preserved untouched (mobile may
    still want to display the multi-risk list). New top-level keys added:
      - top_risk         (5-field personalised text + trigger metadata)
      - best_time        ({window, label, period})
      - avoid_time       ({window, label, period})
      - choghadiya_today (full 16-segment schedule)
      - rahukaal_today   ({start, end, label}) or None

    Mutates and returns `radar` for convenience.
    """
    # ── 1. Detect dominant trigger from real engine signals ─────────────────
    trigger = detect_dominant_trigger(energy_result)
    text    = _resolve_text(trigger)

    radar["top_risk"] = {
        "trigger":              trigger,
        "category":             text["category"],
        "kya_risk_hai":         text["kya_risk_hai"],
        "kya_dhyan_rakhna_hai": text["kya_dhyan_rakhna_hai"],
        "kya_avoid_karna_hai":  text["kya_avoid_karna_hai"],
        "kya_karna_hai":        text["kya_karna_hai"],
        "upay":                 text["upay"],
    }

    # ── 2. Build Choghadiya schedule + Rahukaal window ──────────────────────
    schedule = build_choghadiya_schedule(weekday, sunrise, sunset)
    rahukaal = compute_rahukaal_window(weekday, sunrise, sunset)

    best_time, avoid_time = pick_best_avoid_times(schedule, rahukaal, current_h)

    radar["best_time"]        = best_time
    radar["avoid_time"]       = avoid_time
    radar["choghadiya_today"] = [
        {
            "start":   s["start"],
            "end":     s["end"],
            "name":    s["name"],
            "period":  s["period"],
            "quality": s["quality"],
        } for s in schedule
    ]
    radar["rahukaal_today"]   = (
        {"start": rahukaal["start"], "end": rahukaal["end"], "label": "Rahukaal"}
        if rahukaal else None
    )

    # ── 3. Per-day enrichment (REAL projection for next 7 days) ──────────────
    # Each day's text + Choghadiya windows + risk score derived from real
    # natal Moon nakshatra + projected transit Moon/Sun + persistent Saturn
    # /Mars/PD signals. NO template fallback for Days 2-7.
    radar["per_day"] = compute_per_day_enrichment(
        energy_result, birth_chart or {}, today_planets,
        weekday, sunrise, sunset, current_h, days=7,
        birth_data=birth_data, today_date_iso=today_date_iso,
    )

    # ── 4. Brand-voice attribution (NEVER reveal AI/LLM) ────────────────────
    radar.setdefault("powered_by", "Advanced Cosmic Intelligence")

    return radar


__all__ = [
    "enrich_risk_radar",
    "build_choghadiya_schedule",
    "compute_rahukaal_window",
    "pick_best_avoid_times",
    "detect_dominant_trigger",
    "compute_per_day_enrichment",
]
