"""Master timing spec — every domain: WHAT to check, WHEN engine runs, static vs timing.

Used by timing_router, audit scripts, and narrator LOCKED blocks.
Engine implementers: keep this dict in sync with actual code paths.
"""
from __future__ import annotations

from typing import Any

# Each spec entry:
#   houses, lords, karakas, divisionals, kp_cusps, dasha_targets, transits,
#   buckets, static_archetypes, timing_triggers, user_wants, guards, engine, status

DOMAIN_TIMING_SPECS: dict[str, dict[str, Any]] = {
    "marriage": {
        "label": "Marriage / Shaadi kab",
        "engine": "event_timing.marriage.marriage_engine_v2",
        "status": "ready",
        "houses": [2, 7, 11],
        "lords": ["2L", "7L", "11L"],
        "karakas": ["Venus", "Jupiter", "Moon"],
        "divisionals": ["D9", "D7"],
        "kp_cusps": [2, 7, 11],
        "pipeline_steps": [
            "STEP0 age/gender/delay-vs-late (marriage_age_context)",
            "STEP0a BCP D1+D9 focus ages (bcp_marriage_ages)",
            "STEP1-5 D1/D9 significator pipeline (marriage_spec_pipeline)",
            "STEP5 dasha scan on marriage targets",
            "STEP6-7 transit + double-transit on 7H/7L",
            "STEP8 final gate + top-3 windows",
        ],
        "dasha_targets": ["7L", "Venus", "Jupiter", "2L", "11L"],
        "transits": ["Jupiter on 7H/7L", "Saturn delay check", "double-transit 7H"],
        "buckets": ["timing", "remedy", "analysis"],
        "timing_triggers": ["kab", "when", "kis saal", "muhurat", "shaadi kab"],
        "static_vs_timing": {
            "timing": "shaadi kab / marriage date / muhurat",
            "static": "spouse nature, compatibility, manglik, delay tone without kab",
        },
        "user_wants": "Exact window range + dasha lords cited; never guarantee date",
        "guards": ["too_young suppress", "no guaranteed shaadi date", "delay vs late frame"],
    },
    "love": {
        "label": "Love / relationship timing",
        "engine": "event_timing.love.love_timing_engine_v1",
        "status": "ready",
        "houses": [5, 7, 11],
        "lords": ["5L", "7L", "11L"],
        "karakas": ["Venus", "Moon", "Mars"],
        "divisionals": ["D9"],
        "kp_cusps": [5, 7, 11],
        "pipeline_steps": [
            "STEP0 one-sided / breakup / affair tone guard",
            "STEP1 5H romance + 7H partnership promise (timing buckets)",
            "STEP2 Venus dignity + Mars impulse",
            "STEP3 BCP 5L+7L parallel ages (background)",
            "STEP4 D9 Venus/7L overlay (love promise)",
            "STEP5 dasha AD/PD of bucket lords",
            "STEP6 Jupiter+Venus transit on 5H/7H/11H (month lock)",
            "STEP8 no rejection certainty / no third-party naming",
            "STATIC: love_static_engine_v1 for non-kab love Qs",
            "MILAN: milan_engine_v1 when two charts + match Q",
        ],
        "dasha_targets": ["5L", "7L", "11L", "Venus"],
        "transits": ["Venus transit", "Jupiter on 5H/7H"],
        "buckets": [
            "timing", "reconciliation", "one_sided", "commitment", "breakup",
            "meeting", "affair", "general_love",
            "family_approval", "healing", "stress_phase", "discovery",
        ],
        "companion_engines": {
            "static": "event_timing.love.love_static_engine_v1",
            "milan": "event_timing.love.milan_engine_v1",
        },
        "timing_triggers": ["pyaar kab", "patchup kab", "milega kab", "relationship kab"],
        "static_vs_timing": {
            "timing": "kab milega / patchup kab / commitment kab",
            "static": "loyalty, nature, compatibility without kab",
        },
        "user_wants": "Probability window, not 'pakka milega'; preserve dignity",
        "guards": ["LOVE_TONE_RULES", "no betrayal certainty", "love-marriage → marriage engine"],
        "defer_rules": ["love marriage kab → marriage domain"],
    },
    "career": {
        "label": "Career / job / promotion timing",
        "engine": "event_timing.career.career_timing",
        "status": "ready",
        "houses": [2, 6, 10, 11],
        "lords": ["2L", "6L", "10L", "11L"],
        "karakas": ["Sun", "Saturn", "Mercury", "Jupiter"],
        "divisionals": ["D10", "D9", "D24"],
        "kp_cusps": [6, 10, 11],
        "pipeline_steps": [
            "STEP0 age context (65+ → re-employment not first job)",
            "STEP1-35 natal layers (10H, karakas, yogas)",
            "T1 vimshottari + T2 Saturn + T3 Jupiter/Yogini",
            "Conditionals by bucket (promotion, govt, transfer, setback)",
            "Window from MD/AD + Saturn/Jupiter career transit",
        ],
        "dasha_targets": ["10L", "6L", "11L", "5L", "AmK", "Saturn", "Sun"],
        "transits": ["Saturn on 10H", "Jupiter on 10H/11H"],
        "buckets": [
            "govt_job", "promotion", "resignation", "transfer",
            "career_setback", "job_change", "career_field_choice", "general_career",
        ],
        "timing_triggers": ["job kab", "promotion kab", "naukri kab", "transfer kab"],
        "static_vs_timing": {
            "timing": "kab lagega / kab milegi promotion / kab switch",
            "static": "suit karega / kaunsi field / job vs business",
        },
        "user_wants": "Action window + strategy; no guaranteed selection/promotion",
        "guards": ["govt exam no 100% guarantee", "resignation financial buffer"],
    },
    "travel": {
        "label": "Foreign travel / settlement / visa timing",
        "engine": "event_timing.travel.travel_engine_v1",
        "status": "ready",
        "houses": [3, 4, 7, 9, 12],
        "lords": ["3L", "4L", "7L", "9L", "12L"],
        "karakas": ["Rahu", "Moon", "Mercury", "Jupiter", "Saturn"],
        "divisionals": ["D9", "D4"],
        "kp_cusps": [3, 9, 12],
        "pipeline_steps": [
            "STEP1 D1 filter (3/9/12L + occupants + 9H aspects)",
            "STEP2 D9 verify + STEP3 D4 residence shift",
            "STEP3.5 KP CSL 3/9/12",
            "STEP4 weighted rank",
            "STEP5 dasha AD/PD on 12L/9L/Rahu",
            "STEP6 transit Jupiter 9/12, Saturn 12/4, Rahu 9/12",
            "STEP7 Ashtakavarga 9H+12H",
            "STEP8-9 yogas + hard guards",
        ],
        "dasha_targets": ["12L", "9L", "3L", "Rahu"],
        "transits": ["Jupiter 9/12", "Saturn 12", "Rahu 12", "double-transit 9H/12H"],
        "buckets": [
            "foreign_settlement", "visa_theme", "relocation_abroad",
            "travel_yog", "short_travel", "return_india", "general_travel",
        ],
        "timing_triggers": ["videsh kab", "abroad kab", "visa kab", "settle kab", "travel kab"],
        "static_vs_timing": {
            "timing": "kab jaunga / visa kab / settle kab",
            "static": "travel yog strong / foreign possible without kab",
        },
        "user_wants": "Travel window + risk tier; NEVER name country or guarantee visa",
        "guards": ["NO_GUARANTEED_VISA", "NO_DESTINATION_NAMING", "TRAVEL_DISCLAIMER"],
    },
    "property": {
        "label": "Property / ghar / registry timing",
        "engine": "event_timing.property.property_timing_v1",
        "status": "ready",
        "houses": [4, 11],
        "lords": ["4L", "11L"],
        "karakas": ["Mars", "Saturn"],
        "divisionals": ["D4"],
        "kp_cusps": [4],
        "pipeline_steps": [
            "STEP1 BCP D1 4L placement + aspects (focus ages)",
            "STEP2 Active dasha + 4H/11H activation",
            "STEP2 Mangal (bhumi/construction) + Shani (immovable) karaka",
            "STEP5 dasha 4L/Mars/Saturn AD-PD",
            "STEP6 Shani/Guru transit on 4H",
        ],
        "dasha_targets": ["4L", "Mars", "Saturn"],
        "transits": ["Saturn 4H", "Jupiter 4H"],
        "buckets": ["buy", "sell", "construction", "registry", "possession", "inheritance", "dispute", "loan"],
        "timing_triggers": ["ghar kab", "registry kab", "possession kab", "plot kab"],
        "static_vs_timing": {
            "timing": "kab lun / registry kab / shift kab",
            "static": "yog / capacity / type fit without kab",
        },
        "user_wants": "Month-range window for buy/registry; no exact price",
        "guards": ["no location guarantee", "loan approval not guaranteed"],
    },
    "vehicle": {
        "label": "Vehicle / car / bike timing",
        "engine": "event_timing.vehicle.vehicle_timing_v1",
        "status": "ready",
        "houses": [4, 11, 3],
        "lords": ["4L", "11L", "3L"],
        "karakas": ["Venus", "Mars", "Moon", "Mercury"],
        "divisionals": ["D4"],
        "kp_cusps": [4, 11, 3],
        "pipeline_steps": [
            "STEP1 4H vehicle/comfort axis + Venus luxury karaka",
            "STEP2 Mars machinery/vehicle energy",
            "STEP5 dasha 4L/11L/Venus/Mars",
            "STEP6 Jupiter/Saturn transit on 4H/11H",
            "STEP8 no exact model/colour/delivery guarantee",
        ],
        "dasha_targets": ["4L", "11L", "Venus", "Mars"],
        "transits": ["Jupiter 4H/11H", "Venus gochar"],
        "buckets": ["buy", "upgrade", "sell"],
        "timing_triggers": ["gaadi kab", "car kab", "bike kab", "vehicle kab"],
        "static_vs_timing": {
            "timing": "kab khareedun / kab milegi gaadi",
            "static": "kaunsi gaadi suit without kab",
        },
        "user_wants": "Purchase window month-range; no model/price guarantee",
        "guards": ["no accident prediction", "loan/RTO practical checks"],
    },
    "finance": {
        "label": "Wealth / loan / windfall timing",
        "engine": "event_timing.finance.finance_engine_v1",
        "status": "ready",
        "houses": [2, 5, 9, 11],
        "lords": ["2L", "11L"],
        "karakas": ["Jupiter", "Venus", "Mercury"],
        "divisionals": ["D2", "D9"],
        "kp_cusps": [2, 11],
        "pipeline_steps": [
            "STEP1 dhana houses filter",
            "STEP5 dasha 2L/11L/Jupiter",
            "STEP6 transit on 2H/11H",
            "STEP8 never predict rupee amount",
        ],
        "dasha_targets": ["2L", "11L", "Jupiter"],
        "transits": ["Jupiter 2H/11H", "Saturn debt pressure 6H/8H"],
        "buckets": [
            "salary_growth", "loan_emi", "sudden_windfall", "debt_recovery", "general_wealth",
        ],
        "timing_triggers": ["paisa kab", "loan kab", "profit kab", "recovery kab"],
        "static_vs_timing": {
            "timing": "kab milega paisa / loan kab clear",
            "static": "bachat capacity / spender vs saver",
        },
        "user_wants": "Trend window; no lottery guarantee; CA consult for tax/loan",
        "guards": ["no rupee amounts", "no bankruptcy prediction", "no loan-skip advice"],
    },
    "health": {
        "label": "Health / surgery / recovery timing",
        "engine": "event_timing.health.health_engine_v1",
        "status": "ready",
        "houses": [1, 6, 8, 12],
        "lords": ["1L", "6L", "8L"],
        "karakas": ["Sun", "Moon", "Mars", "Saturn"],
        "divisionals": ["D30"],
        "kp_cusps": [1, 6, 8],
        "pipeline_steps": [
            "STEP1 vitality filter 1H/6H",
            "STEP5 dasha 6L/8L for acute/chronic",
            "STEP6 Mars/Saturn transit risk",
            "STEP8 no diagnosis / no muhurat for surgery without doctor",
        ],
        "dasha_targets": ["1L", "6L", "8L", "Moon"],
        "transits": ["Saturn on 1H", "Mars accident trigger"],
        "buckets": ["surgery_recovery", "chronic_illness", "mental_stress", "general_wellness"],
        "timing_triggers": ["theek kab", "recovery kab", "surgery kab", "operation kab"],
        "static_vs_timing": {
            "timing": "recovery kab / surgery window",
            "static": "vitality tone / tendency without kab",
        },
        "user_wants": "Supportive window + prevention; always doctor first",
        "guards": ["no medical diagnosis", "no death prediction"],
    },
    "children": {
        "label": "Children / conception / delivery timing",
        "engine": "event_timing.baby.baby_engine_v1",
        "status": "ready",
        "houses": [5, 7, 9, 11],
        "lords": ["5L", "9L", "11L"],
        "karakas": ["Jupiter"],
        "divisionals": ["D7", "D9"],
        "kp_cusps": [5, 11],
        "pipeline_steps": [
            "STEP1 5H progeny filter",
            "STEP2 D7 verify",
            "STEP5 Jupiter dasha / 5L AD",
            "STEP6 double-transit on 5H",
            "STEP8 no guaranteed gender/count",
        ],
        "dasha_targets": ["5L", "Jupiter", "9L"],
        "transits": ["Jupiter 5H", "Saturn delay 5H"],
        "buckets": ["conception", "pregnancy", "delivery", "delay", "general_children"],
        "timing_triggers": ["bachcha kab", "conceive kab", "pregnancy kab", "santan kab"],
        "static_vs_timing": {
            "timing": "kab hoga bachcha / conceive kab",
            "static": "promise/count tone / nature without kab",
        },
        "user_wants": "Fertile window range; medical consult for conception",
        "guards": ["no gender guarantee", "no miscarriage fear language"],
    },
    "education": {
        "label": "Education / exam / admission timing",
        "engine": "event_timing.education.education_timing_v1",
        "status": "ready",
        "houses": [4, 5, 9],
        "lords": ["4L", "5L", "9L"],
        "karakas": ["Mercury", "Jupiter"],
        "divisionals": ["D24"],
        "kp_cusps": [4, 9],
        "pipeline_steps": [
            "STEP1 4H/5H study + 9H higher ed",
            "STEP5 Mercury/Jupiter dasha",
            "STEP6 Jupiter on 5H/9H for result/admission",
            "STEP8 govt exam → career engine if UPSC/SSC",
        ],
        "dasha_targets": ["5L", "9L", "Mercury", "Jupiter"],
        "transits": ["Jupiter 9H exam luck"],
        "buckets": ["exam_success", "admission", "degree_completion", "higher_studies"],
        "timing_triggers": ["exam kab", "result kab", "admission kab", "pass kab"],
        "static_vs_timing": {
            "timing": "result kab / admission kab",
            "static": "field choice / learning ability without kab",
        },
        "user_wants": "Exam/admission window; no exact marks/rank",
        "guards": ["UPSC/SSC → career timing", "no rank guarantee"],
    },
    "foreign_education": {
        "label": "Foreign travel + higher education timing",
        "engine": "event_timing.foreign_education.foreign_education_timing_v1",
        "status": "ready",
        "houses": [5, 9, 12],
        "lords": ["5L", "9L", "12L"],
        "karakas": ["Rahu", "Jupiter"],
        "divisionals": ["D9", "D4"],
        "kp_cusps": [5, 9, 12],
        "pipeline_steps": [
            "STEP1 5H exam/admission + 9H higher ed + 12H foreign",
            "STEP2 Rahu foreign karaka + Guru higher-studies/visa luck",
            "STEP5 dasha 5L/9L/12L/Rahu/Jupiter AD-PD",
            "STEP6 Jupiter/Rahu transit on 9H/12H",
            "STEP8 no visa/college/country guarantee",
        ],
        "dasha_targets": ["5L", "9L", "12L", "Rahu", "Jupiter"],
        "transits": ["Jupiter 9H/12H", "Rahu 9H/12H", "double-transit 9H/12H"],
        "buckets": ["admission", "exam_selection", "visa", "pr_residency", "settlement"],
        "timing_triggers": [
            "admission kab", "visa kab", "pr kab", "green card kab",
            "foreign settlement kab", "exam result kab",
        ],
        "static_vs_timing": {
            "timing": "admission/visa/PR/settlement kab",
            "static": "study field fit without kab",
        },
        "user_wants": "5H/9H/12H window for admission, exam, visa, PR, settlement",
        "guards": [
            "NO_GUARANTEED_VISA",
            "NO_DESTINATION_NAMING",
            "NO_EXACT_RANK",
            "FOREIGN_EDU_DISCLAIMER",
        ],
    },
    "litigation": {
        "label": "Court / bail / verdict timing",
        "engine": "event_timing.litigation.litigation_timing_v1",
        "status": "ready",
        "houses": [6, 8, 10, 11, 12],
        "lords": ["6L", "8L", "10L", "12L"],
        "karakas": ["Mars", "Saturn", "Rahu", "Mercury"],
        "divisionals": ["D6"],
        "kp_cusps": [6, 8, 10, 11, 12],
        "pipeline_steps": [
            "STEP1 6H dispute + 8H crisis + 10H judge + 12H loss",
            "STEP5 dasha 6L/8L/Saturn",
            "STEP6 Saturn transit delay / Mars conflict",
            "STEP8 anti-fear: no jail/phansi guarantee",
        ],
        "dasha_targets": ["6L", "8L", "10L", "Saturn", "Rahu"],
        "transits": ["Saturn on 6H/8H/10H", "Rahu legal entanglement"],
        "buckets": [
            "fir_police", "bail_theme", "settlement", "court_delay",
            "case_outcome", "acquittal_relief", "general_litigation",
        ],
        "timing_triggers": ["case kab", "bail kab", "verdict kab", "court kab"],
        "static_vs_timing": {
            "timing": "verdict kab / bail kab / case end kab",
            "static": "yog / obstacles / lawyer support without kab",
        },
        "user_wants": "Process window; lawyer first; calm tone on jail fear",
        "guards": ["SAFETY_SUMMARY", "no guaranteed win/loss", "property court → property"],
    },
    "spiritual": {
        "label": "Spiritual growth / occult / guru / pilgrimage timing",
        "engine": "event_timing.spiritual.spiritual_timing_v1",
        "status": "ready",
        "houses": [8, 9, 12],
        "lords": ["8L", "9L", "12L"],
        "karakas": ["Ketu", "Jupiter", "Saturn", "Moon"],
        "divisionals": ["D9", "D12"],
        "kp_cusps": [8, 9, 12],
        "pipeline_steps": [
            "STEP1 8H occult/secret-knowledge + 9H guru/dharma + 12H moksha filter",
            "STEP2 Ketu/Jupiter karaka dignity",
            "STEP5 dasha 8L/9L/12L/Ketu/Jupiter AD-PD",
            "STEP6 Jupiter/Ketu transit on 9H/12H",
            "STEP8 no guru naam / no moksha guarantee",
        ],
        "dasha_targets": ["9L", "12L", "8L", "Ketu", "Jupiter"],
        "transits": ["Jupiter 9H/12H", "Ketu 8H/12H", "Saturn sadhana discipline"],
        "buckets": [
            "guru_deeksha", "occult_learning", "pilgrimage", "inner_peace", "general_spiritual",
        ],
        "timing_triggers": [
            "guru kab", "deeksha kab", "meditation kab", "dhyan kab",
            "teerth kab", "occult kab", "astrology seekh kab", "shanti kab",
        ],
        "static_vs_timing": {
            "timing": "guru kab / deeksha kab / teerth kab / meditation kab",
            "static": "spiritual yog / guru yog / dharma path without kab",
        },
        "user_wants": "Readiness window on 8H/9H/12H; ethics-first occult guidance",
        "guards": [
            "NO_GURU_NAME",
            "NO_MOKSHA_GUARANTEE",
            "OCCULT_ETHICS",
            "DOCTOR_IF_CLINICAL_MENTAL",
        ],
    },
    "fame": {
        "label": "Social image / fame / recognition / politics timing",
        "engine": "event_timing.fame.fame_timing_v1",
        "status": "ready",
        "houses": [1, 5, 10, 11],
        "lords": ["1L", "5L", "10L"],
        "karakas": ["Sun", "Rahu", "Jupiter", "Venus", "Moon"],
        "divisionals": ["D10", "D9"],
        "kp_cusps": [1, 5, 10, 11],
        "pipeline_steps": [
            "STEP1 1H image + 5H creativity + 10H status + 10th-from-Moon filter",
            "STEP2 Sun/Rahu/Jupiter karaka dignity",
            "STEP5 dasha 1L/5L/10L/Sun/Rahu AD-PD",
            "STEP6 Jupiter/Sun/Rahu transit on 1H/10H",
            "STEP8 no viral/award/election guarantee",
        ],
        "dasha_targets": ["1L", "5L", "10L", "Sun", "Rahu", "Jupiter"],
        "transits": ["Sun 10H", "Rahu 1H/11H", "Jupiter honor transit"],
        "buckets": [
            "social_fame", "awards", "reputation_recovery", "politics_leadership", "general_fame",
        ],
        "timing_triggers": [
            "fame kab", "viral kab", "award kab", "reputation kab", "politics kab",
        ],
        "static_vs_timing": {
            "timing": "fame kab / viral kab / award kab / reputation theek kab / politics entry kab",
            "static": "celebrity yog / fame potential without kab",
        },
        "user_wants": "Readiness window on 1H/5H/10H + Sun/Rahu; humble on virality & awards",
        "guards": [
            "NO_VIRAL_GUARANTEE",
            "NO_AWARD_CERTAINTY",
            "NO_POLITICAL_WIN_GUARANTEE",
            "REPUTATION_RECOVERY_HUMBLE",
        ],
    },
    "network": {
        "label": "Friends / network / social circle timing",
        "engine": "event_timing.network.network_timing_v1",
        "status": "ready",
        "houses": [3, 11],
        "lords": ["11L", "3L"],
        "karakas": ["Mercury", "Rahu", "Jupiter", "Venus"],
        "divisionals": ["D11", "D9"],
        "kp_cusps": [3, 11],
        "pipeline_steps": [
            "STEP1 11H friends/gains + 3H Mercury peer communication filter",
            "STEP2 Mercury/Rahu karaka dignity",
            "STEP5 dasha 11L/3L/Mercury/Rahu AD-PD",
            "STEP6 Jupiter/Mercury transit on 11H",
            "STEP8 no VIP name / no guaranteed reconciliation",
        ],
        "dasha_targets": ["11L", "3L", "Mercury", "Rahu", "Jupiter"],
        "transits": ["Mercury 11H", "Rahu 11H", "Jupiter well-wisher transit"],
        "buckets": [
            "influential_network", "friend_conflict", "enmity_peace", "general_network",
        ],
        "timing_triggers": [
            "network kab", "dost dhoka kab", "dushmani kab shant", "bade log help kab",
        ],
        "static_vs_timing": {
            "timing": "network kab / misunderstanding kab khatam / dushmani kab shant",
            "static": "11H strong / friend yog without kab",
        },
        "user_wants": "Readiness window on 11H + Mercury/Rahu; humble on VIP help & reconciliation",
        "guards": [
            "NO_VIP_NAME",
            "NO_FRIEND_RECONCILE_GUARANTEE",
            "NO_ENMITY_END_CERTAINTY",
            "TRUST_PRACTICAL_CHECK",
        ],
    },
    "universal": {
        "label": "Universal timing fallback (no dedicated engine matched)",
        "engine": "event_timing.universal.universal_timing_v1",
        "status": "ready",
        "houses": [1, 9, 10, 11],
        "lords": ["dynamic"],
        "karakas": ["dynamic from topic atlas"],
        "divisionals": ["D9"],
        "kp_cusps": ["dynamic"],
        "pipeline_steps": [
            "STEP0 only if no dedicated engine matched",
            "STEP1 keyword atlas → dynamic concern/leak houses",
            "STEP2 karaka dignity (D9)",
            "STEP3 KP cusps from resolved topic",
            "STEP5 dasha window scoring",
            "STEP8 humble fallback guards",
        ],
        "dasha_targets": ["dynamic lords from atlas"],
        "transits": ["double transit on top concern houses"],
        "buckets": [
            "lottery_speculation", "pet_animal", "sibling_family",
            "inheritance_legacy", "surgery_procedure", "legal_document",
            "creative_project", "general_life_event",
        ],
        "timing_triggers": ["any kab/when Q with no domain registry match"],
        "static_vs_timing": {
            "timing": "fallback only — dedicated engine always preferred",
            "static": "not used",
        },
        "user_wants": "Readiness window from dynamic houses; lower confidence vs dedicated engines",
        "guards": [
            "UNIVERSAL_FALLBACK_ONLY",
            "NO_INVENTED_DATES",
            "HUMBLE_PROBABILITY",
            "DEDICATED_ENGINE_PREFERRED",
        ],
    },
}


def get_domain_spec(domain: str) -> dict[str, Any]:
    return DOMAIN_TIMING_SPECS.get(domain, DOMAIN_TIMING_SPECS.get("career", {}))


def list_domains_by_status(status: str) -> list[str]:
    return [d for d, s in DOMAIN_TIMING_SPECS.items() if s.get("status") == status]
