"""Remedy Catalog — single source of truth for the 3-tier remedy stack.

Every entry follows the schema:

    CATALOG[topic][planet] = {
        "practical":  {action, why, time_to_result, kpi, free, cost_inr},
        "ayurvedic":  {practice, herb, dose, vaidya_caveat, time_to_result},
        "vedic":      {day, mantra, count, donation, gemstone, gem_caveat,
                        cost_inr_paid, free_alt},
        "for_areas":  comma-sep tags (matches systems/areas list per topic),
    }

DESIGN LOCKS (per user mandate, May 6 2026):
- Tier-1 PRACTICAL is ALWAYS shown FIRST. Vedic comes LAST.
- Every paid item carries cost ballpark + caveat ("90% of street stones
  are synthetic — buy with cert", "Trial 3 days first", etc).
- Every health remedy paired with measurable KPI (BP, sleep, weight,
  blood-test, mood-rating) so user can self-verify outcome in 21-40 d.
- Mantras + gemstones cited from BPHS / Phaladeepika / Lal-Kitab consensus.
- Ayurvedic guidance carries vaidya-consult disclaimer for any internal
  herb (Charaka principle: dose depends on prakriti, never universal).
- NEVER recommend vedic-only — engine selector forces practical pairing.

Topics covered: health, marriage, career.
Planets covered: Sun, Moon, Mars, Mercury, Jupiter, Venus, Saturn, Rahu,
Ketu (9 grahas).
"""
from __future__ import annotations

from typing import Any, Dict


# ════════════════════════════════════════════════════════════════════════
# HEALTH — 9 planets × 3 tiers
# ════════════════════════════════════════════════════════════════════════
_HEALTH: Dict[str, Dict[str, Any]] = {
    "Sun": {
        "for_areas": "heart, eyes, vitality, bones, vitamin-D",
        "practical": {
            "action":         "Morning sunlight 15-20 min before 9 AM (eyes closed, face exposed) + ECG + Vit-D test if not done in 12 mo",
            "why":            "Sun rules vitality — direct sunlight regulates circadian + Vit-D + mood. Lab data > faith.",
            "time_to_result": "2 weeks (mood + sleep), 8 weeks (Vit-D level)",
            "kpi":            "Vit-D 30-60 ng/ml, resting HR < 75, sleep onset < 20 min",
            "free":           True,
            "cost_inr":       0,
        },
        "ayurvedic": {
            "practice":       "Surya namaskar 12 rounds at sunrise + Aditya Hridaya Stotra path",
            "herb":           "Amla (1 fresh fruit OR 1 tsp powder with honey daily)",
            "dose":           "1× daily morning, empty stomach",
            "vaidya_caveat":  "Skip if acid reflux active — consult vaidya for pitta-prakriti dose",
            "time_to_result": "4-6 weeks (immunity, eye health)",
        },
        "vedic": {
            "day":            "Sunday",
            "mantra":         "Om Hraam Hreem Hraum Sah Suryaya Namah",
            "count":          "108",
            "donation":       "Wheat + jaggery + red cloth at a temple Sunday morning",
            "gemstone":       "Manik (Ruby) 3-5 ct, copper, ring finger",
            "gem_caveat":     "Astrologer-fitted only. Synthetic ₹500-2000, natural ₹15K-2L. Get IGI/GIA cert.",
            "cost_inr_paid":  "15,000 – 2,00,000 (gemstone) | 0-200 (donation)",
            "free_alt":       "Tulsi-jal arpan to Sun OR feed jaggery-water to a cow Sunday",
        },
    },
    "Moon": {
        "for_areas": "mind, sleep, fluids, digestion, mother, hormones",
        "practical": {
            "action":         "Sleep window 10:30 PM-6 AM + screen-off 1 hr before bed + 2-3 L water/day + B12+thyroid blood test if mood-low",
            "why":            "Moon governs mind & fluids — sleep hygiene + hydration + thyroid panel directly fix 60% mood/fatigue cases. Faith doesn't fix B12 deficiency.",
            "time_to_result": "2-3 weeks (mood, energy)",
            "kpi":            "Sleep > 6.5 hr, B12 > 400 pg/ml, TSH 0.4-4.0",
            "free":           True,
            "cost_inr":       0,
        },
        "ayurvedic": {
            "practice":       "Bhramari pranayama 10 rounds at night + warm milk with nutmeg pinch + Sheetali pranayama for anger/heat",
            "herb":           "Brahmi (½ tsp powder OR vaidya-prescribed tablet) + Jatamansi for sleep",
            "dose":           "Brahmi 1× morning, Jatamansi 1× before bed",
            "vaidya_caveat":  "Brahmi can lower BP — skip if hypotensive. Vaidya consult for pregnancy.",
            "time_to_result": "4 weeks (sleep), 8 weeks (anxiety)",
        },
        "vedic": {
            "day":            "Monday",
            "mantra":         "Om Som Somaya Namah",
            "count":          "108",
            "donation":       "Milk + white rice + white cloth to a needy person Monday",
            "gemstone":       "Moti (Pearl) 4-6 ct, silver, ring finger",
            "gem_caveat":     "Natural ₹3K-50K. Real pearl drilled hole shows growth lines under loupe.",
            "cost_inr_paid":  "3,000 – 50,000 (gemstone)",
            "free_alt":       "Chandra namaskar at moonrise + Shiva Panchakshari japa",
        },
    },
    "Mars": {
        "for_areas": "blood, muscles, inflammation, accident-risk, surgery, anger",
        "practical": {
            "action":         "Daily 30-min walk + skip alcohol 21 days + CBC blood test in 7 days + drive defensively (no phone, seatbelt, no shortcuts)",
            "why":            "Mars rules blood + accidents — CBC catches anemia/inflammation EARLY; skipping alcohol drops BP+inflammation in 21 d; defensive driving cuts accident risk 70%.",
            "time_to_result": "1 week (CBC), 3 weeks (BP + sleep), 6 weeks (inflammation markers)",
            "kpi":            "Hb > 12 (F) / 13 (M), CRP < 3, BP < 130/85, zero close-call driving incidents",
            "free":           True,
            "cost_inr":       400,  # CBC test
        },
        "ayurvedic": {
            "practice":       "Sheetali pranayama 10 rounds + cooling diet (ghee, coconut, cucumber, mint) + avoid red meat & green chilli on Tuesday",
            "herb":           "Manjistha (½ tsp powder) for blood + Guduchi for inflammation + Ashwagandha if low energy",
            "dose":           "Manjistha 1× evening, Guduchi 1× morning",
            "vaidya_caveat":  "Manjistha thins blood — skip if on blood thinners. Pregnancy: vaidya only.",
            "time_to_result": "4-6 weeks (skin, blood markers)",
        },
        "vedic": {
            "day":            "Tuesday",
            "mantra":         "Om Ang Angarakaya Namah",
            "count":          "108",
            "donation":       "Red lentils (masoor) + red cloth + jaggery Tuesday",
            "gemstone":       "Moonga (Red Coral) 6-8 ct, copper, ring finger",
            "gem_caveat":     "TRIAL 3 days first — coral spikes anger in some. Italian deep-red genuine ₹5K-30K. Avoid 'Japanese' bleached.",
            "cost_inr_paid":  "5,000 – 30,000 (gemstone)",
            "free_alt":       "Hanuman Chalisa daily + Mangal-stotra Tuesday",
        },
    },
    "Mercury": {
        "for_areas": "skin, nervous, speech, lungs, intellect, anxiety",
        "practical": {
            "action":         "Screen-break 20-20-20 (every 20 min look 20 ft for 20 sec) + journaling 5 min/day + spirometry test if chest tight + dermatologist if skin",
            "why":            "Mercury rules nerves+lungs+skin — screen breaks fix 80% eye-strain; journaling cuts anxiety measurably (peer-reviewed); skin/lungs need real diagnosis, not mantra.",
            "time_to_result": "1 week (eye strain), 3 weeks (anxiety, journaling effect)",
            "kpi":            "Eye-strain rating < 3/10, anxiety scale (GAD-7) drop ≥ 4 pts in 3 wk",
            "free":           True,
            "cost_inr":       0,
        },
        "ayurvedic": {
            "practice":       "Nadi shodhana pranayama 10 rounds + tongue scraping AM + green moong khichdi 1 meal/day",
            "herb":           "Brahmi for nerves + Mandukaparni (Gotu Kola) for skin + Vasaka for lungs",
            "dose":           "Brahmi ½ tsp morning, Vasaka as syrup if cough",
            "vaidya_caveat":  "All herbs need vaidya for prakriti-specific dose. Brahmi+Mandukaparni can sedate.",
            "time_to_result": "4-6 weeks",
        },
        "vedic": {
            "day":            "Wednesday",
            "mantra":         "Om Bum Budhaya Namah",
            "count":          "108",
            "donation":       "Green moong + green cloth + camphor at Vishnu temple Wednesday",
            "gemstone":       "Panna (Emerald) 4-6 ct, gold, little finger",
            "gem_caveat":     "TRIAL 3 days first. Natural Colombian/Zambian ₹10K-1L. Beryllium-treated cheaper but unstable.",
            "cost_inr_paid":  "10,000 – 1,00,000 (gemstone)",
            "free_alt":       "Vishnu Sahasranama path + amla daily",
        },
    },
    "Jupiter": {
        "for_areas": "liver, pancreas, fat metabolism, immunity, weight",
        "practical": {
            "action":         "Lipid + LFT (liver function) + HbA1c blood test in 7 days + walk 30 min daily + reduce sugar+maida 80% + sleep 7 hr",
            "why":            "Jupiter rules liver+sugar+fat — these labs catch fatty-liver/pre-diabetes years before symptoms. Diet+walking REVERSES early fatty-liver in 12 weeks. Mantra alone reverses none.",
            "time_to_result": "8 weeks (LFT, HbA1c reduction), 12 weeks (visible weight)",
            "kpi":            "HbA1c < 5.7, LDL < 100, ALT/AST < 35, weight drop 3-5 kg in 12 wk if overweight",
            "free":           True,
            "cost_inr":       1500,  # Lipid+LFT+HbA1c panel
        },
        "ayurvedic": {
            "practice":       "Bhastrika pranayama 5 min + bitter greens (karela, methi, neem) 4×/week + skip alcohol completely",
            "herb":           "Bhumi-Amla for liver + Triphala at night + Guggulu (Yograj/Kanchnar) for weight",
            "dose":           "Triphala 1 tsp warm water bedtime; Guggulu vaidya-prescribed",
            "vaidya_caveat":  "Guggulu strong — skip if hyperthyroid. LFT must be tracked.",
            "time_to_result": "8-12 weeks",
        },
        "vedic": {
            "day":            "Thursday",
            "mantra":         "Om Brim Brihaspataye Namah",
            "count":          "108",
            "donation":       "Chana dal + turmeric + yellow cloth Thursday at temple",
            "gemstone":       "Pukhraj (Yellow Sapphire) 4-6 ct, gold, index finger",
            "gem_caveat":     "Generally safe. Natural Sri Lankan ₹15K-1.5L. Heated treated cheaper. Get cert.",
            "cost_inr_paid":  "15,000 – 1,50,000 (gemstone)",
            "free_alt":       "Vishnu Sahasranama or Guru-stotra Thursday + turmeric milk at night",
        },
    },
    "Venus": {
        "for_areas": "kidneys, reproductive, hormones, eyes, throat, skin-glow",
        "practical": {
            "action":         "Hydration 2.5-3 L/day + thyroid + reproductive hormone panel (PCOD/testosterone) + reduce sugar + walk after dinner",
            "why":            "Venus rules hormones+kidneys — hormone tests catch PCOD/thyroid/low-T which mimic 'bad luck in love/career'. Hydration drops kidney stress measurably.",
            "time_to_result": "12 weeks (hormone normalization with diet+exercise)",
            "kpi":            "TSH 0.4-4, AMH age-appropriate, creatinine < 1.0, skin-glow self-rating ≥ 7/10",
            "free":           True,
            "cost_inr":       2500,
        },
        "ayurvedic": {
            "practice":       "Cow ghee 1 tsp/day + Sheetali pranayama + abhyanga (oil-massage) 2×/week + clean white clothes Friday",
            "herb":           "Shatavari (women) for hormones + Gokshura (men) for reproductive + Yashtimadhu for throat",
            "dose":           "Shatavari ½ tsp warm milk evening; vaidya for menopause/pregnancy",
            "vaidya_caveat":  "Shatavari + hormonal-IUD users: vaidya consult mandatory. Estrogen-sensitive cancer history: skip.",
            "time_to_result": "8-12 weeks",
        },
        "vedic": {
            "day":            "Friday",
            "mantra":         "Om Shum Shukraya Namah",
            "count":          "108",
            "donation":       "White sweets (kheer/barfi) + curd + white cloth to a girl Friday",
            "gemstone":       "Heera (Diamond) 0.5-1 ct OR Opal 4-6 ct, silver, middle finger",
            "gem_caveat":     "Opal TRIAL 3 days. Natural opal ₹5K-1L. Diamond — buy only with GIA cert.",
            "cost_inr_paid":  "5,000 – 5,00,000 (depending on stone)",
            "free_alt":       "Lakshmi-stotra Friday + cow ghee in food",
        },
    },
    "Saturn": {
        "for_areas": "joints, bones, chronic conditions, teeth, knees, longevity",
        "practical": {
            "action":         "Vit-D + B12 + RA factor blood test + weight-bearing exercise 30 min × 4/wk + dental check + posture correction (chair, screen height)",
            "why":            "Saturn rules joints+chronic — Vit-D/B12/RA labs catch osteoporosis/RA decades early; weight-bearing builds bone density; posture fixes 70% chronic neck/back. Sesame oil massage helps but doesn't replace these.",
            "time_to_result": "12 weeks (Vit-D, posture pain), 6 months (bone density)",
            "kpi":            "Vit-D > 30, B12 > 400, RA factor negative, no daily joint pain",
            "free":           True,
            "cost_inr":       1200,
        },
        "ayurvedic": {
            "practice":       "Mahanarayan oil massage 2×/week + Vata-pacifying diet (warm, oily, cooked) + serve elderly weekly",
            "herb":           "Ashwagandha for vitality + Shallaki (Boswellia) for joints + Hadjod for bone",
            "dose":           "Shallaki vaidya-prescribed; Ashwagandha 500mg-1g/day max",
            "vaidya_caveat":  "Ashwagandha can spike thyroid — skip if hyperthyroid. Pregnancy: avoid.",
            "time_to_result": "8-12 weeks",
        },
        "vedic": {
            "day":            "Saturday",
            "mantra":         "Om Sham Shanaishcharaya Namah",
            "count":          "108",
            "donation":       "Mustard oil + black urad + black cloth + iron at Shani temple Saturday",
            "gemstone":       "Neelam (Blue Sapphire) 4-6 ct, silver/panchdhatu, middle finger",
            "gem_caveat":     "STRICT 3-day TRIAL — 30% feel adverse (sleep loss, irritability) and must remove. Natural Kashmir blue ₹50K-50L. Heated Sri Lankan ₹10K-1L. Without astrologer + trial = DON'T buy.",
            "cost_inr_paid":  "10,000 – 50,00,000 (rare Kashmir)",
            "free_alt":       "Hanuman Chalisa Saturday + Shani-stotra + sesame-oil self-massage",
        },
    },
    "Rahu": {
        "for_areas": "anxiety, sudden ailments, skin allergies, addiction, mystery diagnoses",
        "practical": {
            "action":         "Allergy panel + Vit-D + thyroid + reduce phone screen 1 hr/day + therapy/counsellor if anxiety chronic + journaling",
            "why":            "Rahu = unknowns/anxiety — most 'mystery' issues are deficiencies (Vit-D/B12/iron) or anxiety. Therapy proven 4-8 wk for GAD. Allergy panel finds real triggers.",
            "time_to_result": "4 weeks (therapy effect), 8 weeks (lab-driven supplement effect)",
            "kpi":            "GAD-7 < 5, allergy triggers identified, Vit-D > 30",
            "free":           True,
            "cost_inr":       2000,  # allergy panel + supplements
        },
        "ayurvedic": {
            "practice":       "Bhramari + Sheetali pranayama + grounding walks barefoot on grass 10 min + reduce taamasic food (fried, leftover, alcohol)",
            "herb":           "Brahmi + Jatamansi for anxiety + Triphala for gut-brain axis",
            "dose":           "Brahmi morning, Jatamansi night (vaidya-fitted)",
            "vaidya_caveat":  "Standard cautions — Brahmi+Jatamansi can sedate.",
            "time_to_result": "6-8 weeks",
        },
        "vedic": {
            "day":            "Saturday (or Wednesday)",
            "mantra":         "Om Bhram Bhrim Bhraum Sah Rahave Namah",
            "count":          "108",
            "donation":       "Black urad + black cloth + coconut + radish Saturday",
            "gemstone":       "Gomed (Hessonite) 5-7 ct, silver, middle finger",
            "gem_caveat":     "TRIAL 3 days. Sri Lankan brownish-orange ₹3K-30K. Confused with citrine.",
            "cost_inr_paid":  "3,000 – 30,000",
            "free_alt":       "Durga Saptashati / Bhairav-stotra + keep silver coin under pillow",
        },
    },
    "Ketu": {
        "for_areas": "auto-immune, infections, mysterious/idiopathic, spine, eyes",
        "practical": {
            "action":         "ANA + thyroid antibody + B12 panel (auto-immune screen) + spine X-ray if back pain + meditation 10 min/day + qualified rheumatologist if labs flag",
            "why":            "Ketu = idiopathic/auto-immune — modern labs (ANA, anti-TPO) catch lupus/Hashimoto's etc that mantras NEVER fix. Meditation has measurable cortisol effect.",
            "time_to_result": "4-8 weeks (lab clarity + meditation effect)",
            "kpi":            "ANA negative or known + tracked, anti-TPO < 35, meditation streak > 21 days",
            "free":           True,
            "cost_inr":       1800,
        },
        "ayurvedic": {
            "practice":       "Pranayama + spiritual sadhana / silence 10 min + til (sesame) in diet + ghee massage on spine weekly",
            "herb":           "Ashwagandha + Guduchi for immunity + Shankhpushpi for nervous-system",
            "dose":           "Vaidya-prescribed for auto-immune (delicate)",
            "vaidya_caveat":  "Auto-immune cases — herbs can flare; ALWAYS pair with rheumatologist.",
            "time_to_result": "8-12 weeks",
        },
        "vedic": {
            "day":            "Tuesday (or Saturday)",
            "mantra":         "Om Sram Srim Sraum Sah Ketave Namah",
            "count":          "108",
            "donation":       "Sesame seeds + multi-coloured cloth + blanket Saturday",
            "gemstone":       "Lehsunia (Cat's Eye) 5-7 ct, silver, middle finger",
            "gem_caveat":     "TRIAL 3 days. Chrysoberyl natural ₹15K-2L. Many fakes — IGI cert mandatory.",
            "cost_inr_paid":  "15,000 – 2,00,000",
            "free_alt":       "Ganesh Atharvashirsha + til daan",
        },
    },
}


# ════════════════════════════════════════════════════════════════════════
# MARRIAGE — 9 planets × 3 tiers
# Focus: relationship readiness, partner-search, marital harmony
# ════════════════════════════════════════════════════════════════════════
_MARRIAGE: Dict[str, Dict[str, Any]] = {
    "Venus": {
        "for_areas": "love-attraction, partner-quality, marital harmony",
        "practical": {
            "action":         "Update profiles (matrimony/social) with REAL recent photos + write 100-word self-honest bio + decide 5 non-negotiables in writing + meet 4 new people/month (event, hobby class, intro-via-friend)",
            "why":            "Venus = attraction. Engine timing only opens DOOR — practical reach (4 introductions/month vs 0) statistically multiplies match probability 8x. Writing non-negotiables prevents wrong choices in haste.",
            "time_to_result": "8-12 weeks (1-2 serious conversations)",
            "kpi":            "≥ 4 new introductions/month, profile updated, non-negotiables list written, 1 second-date",
            "free":           True,
            "cost_inr":       0,
        },
        "ayurvedic": {
            "practice":       "Cow ghee in food + abhyanga 2×/week + rose-water on face + soft white/cream clothes Friday",
            "herb":           "Shatavari (women) / Gokshura (men) for hormonal balance",
            "dose":           "½ tsp warm milk evening (vaidya-fitted)",
            "vaidya_caveat":  "Standard — pregnancy/hormonal disorder vaidya consult.",
            "time_to_result": "6-8 weeks (skin glow, confidence)",
        },
        "vedic": {
            "day":            "Friday",
            "mantra":         "Om Shum Shukraya Namah  AND  Om Kleem Kamadevaya Namah (108 each)",
            "count":          "108",
            "donation":       "White sweets + curd + white cloth to an unmarried girl Friday",
            "gemstone":       "Heera (Diamond) 0.5-1 ct OR Opal 4-6 ct, silver, middle finger",
            "gem_caveat":     "Opal trial 3 days. Diamond GIA cert mandatory.",
            "cost_inr_paid":  "5,000 – 5,00,000",
            "free_alt":       "Lakshmi-stotra Friday + visit Krishna/Radha temple weekly",
        },
    },
    "Jupiter": {
        "for_areas": "groom-quality (women), wisdom partner, in-laws, dharma alignment",
        "practical": {
            "action":         "Define values match (faith, family, finance) BEFORE meeting + ask discriminating Qs by date 3 (kids/career/parents) + family meet by date 6",
            "why":            "Jupiter = wisdom + values. Most marriages fail on UNSPOKEN value mismatch. Asking by D3 saves 6 months of confusion. Engine can't make good groom appear if you don't filter.",
            "time_to_result": "12 weeks (clear shortlist)",
            "kpi":            "Value-match scoring done for 3 prospects, family-meet for 1+",
            "free":           True,
            "cost_inr":       0,
        },
        "ayurvedic": {
            "practice":       "Vishnu Sahasranama + turmeric milk at night + chana-jaggery-sprouts in diet",
            "herb":           "Triphala + Ashwagandha for vitality",
            "dose":           "Standard",
            "vaidya_caveat":  "—",
            "time_to_result": "6 weeks (vitality)",
        },
        "vedic": {
            "day":            "Thursday",
            "mantra":         "Om Brim Brihaspataye Namah  AND  Om Gam Ganapataye Namah",
            "count":          "108",
            "donation":       "Chana dal + turmeric + yellow cloth + banana to a brahmin/teacher Thursday",
            "gemstone":       "Pukhraj (Yellow Sapphire) 4-6 ct, gold, index finger — TRADITIONALLY recommended for women seeking marriage",
            "gem_caveat":     "Generally safe. Natural Sri Lankan ₹15K-1.5L.",
            "cost_inr_paid":  "15,000 – 1,50,000",
            "free_alt":       "Thursday vrat (banana fast) + Vishnu temple weekly",
        },
    },
    "Mars": {
        "for_areas": "Mangal Dosh, marriage-energy, partner-aggression",
        "practical": {
            "action":         "Couples-counsellor session BEFORE marriage if both serious + temper-management book/course if quick anger + transparent about Mangal status with prospect (DON'T hide)",
            "why":            "Mangal Dosh statistical impact is OVERSTATED in popular astrology — 60-70% Indian women have it. Real predictor of marital trouble is communication/temper, NOT Mars. Counsellor 2 sessions catches 80% incompatibilities.",
            "time_to_result": "Immediate (transparency); 4 wk (temper drills)",
            "kpi":            "1 couple-counsellor session done OR 1 temper-mgmt course completed",
            "free":           True,
            "cost_inr":       3000,  # 1-2 counselor sessions
        },
        "ayurvedic": {
            "practice":       "Sheetali pranayama 10 rounds + cooling diet (ghee, mint, cucumber, coconut water) + skip red meat & green chilli Tuesday",
            "herb":           "Manjistha + Brahmi for cooling",
            "dose":           "Standard",
            "vaidya_caveat":  "—",
            "time_to_result": "4-6 weeks",
        },
        "vedic": {
            "day":            "Tuesday",
            "mantra":         "Om Ang Angarakaya Namah  AND  Hanuman Chalisa daily",
            "count":          "108",
            "donation":       "Red lentils + red cloth + jaggery Tuesday",
            "gemstone":       "Moonga (Red Coral) — but TRIAL first, can spike anger",
            "gem_caveat":     "Mangal Dosh classical remedies: Mangal Dosh Nivaran Puja (if both partners genuinely concerned). Cost ₹2K-25K — choose verified pandit.",
            "cost_inr_paid":  "2,000 – 25,000 (puja) | 5K-30K (coral)",
            "free_alt":       "Hanuman Chalisa Tuesday + visit Hanuman temple",
        },
    },
    "Moon": {
        "for_areas": "emotional connection, mother/family approval, intuition in choice",
        "practical": {
            "action":         "Sleep + mood baseline FIXED first (Moon-care basics) + don't make marriage decision in low-mood phase + journal 'what would I want my partner to know' 5 min/wk",
            "why":            "Moon = mind. Decisions made in unstable mood-state have 3x higher regret rate (psych research). Stabilize first, choose later.",
            "time_to_result": "3-4 weeks (mood baseline)",
            "kpi":            "Sleep > 6.5 hr × 21 days, journal kept ≥ 4 wk",
            "free":           True,
            "cost_inr":       0,
        },
        "ayurvedic": {
            "practice":       "Bhramari pranayama at night + warm milk with nutmeg + Brahmi/Jatamansi if anxious",
            "herb":           "Brahmi + Shankhpushpi",
            "dose":           "Standard, vaidya for pregnancy",
            "vaidya_caveat":  "Same as health.Moon",
            "time_to_result": "6 weeks",
        },
        "vedic": {
            "day":            "Monday",
            "mantra":         "Om Som Somaya Namah",
            "count":          "108",
            "donation":       "Milk + white rice + white cloth Monday",
            "gemstone":       "Moti (Pearl) 4-6 ct, silver, ring finger",
            "gem_caveat":     "Standard pearl quality check (loupe).",
            "cost_inr_paid":  "3,000 – 50,000",
            "free_alt":       "Monday vrat (one-meal) + Shiva temple",
        },
    },
    "Saturn": {
        "for_areas": "marriage delay, age-gap concerns, late-but-stable matches, in-law duty",
        "practical": {
            "action":         "Accept the delay productively — invest delay-years in (a) financial corpus 6-12 mo emergency fund, (b) skill upgrade, (c) sharper non-negotiables list. Saturn-delayed marriages historically more stable BECAUSE of better self-knowledge.",
            "why":            "Saturn delay is real but the OUTCOME post-delay is statistically BETTER than rushed Mars-Venus matches. Use the time. Don't panic-marry.",
            "time_to_result": "12-24 months (corpus + skill); marriage when chart opens",
            "kpi":            "6-mo emergency fund saved, 1 new skill certified, non-negotiables sharpened",
            "free":           True,
            "cost_inr":       0,
        },
        "ayurvedic": {
            "practice":       "Mahanarayan oil massage + Vata-pacifying diet + serve elderly weekly",
            "herb":           "Ashwagandha 500mg/day for vitality",
            "dose":           "Standard",
            "vaidya_caveat":  "Standard",
            "time_to_result": "6-8 weeks",
        },
        "vedic": {
            "day":            "Saturday",
            "mantra":         "Om Sham Shanaishcharaya Namah",
            "count":          "108",
            "donation":       "Mustard oil + black urad + black cloth + iron Shani temple",
            "gemstone":       "Neelam (Blue Sapphire) — STRICT trial — only if astrologer confirms benefic",
            "gem_caveat":     "30% adverse rate. Free alternatives strongly preferred.",
            "cost_inr_paid":  "10,000 – 50,00,000",
            "free_alt":       "Saturday Hanuman Chalisa + serve elderly weekly + Shani-stotra",
        },
    },
    "Sun": {
        "for_areas": "ego balance, father/family approval, public-image of partner",
        "practical": {
            "action":         "Father-conversation 1×/month if his approval matters + work on public-self confidence (1 social-skill book OR Toastmasters) + accept partner's ego-needs respectfully",
            "why":            "Sun = ego/father. 40% Indian marriage breakdowns trace to in-law/parent conflict. Direct conversation > silent assumption.",
            "time_to_result": "8 weeks",
            "kpi":            "Monthly call with father logged, 1 confidence-skill course done",
            "free":           True,
            "cost_inr":       0,
        },
        "ayurvedic": {
            "practice":       "Surya namaskar 12 rounds + Aditya Hridaya Stotra Sunday",
            "herb":           "Amla daily",
            "dose":           "Standard",
            "vaidya_caveat":  "—",
            "time_to_result": "6 weeks",
        },
        "vedic": {
            "day":            "Sunday",
            "mantra":         "Om Hraam Hreem Hraum Sah Suryaya Namah",
            "count":          "108",
            "donation":       "Wheat + jaggery Sunday",
            "gemstone":       "Manik (Ruby) — astrologer-fitted",
            "gem_caveat":     "Standard ruby caveats.",
            "cost_inr_paid":  "15,000 – 2,00,000",
            "free_alt":       "Tulsi-jal arpan to Sun + Aditya Hridaya Stotra",
        },
    },
    "Mercury": {
        "for_areas": "communication, intellectual compatibility, friendship-base",
        "practical": {
            "action":         "Communication-skill book (e.g. Crucial Conversations) + practice 'I-statements' instead of 'You always' + weekly 30-min uninterrupted talk with prospect/partner",
            "why":            "Mercury = communication. 70% of marital fights are bad-communication, not bad-people. Skill is learnable.",
            "time_to_result": "6 weeks",
            "kpi":            "1 book read, weekly talk-slot kept × 6 wk",
            "free":           True,
            "cost_inr":       400,  # 1 book
        },
        "ayurvedic": {
            "practice":       "Nadi shodhana + green moong khichdi 1 meal",
            "herb":           "Brahmi",
            "dose":           "½ tsp morning",
            "vaidya_caveat":  "Standard",
            "time_to_result": "6 weeks",
        },
        "vedic": {
            "day":            "Wednesday",
            "mantra":         "Om Bum Budhaya Namah",
            "count":          "108",
            "donation":       "Green moong + green cloth Wednesday",
            "gemstone":       "Panna (Emerald) — trial",
            "gem_caveat":     "Standard emerald.",
            "cost_inr_paid":  "10,000 – 1,00,000",
            "free_alt":       "Vishnu Sahasranama + amla daily",
        },
    },
    "Rahu": {
        "for_areas": "unconventional matches, inter-caste/foreign, sudden engagement",
        "practical": {
            "action":         "Verify identity HEAVILY (background, social, in-person family meet) + slow down impulsive engagement decisions + 90-day cooling-off rule for online-only relationships before commit",
            "why":            "Rahu = sudden + illusion. Online-romance fraud at all-time high in India. 90-day rule cuts risk 75%. Verify > trust.",
            "time_to_result": "Immediate risk-cut",
            "kpi":            "Background-check done, family meet done, 90-day rule observed",
            "free":           True,
            "cost_inr":       0,
        },
        "ayurvedic": {
            "practice":       "Bhramari + grounding walks barefoot grass",
            "herb":           "Brahmi + Jatamansi",
            "dose":           "Standard",
            "vaidya_caveat":  "Standard",
            "time_to_result": "6 weeks",
        },
        "vedic": {
            "day":            "Saturday",
            "mantra":         "Om Bhram Bhrim Bhraum Sah Rahave Namah",
            "count":          "108",
            "donation":       "Black urad + coconut Saturday",
            "gemstone":       "Gomed — trial",
            "gem_caveat":     "Standard hessonite.",
            "cost_inr_paid":  "3,000 – 30,000",
            "free_alt":       "Durga Saptashati path",
        },
    },
    "Ketu": {
        "for_areas": "spiritual partner, past-life karma, second-marriage healing",
        "practical": {
            "action":         "If second marriage / past trauma: 4-8 sessions trauma-informed therapy BEFORE re-marrying; 6-month healing minimum after divorce; spiritual partner search → check action-aligned values not just words",
            "why":            "Ketu = past-karma + detachment. Therapy after divorce statistically halves re-marriage breakdown. Skipping it perpetuates pattern.",
            "time_to_result": "8 weeks (therapy effect)",
            "kpi":            "≥ 4 therapy sessions, 6-mo healing window respected",
            "free":           True,
            "cost_inr":       8000,  # 4 sessions
        },
        "ayurvedic": {
            "practice":       "Meditation + til + ghee on spine",
            "herb":           "Ashwagandha + Shankhpushpi",
            "dose":           "Standard",
            "vaidya_caveat":  "Standard",
            "time_to_result": "8 weeks",
        },
        "vedic": {
            "day":            "Tuesday",
            "mantra":         "Om Sram Srim Sraum Sah Ketave Namah",
            "count":          "108",
            "donation":       "Sesame + multi-color cloth Saturday",
            "gemstone":       "Lehsunia — trial",
            "gem_caveat":     "Standard cat's eye.",
            "cost_inr_paid":  "15,000 – 2,00,000",
            "free_alt":       "Ganesh Atharvashirsha + til daan",
        },
    },
}


# ════════════════════════════════════════════════════════════════════════
# CAREER — 9 planets × 3 tiers
# Focus: job-search, promotion, business, skill, role-fit
# ════════════════════════════════════════════════════════════════════════
_CAREER: Dict[str, Dict[str, Any]] = {
    "Sun": {
        "for_areas": "leadership, government, authority, visibility, promotion",
        "practical": {
            "action":         "Updated CV + LinkedIn + 5-line elevator pitch + apply to 8 roles/week + ask manager DIRECTLY 'what's needed for promotion' in 1:1",
            "why":            "Sun = visibility. 'Direct ask' to manager moves promotion 6-12 mo faster (HR data). 8 apps/wk vs 1 statistically yields offer 6x faster.",
            "time_to_result": "8-12 weeks (first interview), 6 mo (promotion talk)",
            "kpi":            "8 applications/wk × 6 wk, 1 manager 1:1 with explicit ask",
            "free":           True,
            "cost_inr":       0,
        },
        "ayurvedic": {
            "practice":       "Surya namaskar + Aditya Hridaya Stotra Sunday + amla",
            "herb":           "Amla + Brahmi for confidence",
            "dose":           "Standard",
            "vaidya_caveat":  "—",
            "time_to_result": "6 weeks",
        },
        "vedic": {
            "day":            "Sunday",
            "mantra":         "Om Hraam Hreem Hraum Sah Suryaya Namah",
            "count":          "108",
            "donation":       "Wheat + jaggery + copper item Sunday",
            "gemstone":       "Manik (Ruby) — astrologer-fitted",
            "gem_caveat":     "Standard ruby.",
            "cost_inr_paid":  "15,000 – 2,00,000",
            "free_alt":       "Aditya Hridaya Stotra Sunday + Tulsi-jal to Sun",
        },
    },
    "Saturn": {
        "for_areas": "long-grind careers, service, justice, labour, persistence",
        "practical": {
            "action":         "Skill-deepening (Saturn rewards depth, not breadth) — pick ONE skill, 200 hours focused practice. Avoid job-hopping under Saturn — stay 18+ mo unless toxic. Build 12-mo emergency fund.",
            "why":            "Saturn = mastery via time. Job-hoppers under Saturn dasha penalized in resume gaps; stayers compound. 200 hr (Cal Newport rule) of deep work is the floor for promotion-grade skill.",
            "time_to_result": "6-12 months (visible skill jump)",
            "kpi":            "200 hr logged on 1 skill, 18-mo job-tenure milestone, 12-mo fund saved",
            "free":           True,
            "cost_inr":       0,
        },
        "ayurvedic": {
            "practice":       "Mahanarayan oil massage + Vata diet + serve elderly",
            "herb":           "Ashwagandha 500mg + Brahmi for focus",
            "dose":           "Standard",
            "vaidya_caveat":  "Standard",
            "time_to_result": "6 weeks (focus, energy)",
        },
        "vedic": {
            "day":            "Saturday",
            "mantra":         "Om Sham Shanaishcharaya Namah",
            "count":          "108",
            "donation":       "Mustard oil + black urad Saturday",
            "gemstone":       "Neelam — STRICT trial only",
            "gem_caveat":     "Free alternatives strongly preferred for career.",
            "cost_inr_paid":  "10,000 – 50,00,000",
            "free_alt":       "Saturday Hanuman Chalisa + serve elderly + Shani-stotra",
        },
    },
    "Mercury": {
        "for_areas": "IT, communication, sales, writing, accounts, analysis",
        "practical": {
            "action":         "1 cert/quarter (AWS/PMP/data/copy) + 1 portfolio piece public/quarter + reach out to 5 strangers on LinkedIn/wk for advice (cold-DM 100-word) — networking compounds",
            "why":            "Mercury = info exchange + cert/portfolio = direct hireability proof. 'Cold DM 100' rule generates 5-10 warm intros / 100 messages — measured.",
            "time_to_result": "12 weeks (visible portfolio + 1 cert)",
            "kpi":            "1 cert done, 1 portfolio piece live, 60 DMs sent in qtr",
            "free":           True,
            "cost_inr":       8000,  # 1 cert
        },
        "ayurvedic": {
            "practice":       "Nadi shodhana + green moong + tongue scraping",
            "herb":           "Brahmi + Mandukaparni for focus",
            "dose":           "Standard",
            "vaidya_caveat":  "Standard",
            "time_to_result": "6 weeks",
        },
        "vedic": {
            "day":            "Wednesday",
            "mantra":         "Om Bum Budhaya Namah",
            "count":          "108",
            "donation":       "Green moong + green cloth + camphor at Vishnu temple Wednesday",
            "gemstone":       "Panna (Emerald) — trial",
            "gem_caveat":     "Standard emerald.",
            "cost_inr_paid":  "10,000 – 1,00,000",
            "free_alt":       "Vishnu Sahasranama Wednesday + amla daily",
        },
    },
    "Jupiter": {
        "for_areas": "teaching, finance, law, advisory, dharma-aligned roles",
        "practical": {
            "action":         "Find a real mentor (DM 5/wk till 1 says yes) + read 1 domain-classic/quarter + take on 1 mentee yourself (teaching = 2x retention) + ethical-finance habit (10% save+invest auto-debit)",
            "why":            "Jupiter = guru + dharma. Mentorship measurably accelerates career 2-3 yr. Teaching others compounds your own depth. Finance discipline gives RUNWAY for right opportunity (vs panic-take wrong role).",
            "time_to_result": "6 months (mentor + classic), 12 mo (financial cushion)",
            "kpi":            "1 mentor monthly call, 4 classics read in year, 10% auto-save active",
            "free":           True,
            "cost_inr":       0,
        },
        "ayurvedic": {
            "practice":       "Bhastrika pranayama + bitter greens + skip alcohol",
            "herb":           "Triphala + Bhumi-Amla for liver clarity",
            "dose":           "Standard",
            "vaidya_caveat":  "Standard",
            "time_to_result": "8 weeks",
        },
        "vedic": {
            "day":            "Thursday",
            "mantra":         "Om Brim Brihaspataye Namah",
            "count":          "108",
            "donation":       "Chana dal + turmeric + yellow cloth + banana to teacher Thursday",
            "gemstone":       "Pukhraj (Yellow Sapphire) — generally safe, get cert",
            "gem_caveat":     "Standard pukhraj.",
            "cost_inr_paid":  "15,000 – 1,50,000",
            "free_alt":       "Thursday Vishnu Sahasranama + visit a teacher/guru weekly",
        },
    },
    "Mars": {
        "for_areas": "engineering, military, sports, sales-target, surgery, real-estate",
        "practical": {
            "action":         "Set 1 hard quarterly target (number-based) + daily morning 5-min planning + 30-min cardio 4×/wk + transparent peer-competition (state your goal publicly to 3 people for accountability)",
            "why":            "Mars = drive. Number-based targets (e.g. '20% revenue', 'Sub-3 marathon') compound; vague goals fail. Public commitment doubles follow-through (psych).",
            "time_to_result": "12 weeks (1 target met)",
            "kpi":            "1 quarterly number-target hit, 4 cardio sessions/wk × 12 wk",
            "free":           True,
            "cost_inr":       0,
        },
        "ayurvedic": {
            "practice":       "Sheetali pranayama + cooling diet + skip Tuesday red-meat",
            "herb":           "Manjistha + Brahmi (anger-calming)",
            "dose":           "Standard",
            "vaidya_caveat":  "Standard",
            "time_to_result": "6 weeks",
        },
        "vedic": {
            "day":            "Tuesday",
            "mantra":         "Om Ang Angarakaya Namah",
            "count":          "108",
            "donation":       "Red lentils + jaggery Tuesday",
            "gemstone":       "Moonga (Coral) — trial 3 days",
            "gem_caveat":     "Standard coral.",
            "cost_inr_paid":  "5,000 – 30,000",
            "free_alt":       "Hanuman Chalisa Tuesday",
        },
    },
    "Venus": {
        "for_areas": "creative, design, hospitality, beauty, luxury, fashion, arts",
        "practical": {
            "action":         "Build a public portfolio (Behance/Insta/website) + 1 paid client/quarter (even tiny) + invest 5% revenue into craft tools + style/grooming budget IS career-investment in these fields",
            "why":            "Venus = aesthetic + value. Visible portfolio + 1 paid client beats 'still learning' claim 10x to recruiters. In creative fields presentation IS the product.",
            "time_to_result": "12 weeks (portfolio + 1 paid)",
            "kpi":            "Portfolio live, 1 paid project done, 5% craft-tool reinvest",
            "free":           True,
            "cost_inr":       3000,  # tools / website
        },
        "ayurvedic": {
            "practice":       "Cow ghee + abhyanga + rose-water + clean Friday clothes",
            "herb":           "Shatavari/Gokshura per gender",
            "dose":           "Standard",
            "vaidya_caveat":  "Standard",
            "time_to_result": "6 weeks (skin-glow, energy)",
        },
        "vedic": {
            "day":            "Friday",
            "mantra":         "Om Shum Shukraya Namah",
            "count":          "108",
            "donation":       "White sweets + curd Friday",
            "gemstone":       "Heera/Opal — trial",
            "gem_caveat":     "Standard.",
            "cost_inr_paid":  "5,000 – 5,00,000",
            "free_alt":       "Lakshmi-stotra Friday",
        },
    },
    "Moon": {
        "for_areas": "people-roles (HR, hospitality, healthcare, public-facing), market-emotion (trading, journalism)",
        "practical": {
            "action":         "Sleep + mood baseline FIRST (Moon-care basics) + emotional-intelligence skill (1 EI book + practice naming-emotions journal) + don't make career switch in low-mood phase",
            "why":            "Moon = emotion. People-roles need stable mood baseline. EI score predicts 58% of job performance in service roles (Goleman).",
            "time_to_result": "4 weeks (mood), 8 wk (EI)",
            "kpi":            "Sleep > 6.5 hr × 21 d, 1 EI book read, journal kept 6 wk",
            "free":           True,
            "cost_inr":       400,
        },
        "ayurvedic": {
            "practice":       "Bhramari + warm milk + Brahmi/Jatamansi if anxious",
            "herb":           "Brahmi + Jatamansi",
            "dose":           "Standard",
            "vaidya_caveat":  "Standard",
            "time_to_result": "6 weeks",
        },
        "vedic": {
            "day":            "Monday",
            "mantra":         "Om Som Somaya Namah",
            "count":          "108",
            "donation":       "Milk + white rice Monday",
            "gemstone":       "Moti (Pearl)",
            "gem_caveat":     "Standard",
            "cost_inr_paid":  "3,000 – 50,000",
            "free_alt":       "Monday Shiva temple + Chandra namaskar",
        },
    },
    "Rahu": {
        "for_areas": "tech, foreign, novel/unconventional, viral/influencer, crypto, gambling-domains",
        "practical": {
            "action":         "Go where the FUTURE is (1 emerging tech: AI/ML/blockchain/biotech — 100 hr learning) + foreign market exposure + AVOID get-rich-quick schemes (Rahu's trap) + verify every offer 2× before commit",
            "why":            "Rahu = unconventional + sudden. Genuine Rahu success comes from EARLY adoption of REAL emerging field, not gambling. 100 hr in AI/ML in 2026 = 5-yr career multiplier. Get-rich schemes = life-savings loss.",
            "time_to_result": "6 months (skill + offer)",
            "kpi":            "100 hr logged on emerging tech, 0 get-rich schemes joined",
            "free":           True,
            "cost_inr":       0,
        },
        "ayurvedic": {
            "practice":       "Bhramari + grounding walks + reduce screen 1 hr",
            "herb":           "Brahmi + Jatamansi",
            "dose":           "Standard",
            "vaidya_caveat":  "Standard",
            "time_to_result": "6 weeks",
        },
        "vedic": {
            "day":            "Saturday",
            "mantra":         "Om Bhram Bhrim Bhraum Sah Rahave Namah",
            "count":          "108",
            "donation":       "Black urad + coconut Saturday",
            "gemstone":       "Gomed — trial",
            "gem_caveat":     "Standard hessonite.",
            "cost_inr_paid":  "3,000 – 30,000",
            "free_alt":       "Durga Saptashati Saturday",
        },
    },
    "Ketu": {
        "for_areas": "research, spiritual, occult, niche-specialist, code-deep-work, isolated-mastery",
        "practical": {
            "action":         "Pick a NICHE (Ketu rewards depth) + 1000-hour rule on it + minimal social-media + do work that doesn't need recognition (will arrive late but compound)",
            "why":            "Ketu = detachment + mastery. Niche specialists out-earn generalists 2-5x in long-tail (Pareto). Less social-media = more deep work. Recognition lag is real but compensates.",
            "time_to_result": "12-24 months (visible niche authority)",
            "kpi":            "1 niche chosen, 250 hr logged in qtr, social-media usage < 30 min/day",
            "free":           True,
            "cost_inr":       0,
        },
        "ayurvedic": {
            "practice":       "Meditation 10 min + til + ghee spine massage",
            "herb":           "Ashwagandha + Shankhpushpi",
            "dose":           "Standard",
            "vaidya_caveat":  "Standard",
            "time_to_result": "8 weeks",
        },
        "vedic": {
            "day":            "Tuesday",
            "mantra":         "Om Sram Srim Sraum Sah Ketave Namah",
            "count":          "108",
            "donation":       "Sesame + multi-color cloth Saturday",
            "gemstone":       "Lehsunia — trial",
            "gem_caveat":     "Standard.",
            "cost_inr_paid":  "15,000 – 2,00,000",
            "free_alt":       "Ganesh Atharvashirsha + til daan",
        },
    },
}


# ════════════════════════════════════════════════════════════════════════
# MONEY / WEALTH — 9 planets × 3 tiers
# Focus: dhan-yog, savings, debt, investing, income-growth, expense-control
# (DELIBERATELY SEPARATE FROM CAREER — career = role/income-source,
#  money = what you DO with the income that arrives)
# ════════════════════════════════════════════════════════════════════════
_MONEY: Dict[str, Dict[str, Any]] = {
    "Jupiter": {
        "for_areas": "dhan-yog, long-term wealth, ethical investing, advisor-quality",
        "practical": {
            "action":         "Auto-debit 10-20% of monthly income to (a) index-fund SIP + (b) PPF/EPF on payday + read 1 personal-finance classic (Psychology of Money / Rich Dad) + meet a SEBI-registered advisor 1× before any big decision",
            "why":            "Jupiter = expansion via wisdom. Auto-debit on payday beats willpower 100% of the time. Index-fund SIP for 10 yr historically beats 85% active funds (SPIVA data). Advisor meeting prevents 1 bad decision = saves years of returns.",
            "time_to_result": "12 months (visible corpus), 5-10 yr (compound takeoff)",
            "kpi":            "10%+ auto-debit active × 12 mo, 1 finance classic read, 1 advisor meet logged",
            "free":           True,
            "cost_inr":       0,
        },
        "ayurvedic": {
            "practice":       "Bhastrika 5 min morning (clarity for money decisions) + skip alcohol Thursdays + bitter greens 1 meal/wk for liver-clarity",
            "herb":           "Triphala bedtime + Bhumi-Amla for liver clarity (clear-head decisions)",
            "dose":           "Triphala 1 tsp with warm water at night",
            "vaidya_caveat":  "Triphala is gentle — pregnancy: vaidya consult.",
            "time_to_result": "8 weeks (decision-clarity, energy)",
        },
        "vedic": {
            "day":            "Thursday",
            "mantra":         "Om Brim Brihaspataye Namah",
            "count":          "108",
            "donation":       "Chana dal + turmeric + yellow cloth + banana to a teacher Thursday",
            "gemstone":       "Pukhraj (Yellow Sapphire) 4-7 ct, gold, index finger — generally safe but get IGI/GIA cert",
            "gem_caveat":     "Natural pukhraj ₹15K-1.5L. Synthetic ₹1K-5K — always cert. Astrologer-fitted only.",
            "cost_inr_paid":  "15,000 – 1,50,000 (gemstone) | 0-200 (donation)",
            "free_alt":       "Thursday Vishnu Sahasranama + feed a cow OR donate 1 hr to a teacher / NGO",
        },
    },
    "Venus": {
        "for_areas": "luxury-spend control, lifestyle inflation, beauty/fashion budget, joint-finances with partner",
        "practical": {
            "action":         "30-day rule on any non-essential > ₹2,000 + monthly category-budget for beauty/dining/clothes (cap each at 5% income) + joint money-talk with spouse 1×/month if married + DELETE saved cards from shopping apps",
            "why":            "Venus = pleasure spending — biggest leak in 25-45 age band. 30-day rule cuts impulse buys 70%. Joint money-talks halve marital money fights (research). Saved-card deletion adds friction = drops spend 20-30%.",
            "time_to_result": "30 days (visible spend drop), 6 mo (corpus reappears)",
            "kpi":            "30-day rule logged, 3 budget categories capped, monthly money-date with spouse",
            "free":           True,
            "cost_inr":       0,
        },
        "ayurvedic": {
            "practice":       "Cow ghee 1 tsp morning (sattva clarity) + abhyanga (self-massage) Friday + clean white/light Friday clothes",
            "herb":           "Shatavari (women) / Gokshura (men) for grounded vitality",
            "dose":           "Standard, 500mg/day",
            "vaidya_caveat":  "Standard.",
            "time_to_result": "6 weeks",
        },
        "vedic": {
            "day":            "Friday",
            "mantra":         "Om Shum Shukraya Namah",
            "count":          "108",
            "donation":       "White sweets + curd + white cloth Friday (or to a young girl)",
            "gemstone":       "Heera (Diamond) / Opal — astrologer-fitted, high cost — most users skip",
            "gem_caveat":     "Diamond ₹50K-5L+. Opal ₹3K-30K. Free alternatives strongly preferred for this planet.",
            "cost_inr_paid":  "5,000 – 5,00,000 (gemstone)",
            "free_alt":       "Friday Lakshmi-stotra + feed/clothe a young girl OR support a girl-child education NGO ₹500/mo",
        },
    },
    "Mercury": {
        "for_areas": "tracking, accounting, tax, negotiation, side-income, calculation-discipline",
        "practical": {
            "action":         "Track every rupee for 30 days (Walnut/MoneyView/spreadsheet) + file taxes ON TIME (don't last-minute) + start ONE side-income skill (writing/coding/tutoring) — target ₹5K/mo extra in 90 days + read a tax-saving guide once",
            "why":            "Mercury = data + commerce. Tracking ALONE drops spend 15-20% (visibility effect). Side-income compounds — ₹5K/mo invested = ₹10L+ in 10 yr. Tax filing on time avoids penalty + enables loan eligibility.",
            "time_to_result": "30 days (visibility), 90 days (first side-income), 1 yr (₹50-1L corpus)",
            "kpi":            "30-day tracker complete, ITR filed pre-deadline, ₹5K/mo side-income hit by day 90",
            "free":           True,
            "cost_inr":       0,
        },
        "ayurvedic": {
            "practice":       "Nadi shodhana 10 rounds morning (clarity for numbers) + green moong khichdi 1 meal/wk + tongue scraping daily",
            "herb":           "Brahmi ½ tsp morning (focus + memory for finance details)",
            "dose":           "Standard",
            "vaidya_caveat":  "Standard",
            "time_to_result": "6 weeks",
        },
        "vedic": {
            "day":            "Wednesday",
            "mantra":         "Om Bum Budhaya Namah",
            "count":          "108",
            "donation":       "Green moong + green cloth + camphor at Vishnu temple Wednesday",
            "gemstone":       "Panna (Emerald) 4-6 ct, gold/silver, little finger — trial 3 days",
            "gem_caveat":     "Natural panna ₹10K-1L. Many synthetics — IGI/GIA cert essential.",
            "cost_inr_paid":  "10,000 – 1,00,000",
            "free_alt":       "Wednesday Vishnu Sahasranama + amla daily + feed birds green moong",
        },
    },
    "Moon": {
        "for_areas": "emotional spending, comfort-buying, mother-related expenses, money-anxiety",
        "practical": {
            "action":         "Identify your emotional-spend trigger (sad/lonely/bored) + create non-money replacement (walk/call friend/journal) + emergency fund FIRST (3-6 mo expenses in liquid fund) + don't decide finances in low-mood phase",
            "why":            "Moon = mind. 40-60% of overspending is emotion-driven (behavioural finance). Naming the trigger drops it 50%. Emergency fund cuts money-anxiety more than any income raise (research).",
            "time_to_result": "4 weeks (mood-baseline), 6 mo (3-mo fund built)",
            "kpi":            "Trigger named in journal, replacement habit kept 21 d, 3-mo expenses in emergency fund",
            "free":           True,
            "cost_inr":       0,
        },
        "ayurvedic": {
            "practice":       "Bhramari pranayama at night + warm milk with nutmeg pre-bed + Sheetali for money-anxiety panic",
            "herb":           "Brahmi morning + Jatamansi night (calms money-anxiety, clearer decisions)",
            "dose":           "Standard",
            "vaidya_caveat":  "Brahmi can lower BP — skip if hypotensive. Pregnancy: vaidya only.",
            "time_to_result": "6 weeks",
        },
        "vedic": {
            "day":            "Monday",
            "mantra":         "Om Som Somaya Namah",
            "count":          "108",
            "donation":       "Milk + white rice + white cloth Monday (or to mother/elderly woman)",
            "gemstone":       "Moti (Pearl) 4-6 ct, silver, ring finger",
            "gem_caveat":     "Standard pearl, ₹3K-50K. Loupe-check growth lines.",
            "cost_inr_paid":  "3,000 – 50,000",
            "free_alt":       "Monday Shiva temple visit + Chandra namaskar + speak to mother weekly",
        },
    },
    "Mars": {
        "for_areas": "debt management, EMI burden, real-estate, aggressive investing, loan discipline",
        "practical": {
            "action":         "Aggressive debt-snowball (highest-interest debt FIRST: credit-card 36-42%, then personal loan, then home/car) + NO new EMI till existing debt-to-income < 35% + property buy ONLY if you can pay 30%+ down AND EMI < 35% of income",
            "why":            "Mars = aggression — direct it AT the debt. Credit-card debt at 36%+ is wealth-destroyer #1. 35% DTI is the bank-stress threshold. House-poor (over-EMI) is the #1 wealth trap of Indian middle-class.",
            "time_to_result": "12-24 months (CC debt cleared)",
            "kpi":            "0 credit-card balance carried, DTI < 35%, no new EMI till old cleared",
            "free":           True,
            "cost_inr":       0,
        },
        "ayurvedic": {
            "practice":       "Sheetali pranayama 10 rounds (cools money-rage / panic-decisions) + skip red meat & alcohol Tuesday + cooling diet (mint, cucumber, ghee, coconut)",
            "herb":           "Manjistha (blood) + Brahmi (calms aggressive money-decisions)",
            "dose":           "Standard",
            "vaidya_caveat":  "Manjistha thins blood — skip if on blood thinners.",
            "time_to_result": "6 weeks",
        },
        "vedic": {
            "day":            "Tuesday",
            "mantra":         "Om Ang Angarakaya Namah",
            "count":          "108",
            "donation":       "Red lentils (masoor) + jaggery + red cloth Tuesday",
            "gemstone":       "Moonga (Red Coral) 6-8 ct, copper, ring finger — TRIAL 3 days first",
            "gem_caveat":     "Coral can spike anger — bad for impulse-spend types. Italian deep-red ₹5K-30K. Free alternatives recommended.",
            "cost_inr_paid":  "5,000 – 30,000",
            "free_alt":       "Hanuman Chalisa Tuesday + Mangal-stotra (aggression channelled to debt-clearance)",
        },
    },
    "Sun": {
        "for_areas": "father/family wealth, government dues, authority-spending, status-spending",
        "practical": {
            "action":         "Annual financial review with self/family (net-worth + goals) + clear all govt dues (PAN/Aadhaar/property tax/LIC premiums) + reduce status-spend (car/phone/clothes for image) by 50% + 1:1 with father about family money on the table once",
            "why":            "Sun = authority + visibility. Untaxed income / unfiled returns destroy 5-yr wealth-building (penalty + ineligibility). Status-spend is invisible-wealth-killer in 30s. Family money-clarity prevents inheritance disputes.",
            "time_to_result": "3 months (govt clean-up), 6 mo (status-spend cut)",
            "kpi":            "Net-worth tracked annually, 0 govt dues outstanding, status-spend categories cut 50%",
            "free":           True,
            "cost_inr":       0,
        },
        "ayurvedic": {
            "practice":       "Surya namaskar 12 rounds at sunrise + Aditya Hridaya Stotra Sunday (clarity, vitality for sustained wealth-building)",
            "herb":           "Amla 1 fresh OR 1 tsp powder daily morning",
            "dose":           "Standard",
            "vaidya_caveat":  "Skip amla if acid-reflux active.",
            "time_to_result": "6 weeks",
        },
        "vedic": {
            "day":            "Sunday",
            "mantra":         "Om Hraam Hreem Hraum Sah Suryaya Namah",
            "count":          "108",
            "donation":       "Wheat + jaggery + copper item + red cloth Sunday morning",
            "gemstone":       "Manik (Ruby) 3-5 ct, copper/gold, ring finger — astrologer-fitted only",
            "gem_caveat":     "Synthetic ₹500-2K, natural ₹15K-2L. IGI/GIA cert essential. Trial first.",
            "cost_inr_paid":  "15,000 – 2,00,000",
            "free_alt":       "Sunday Aditya Hridaya Stotra + Tulsi-jal arpan to Sun + serve father weekly",
        },
    },
    "Saturn": {
        "for_areas": "discipline, long-corpus, pension, real-asset (gold/property), avoiding shortcuts",
        "practical": {
            "action":         "12-month emergency fund target (NOT 3-month — Saturn rewards excess buffer) + 30-yr horizon investing (NPS + index SIP, NOT trading) + skip ALL get-rich-quick schemes + 10% income to physical gold/sovereign-gold-bond annually for 10 yr",
            "why":            "Saturn = patience compounds. 12-mo buffer covers Saturn-dasha rough patches (job loss, health). NPS gives extra 80CCD(1B) deduction. SGB gives 2.5% interest + capital appreciation, beats physical gold. Trading is the Saturn-dasha trap.",
            "time_to_result": "5-10 years (visible compound), 20-30 yr (life-changing)",
            "kpi":            "12-mo emergency fund hit, NPS active, SGB / physical-gold 10% rule, 0 trading accounts opened",
            "free":           True,
            "cost_inr":       0,
        },
        "ayurvedic": {
            "practice":       "Mahanarayan oil massage 2×/wk + Vata-pacifying diet (warm, oily, grounding) + serve elderly weekly (Saturn karaka)",
            "herb":           "Ashwagandha 500mg/day (vitality for the long discipline)",
            "dose":           "Standard",
            "vaidya_caveat":  "Hyperthyroid: vaidya consult before ashwagandha.",
            "time_to_result": "6-8 weeks",
        },
        "vedic": {
            "day":            "Saturday",
            "mantra":         "Om Sham Shanaishcharaya Namah",
            "count":          "108",
            "donation":       "Mustard oil + black urad + iron item + black cloth at Shani temple Saturday",
            "gemstone":       "Neelam (Blue Sapphire) — STRICT TRIAL — 30% adverse rate, only if astrologer confirms benefic Saturn",
            "gem_caveat":     "Adverse reaction in 3 days = immediately remove. Free alternatives strongly preferred.",
            "cost_inr_paid":  "10,000 – 50,00,000",
            "free_alt":       "Saturday Hanuman Chalisa + serve elderly weekly + Shani-stotra + mustard oil to Shani",
        },
    },
    "Rahu": {
        "for_areas": "speculation, crypto, F&O, MLM, foreign currency, sudden gain/loss windows",
        "practical": {
            "action":         "ZERO trading / F&O / crypto > 5% of net-worth (cap is the rule, not the exception) + AVOID all MLM/network-marketing/get-rich schemes + verify EVERY 'guaranteed return' offer 3× + 90-day cooling-off on any 'urgent' investment opportunity",
            "why":            "Rahu = illusion + sudden. F&O retail loss-rate is 89% in India (SEBI 2023 study). MLM bottom 99% lose money. 'Urgent' offers are nearly always frauds. 90-day rule cuts scam-loss 80%+.",
            "time_to_result": "Immediate risk-cut",
            "kpi":            "Trading/crypto exposure < 5% NW, 0 MLM joined, 90-day rule logged",
            "free":           True,
            "cost_inr":       0,
        },
        "ayurvedic": {
            "practice":       "Bhramari + grounding walks barefoot grass + reduce screen 1 hr (Rahu rules screens/illusion)",
            "herb":           "Brahmi + Jatamansi (clarity vs Rahu's fog)",
            "dose":           "Standard",
            "vaidya_caveat":  "Standard",
            "time_to_result": "6 weeks",
        },
        "vedic": {
            "day":            "Saturday",
            "mantra":         "Om Bhram Bhrim Bhraum Sah Rahave Namah",
            "count":          "108",
            "donation":       "Black urad + coconut + black cloth Saturday (or to a beggar)",
            "gemstone":       "Gomed (Hessonite) — trial 3 days",
            "gem_caveat":     "Standard hessonite ₹3K-30K. Avoid if already prone to anxiety.",
            "cost_inr_paid":  "3,000 – 30,000",
            "free_alt":       "Saturday Durga Saptashati path + feed a black dog/crow",
        },
    },
    "Ketu": {
        "for_areas": "minimalism, hidden wealth-leak, occult/superstition spending, detachment-from-greed",
        "practical": {
            "action":         "Annual leak-audit: cancel unused subscriptions / EMIs / memberships (avg Indian leaks ₹2-5K/mo on this) + minimalism 1 month challenge (buy nothing non-essential) + STOP paying for occult/'guaranteed remedy' fees > ₹5,000 — most are exploitation",
            "why":            "Ketu = detachment + reveal-the-hidden. Subscription leak is the silent 5-15% income-bleed. Minimalism month resets baseline desire. Predatory 'astro/tantra' fees are the #1 spiritual-money trap (we are ASTROLOGY ENGINE saying this — credibility matters).",
            "time_to_result": "1 month (subscription audit), 3 mo (minimalism reset)",
            "kpi":            "Subscription audit done, 1 minimalism month logged, 0 paid 'guaranteed remedy' transactions > ₹5K",
            "free":           True,
            "cost_inr":       0,
        },
        "ayurvedic": {
            "practice":       "Meditation 10 min daily + til + ghee on spine 1×/wk + silent-day 1×/month",
            "herb":           "Ashwagandha + Shankhpushpi (clarity, detachment from compulsion)",
            "dose":           "Standard",
            "vaidya_caveat":  "Standard",
            "time_to_result": "8 weeks",
        },
        "vedic": {
            "day":            "Tuesday",
            "mantra":         "Om Sram Srim Sraum Sah Ketave Namah",
            "count":          "108",
            "donation":       "Sesame (til) + multi-color cloth Saturday",
            "gemstone":       "Lehsunia (Cat's Eye) — trial only, generally not for money topic",
            "gem_caveat":     "Standard cat's eye ₹15K-2L. Free alternatives strongly preferred.",
            "cost_inr_paid":  "15,000 – 2,00,000",
            "free_alt":       "Ganesh Atharvashirsha daily + til daan + 1 silent day/month",
        },
    },
}


# ════════════════════════════════════════════════════════════════════════
# BUSINESS / ENTREPRENEURSHIP — 9 planets × 3 tiers
# Focus: startup, partners, scaling, founder-fit, cashflow, hiring
# (DELIBERATELY SEPARATE FROM CAREER — career = employee track,
#  business = founder/owner track with different risk profile)
# ════════════════════════════════════════════════════════════════════════
_BUSINESS: Dict[str, Dict[str, Any]] = {
    "Sun": {
        "for_areas": "founder identity, vision-clarity, leadership, govt-licensing, brand-as-self",
        "practical": {
            "action":         "Write a 1-page company vision (mission + 3-yr goal + customer-promise) + register the entity properly (LLP/Pvt Ltd, GST, MSME) + clear 1:1 weekly with each direct report + state your role title clearly to the world (LinkedIn/website)",
            "why":            "Sun = visible authority. Vague founders attract vague teams. Registered entity (vs proprietorship after ₹40L turnover) saves tax + enables fundraising. Weekly 1:1s drop attrition 30%+.",
            "time_to_result": "1 month (vision + entity), 3 mo (team alignment)",
            "kpi":            "Vision doc written, entity registered, weekly 1:1 cadence active",
            "free":           True,
            "cost_inr":       12000,  # entity registration + GST
        },
        "ayurvedic": {
            "practice":       "Surya namaskar 12 rounds + Aditya Hridaya Stotra Sunday (founder vitality is the bottleneck)",
            "herb":           "Amla daily + Ashwagandha for stamina under load",
            "dose":           "Standard",
            "vaidya_caveat":  "Skip amla if acid-reflux; ashwagandha vaidya for hyperthyroid.",
            "time_to_result": "6 weeks",
        },
        "vedic": {
            "day":            "Sunday",
            "mantra":         "Om Hraam Hreem Hraum Sah Suryaya Namah",
            "count":          "108",
            "donation":       "Wheat + jaggery + copper item Sunday morning",
            "gemstone":       "Manik (Ruby) — astrologer-fitted",
            "gem_caveat":     "Standard ruby caveats. Cert essential.",
            "cost_inr_paid":  "15,000 – 2,00,000",
            "free_alt":       "Aditya Hridaya Stotra Sunday + Tulsi-jal arpan to Sun",
        },
    },
    "Mercury": {
        "for_areas": "sales, copy/marketing, accounting, contracts, founder-articulation, deal-negotiation",
        "practical": {
            "action":         "Talk to 10 customers/week (sales OR discovery — even after PMF) + write monthly investor/customer update (forces clarity) + cleanest possible accounts (Zoho/Tally + monthly P&L) + EVERY important deal in writing (email confirmation > verbal)",
            "why":            "Mercury = communication + commerce. 'Talk to 10 customers/wk' is the ONLY sustainable PMF / growth signal — beats every framework. Monthly P&L catches cashflow trouble 90 days before it kills you. Verbal-only deals are a top-3 startup-death cause.",
            "time_to_result": "4 weeks (customer signal), 12 wk (clean books)",
            "kpi":            "10 customer convos/wk × 12 wk, monthly P&L published, 0 verbal-only deals",
            "free":           True,
            "cost_inr":       6000,  # accounting software + CA fees first year
        },
        "ayurvedic": {
            "practice":       "Nadi shodhana morning (clarity for sales pitches) + green moong khichdi 1×/wk",
            "herb":           "Brahmi + Mandukaparni (focus + memory for product/customer detail)",
            "dose":           "Standard",
            "vaidya_caveat":  "Standard",
            "time_to_result": "6 weeks",
        },
        "vedic": {
            "day":            "Wednesday",
            "mantra":         "Om Bum Budhaya Namah",
            "count":          "108",
            "donation":       "Green moong + green cloth + camphor at Vishnu temple Wednesday",
            "gemstone":       "Panna (Emerald) — trial 3 days",
            "gem_caveat":     "Synthetics common — IGI/GIA cert essential.",
            "cost_inr_paid":  "10,000 – 1,00,000",
            "free_alt":       "Wednesday Vishnu Sahasranama + amla daily",
        },
    },
    "Jupiter": {
        "for_areas": "advisor/mentor, ethics, fundraising, dharma-of-business, equity-fairness",
        "practical": {
            "action":         "Get 2 real advisors (1 domain expert + 1 stage-ahead founder) — give them 0.5-1% advisory equity, monthly call + read 1 business classic / quarter (Zero to One, Hard Thing, High Output Mgmt) + ETHICAL bookkeeping (no fake invoices ever — destroys you in 5 yr)",
            "why":            "Jupiter = wisdom + dharma. 2 advisors prevent 80% rookie mistakes (YC data). Quarterly classics = the founder operating-system. Fake-invoice culture kills the company AT acquisition due-diligence — not before.",
            "time_to_result": "3 months (advisor cadence), 12 mo (decision-quality jump)",
            "kpi":            "2 advisors locked + monthly call, 4 classics/yr, clean books",
            "free":           True,
            "cost_inr":       0,
        },
        "ayurvedic": {
            "practice":       "Bhastrika 5 min + bitter greens 1 meal/wk + skip alcohol Thursday (Jupiter's day)",
            "herb":           "Triphala bedtime + Bhumi-Amla (liver clarity for big decisions)",
            "dose":           "Standard",
            "vaidya_caveat":  "Standard",
            "time_to_result": "8 weeks",
        },
        "vedic": {
            "day":            "Thursday",
            "mantra":         "Om Brim Brihaspataye Namah",
            "count":          "108",
            "donation":       "Chana dal + turmeric + yellow cloth + banana to a teacher Thursday",
            "gemstone":       "Pukhraj (Yellow Sapphire) — generally safe, get cert",
            "gem_caveat":     "Astrologer-fitted only. Cert essential.",
            "cost_inr_paid":  "15,000 – 1,50,000",
            "free_alt":       "Thursday Vishnu Sahasranama + meet a mentor / teach 1 hr free",
        },
    },
    "Venus": {
        "for_areas": "brand, design, customer-experience, partnerships, product-aesthetic, hospitality-vertical",
        "practical": {
            "action":         "Brand basics (logo + tagline + 5-page website + consistent visual identity) before scaling spend + 1 customer-delight ritual (handwritten note / surprise upgrade / NPS follow-up) + co-founder/partner agreement on PAPER from day 1 (vesting + roles + exit) — never verbal",
            "why":            "Venus = aesthetic + value-exchange + partnerships. Bad brand = 3-5x higher CAC. Customer-delight ritual = top driver of organic word-of-mouth. Founder-disputes are top-3 startup-killer (verbal partner deals are the trigger).",
            "time_to_result": "8 weeks (brand basics), immediate (partner agreement)",
            "kpi":            "Logo+website live, partner agreement signed (vesting+roles), 1 delight ritual running",
            "free":           True,
            "cost_inr":       25000,  # logo/website basics + lawyer fee for cofounder agreement
        },
        "ayurvedic": {
            "practice":       "Cow ghee morning + abhyanga Friday + clean Friday clothes",
            "herb":           "Shatavari/Gokshura per gender",
            "dose":           "Standard",
            "vaidya_caveat":  "Standard",
            "time_to_result": "6 weeks",
        },
        "vedic": {
            "day":            "Friday",
            "mantra":         "Om Shum Shukraya Namah",
            "count":          "108",
            "donation":       "White sweets + curd + white cloth Friday",
            "gemstone":       "Heera/Opal — astrologer-fitted",
            "gem_caveat":     "Diamond ₹50K-5L+. Free alternatives preferred.",
            "cost_inr_paid":  "5,000 – 5,00,000",
            "free_alt":       "Lakshmi-stotra Friday + delight a customer with personal note",
        },
    },
    "Mars": {
        "for_areas": "execution speed, ops, sales-target, founder-stamina, conflict-resolution, real-estate-business",
        "practical": {
            "action":         "ONE quarterly number (revenue / users / margin) — written, public to team + daily 5-min standup + founder physical fitness 4×/wk (the company runs on YOUR energy) + handle hard conversations within 48 hr (don't postpone partner/employee conflict)",
            "why":            "Mars = drive + courage. One-number focus beats 10-OKR confusion. Standups halve cycle time. Founder fitness directly correlates with company endurance (longitudinal studies). Postponed conflict compounds 10x.",
            "time_to_result": "1 quarter (number + cadence)",
            "kpi":            "1 quarterly number hit, daily standups × 12 wk, 4 fitness sessions/wk, 48-hr conflict rule",
            "free":           True,
            "cost_inr":       0,
        },
        "ayurvedic": {
            "practice":       "Sheetali pranayama 10 rounds (cools founder-burnout & impulsive decisions) + cooling diet + skip Tuesday red-meat",
            "herb":           "Manjistha + Brahmi (anger-channel + focus)",
            "dose":           "Standard",
            "vaidya_caveat":  "Standard",
            "time_to_result": "6 weeks",
        },
        "vedic": {
            "day":            "Tuesday",
            "mantra":         "Om Ang Angarakaya Namah",
            "count":          "108",
            "donation":       "Red lentils + jaggery Tuesday",
            "gemstone":       "Moonga (Coral) — TRIAL 3 days first (can spike anger)",
            "gem_caveat":     "Standard coral caveats.",
            "cost_inr_paid":  "5,000 – 30,000",
            "free_alt":       "Hanuman Chalisa Tuesday (channel drive at the goal, not at the team)",
        },
    },
    "Saturn": {
        "for_areas": "operations, processes, scaling-systems, retention, compliance, long-grind sustainability",
        "practical": {
            "action":         "Document EVERY repeated process (SOPs in Notion/Confluence) + 18-month runway target ALWAYS (not 6) + retention metrics > acquisition metrics (cohort/churn dashboards) + compliance calendar (GST/TDS/PF/ESI/ROC) — never miss a date",
            "why":            "Saturn = systems + time. Founders die at scale because nothing is documented (bus-factor-1). 18-mo runway lets you say NO to bad deals. Retention is the only true growth — leaky bucket kills you. Compliance penalty + ban-from-tendering is silent killer.",
            "time_to_result": "6 months (SOPs + dashboards), continuous",
            "kpi":            "10 SOPs documented, 18-mo runway maintained, monthly cohort/retention review, 0 compliance defaults",
            "free":           True,
            "cost_inr":       0,
        },
        "ayurvedic": {
            "practice":       "Mahanarayan oil massage + Vata diet + serve elderly weekly",
            "herb":           "Ashwagandha 500mg + Brahmi (long-grind stamina + focus)",
            "dose":           "Standard",
            "vaidya_caveat":  "Hyperthyroid: vaidya consult.",
            "time_to_result": "6-8 weeks",
        },
        "vedic": {
            "day":            "Saturday",
            "mantra":         "Om Sham Shanaishcharaya Namah",
            "count":          "108",
            "donation":       "Mustard oil + black urad + iron item Saturday",
            "gemstone":       "Neelam — STRICT trial only, free alternatives preferred",
            "gem_caveat":     "30% adverse rate — wrong-Saturn user gets worse not better.",
            "cost_inr_paid":  "10,000 – 50,00,000",
            "free_alt":       "Saturday Hanuman Chalisa + serve elderly + Shani-stotra",
        },
    },
    "Moon": {
        "for_areas": "team-mood, founder mental health, customer-empathy, B2C intuition, market-feel",
        "practical": {
            "action":         "Founder sleep 7+ hr non-negotiable (the company makes its worst decisions on tired founders) + monthly therapist/coach (founder isolation is real) + customer-empathy ritual (1 founder support-ticket / wk personally) + team-mood pulse-check monthly (1 simple form)",
            "why":            "Moon = mind + nurture. Sleep-deprived CEO decisions cost the company 5-10% revenue per quarter (research). Founder-therapy correlates with 2-3x longer company tenure. Personal support ticket keeps founder grounded in reality.",
            "time_to_result": "4 weeks (sleep + pulse), continuous",
            "kpi":            "Sleep > 6.5 hr × 21 d, monthly therapist OR peer-CEO group, 1 support-ticket/wk by founder, monthly mood-pulse",
            "free":           True,
            "cost_inr":       6000,  # 1 therapist session/mo
        },
        "ayurvedic": {
            "practice":       "Bhramari pranayama at night + warm milk + Brahmi/Jatamansi if anxious",
            "herb":           "Brahmi morning + Jatamansi night",
            "dose":           "Standard",
            "vaidya_caveat":  "Brahmi can lower BP — skip if hypotensive.",
            "time_to_result": "6 weeks",
        },
        "vedic": {
            "day":            "Monday",
            "mantra":         "Om Som Somaya Namah",
            "count":          "108",
            "donation":       "Milk + white rice + white cloth Monday",
            "gemstone":       "Moti (Pearl)",
            "gem_caveat":     "Standard pearl ₹3K-50K.",
            "cost_inr_paid":  "3,000 – 50,000",
            "free_alt":       "Monday Shiva temple + Chandra namaskar + speak to mother weekly",
        },
    },
    "Rahu": {
        "for_areas": "viral growth, sudden-scale, foreign markets, hype-product, AI/web3, fundraising-frenzy",
        "practical": {
            "action":         "Don't confuse VIRALITY with PMF (most viral hits churn at 95% in 30 d) + raise ONLY what you can deploy in 18 mo (over-fundraising kills focus + dilution) + verify EVERY 'too-good' partnership 2× + AVOID get-big-quick playbook (Rahu's classic trap)",
            "why":            "Rahu = sudden + illusion. WeWork / FTX / countless flameouts = Rahu un-channelled. Over-funded startups die more than under-funded (Causal Foundry data). Hype-product without retention is wealth-destruction at scale.",
            "time_to_result": "Immediate risk-cut",
            "kpi":            "Retention > viral-spike measured, raise size matches 18-mo plan, 2× partnership verification logged",
            "free":           True,
            "cost_inr":       0,
        },
        "ayurvedic": {
            "practice":       "Bhramari + grounding walks + reduce screen 1 hr/day",
            "herb":           "Brahmi + Jatamansi (clarity vs Rahu fog)",
            "dose":           "Standard",
            "vaidya_caveat":  "Standard",
            "time_to_result": "6 weeks",
        },
        "vedic": {
            "day":            "Saturday",
            "mantra":         "Om Bhram Bhrim Bhraum Sah Rahave Namah",
            "count":          "108",
            "donation":       "Black urad + coconut Saturday",
            "gemstone":       "Gomed — trial",
            "gem_caveat":     "Standard hessonite.",
            "cost_inr_paid":  "3,000 – 30,000",
            "free_alt":       "Saturday Durga Saptashati path",
        },
    },
    "Ketu": {
        "for_areas": "niche/wedge, deep-tech, R&D, founder-detachment-from-vanity, exit-readiness",
        "practical": {
            "action":         "Pick a NICHE wedge (Ketu rewards depth) — 'best in narrow' beats 'good in wide' for early-stage + minimal vanity-metric reporting (revenue + retention + cash, that's it) + always be 'exit-ready' (clean cap-table + clean books + signed agreements) — even if you never sell",
            "why":            "Ketu = detachment + mastery + reveal-hidden. Niche-wedge wins 5x more often than broad attack at < ₹50Cr ARR. Vanity-metric founders take longer to ship. Exit-ready hygiene means you can raise/sell/pivot in 30 days vs 6 months.",
            "time_to_result": "6 months (niche clarity), continuous (hygiene)",
            "kpi":            "1 niche wedge defined, 3-metric dashboard only, cap-table + books + agreements clean (founder-quarterly check)",
            "free":           True,
            "cost_inr":       0,
        },
        "ayurvedic": {
            "practice":       "Meditation 10 min daily + til + ghee on spine + silent half-day weekly",
            "herb":           "Ashwagandha + Shankhpushpi",
            "dose":           "Standard",
            "vaidya_caveat":  "Standard",
            "time_to_result": "8 weeks",
        },
        "vedic": {
            "day":            "Tuesday",
            "mantra":         "Om Sram Srim Sraum Sah Ketave Namah",
            "count":          "108",
            "donation":       "Sesame + multi-color cloth Saturday",
            "gemstone":       "Lehsunia — trial only",
            "gem_caveat":     "Standard cat's eye.",
            "cost_inr_paid":  "15,000 – 2,00,000",
            "free_alt":       "Ganesh Atharvashirsha + til daan + 1 silent day/month",
        },
    },
}


CATALOG: Dict[str, Dict[str, Dict[str, Any]]] = {
    "health":   _HEALTH,
    "marriage": _MARRIAGE,
    "career":   _CAREER,
    "money":    _MONEY,
    "business": _BUSINESS,
}


# ─── System / Area daily-practice tables (tier-1.5 — daily habits keyed
# by affected_systems / life-areas, NOT by planet) ─────────────────────

SYSTEM_PRACTICES: Dict[str, Dict[str, str]] = {
    # health systems (mirror health_engine `_affected_systems()` tags)
    "heart":         {"practice": "Anulom-vilom 10 min + walk 30 min + reduce salt + 1 fruit/day"},
    "eyes":          {"practice": "Trataka 5 min + 20-20-20 screen rule + triphala-water eye-wash"},
    "vitality":      {"practice": "Surya namaskar + ashwagandha (vaidya) + 7-8 hr sleep"},
    "bones":         {"practice": "Calcium-rich (sesame, ragi) + 15 min sun + weight-bearing"},
    "mind":          {"practice": "Bhramari 10 rounds + 10-min meditation + reduce caffeine"},
    "sleep":         {"practice": "Brahmi/jatamansi (vaidya) + screen-off 1 hr pre-bed + warm milk"},
    "fluids":        {"practice": "2-3 L water + jeera-saunf-ajwain water + reduce cold drinks"},
    "digestion":     {"practice": "Triphala bedtime + ginger pre-meals + eat sitting slowly"},
    "blood":         {"practice": "Anar/beetroot juice + tulsi water + iron-rich greens"},
    "muscles":       {"practice": "Light yoga + ashwagandha + sesame oil massage 2x/wk"},
    "inflammation":  {"practice": "Turmeric-pepper-water + omega-3 (flax/walnut) + reduce sugar+maida"},
    "accident_risk": {"practice": "Hanuman Chalisa + Mahamrityunjaya 11x + extra mindfulness driving"},
    "liver":         {"practice": "Bhastrika pranayama + bitter greens + skip alcohol"},
    "skin":          {"practice": "Neem-tulsi water bath + amla daily + reduce night-out fried"},
    "nervous":       {"practice": "Brahmi + abhyanga 2x/wk + nadi shodhana"},
    "kidneys":       {"practice": "Hydration + reduce salt + coriander seed water"},
    "reproductive":  {"practice": "Shatavari/Gokshura (vaidya) + pelvic yoga"},
    "joints":        {"practice": "Vata-pacifying diet + Mahanarayan oil massage"},
    "chronic":       {"practice": "Same daily dincharya + Mahamrityunjaya jaap; no shortcuts"},
    "anxiety":       {"practice": "Bhramari + Sheetali + grounding walks barefoot grass"},
    "auto-immune":   {"practice": "Anti-inflammatory diet + stress mgmt + qualified physician"},
    # marriage / relationship areas
    "communication": {"practice": "I-statements + weekly 30-min uninterrupted talk + 1 EI book"},
    "harmony":       {"practice": "Joint Friday meal + 1 weekly walk together + Lakshmi-stotra"},
    "in-laws":       {"practice": "Monthly call + 1 family meet/qtr + boundaries-with-respect script"},
    "trust":         {"practice": "100-day no-secret-sharing rule with partner + transparent finances"},
    # career areas
    "leadership":    {"practice": "Daily 5-min planning + monthly skip-level chat + 1 mentee"},
    "skill_depth":   {"practice": "200-hr deep-work block + 1 cert/qtr + portfolio piece public"},
    "networking":    {"practice": "5 cold-DMs/wk + 1 coffee-chat/wk + LinkedIn weekly post"},
    "stability":     {"practice": "12-mo emergency fund + 18-mo tenure + 10% auto-invest"},
    # money / wealth areas
    "savings":          {"practice": "Auto-debit 10-20% on payday + monthly net-worth tracker + 30-day rule on non-essential > ₹2K"},
    "debt":             {"practice": "Snowball highest-interest first (CC > PL > home) + 0 new EMI till DTI < 35% + weekly debt-balance log"},
    "investing":        {"practice": "Index-fund SIP + NPS + 5% cap on F&O/crypto + skip 'guaranteed return' offers"},
    "income_growth":    {"practice": "1 side-income skill (5K/mo target in 90d) + quarterly rate-review + 1 cert/yr in higher-pay skill"},
    "expense_control":  {"practice": "Track every rupee 30 days + delete saved cards + cancel unused subscriptions monthly"},
    "emergency_fund":   {"practice": "3-6 mo expenses in liquid fund FIRST + auto-top-up monthly + don't touch except emergency"},
    "credit_score":     {"practice": "Pay full CC bill + credit-utilisation < 30% + check CIBIL quarterly + dispute errors"},
    "taxes":            {"practice": "ITR pre-deadline + 80C/80D maxed + advance-tax quarterly if applicable + CA review annually"},
    "gold_assets":      {"practice": "10% income to SGB/sovereign-gold-bond annually + avoid digital-gold platforms with no SEBI cover"},
    # business / entrepreneurship areas
    "founders_fit":         {"practice": "Cofounder agreement on paper (vesting + roles + exit) + monthly founder retro + therapist OR peer-CEO group"},
    "product_market_fit":   {"practice": "10 customer convos/wk + retention > acquisition dashboard + 1 founder support-ticket/wk"},
    "cashflow":             {"practice": "Monthly P&L + 18-mo runway target + weekly burn-rate review + 0 verbal-only deals"},
    "hiring":               {"practice": "Slow hire fast fire + 90-day probation review + 2-ref minimum + culture-fit > skill-fit"},
    "sales_pipeline":       {"practice": "CRM with stage + weekly pipeline review + 10 outbound/wk founder-led until 5 sales hires"},
    "partnerships":         {"practice": "Verify 2× before signing + signed MoU > verbal + 90-day exit clause + quarterly review"},
    "scaling":              {"practice": "Document 10 SOPs/qtr + cohort-retention tracking + bus-factor > 1 on every critical role"},
    "brand":                {"practice": "Logo + 5-page site + consistent visual identity + 1 customer-delight ritual + monthly NPS"},
    "legal_compliance":     {"practice": "GST/TDS/PF/ESI/ROC compliance calendar + CA + lawyer on retainer + clean cap-table"},
}
