// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/tabbar/ElevatedFAB.tsx": () => import("../components/mockups/tabbar/ElevatedFAB.tsx"),
  "./components/mockups/tabbar/ExpandingChip.tsx": () => import("../components/mockups/tabbar/ExpandingChip.tsx"),
  "./components/mockups/tabbar/FloatingPill.tsx": () => import("../components/mockups/tabbar/FloatingPill.tsx")
};
