// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/compass-layouts/Classic.tsx": () => import("../components/mockups/compass-layouts/Classic.tsx"),
  "./components/mockups/compass-layouts/Mandala.tsx": () => import("../components/mockups/compass-layouts/Mandala.tsx"),
  "./components/mockups/compass-layouts/Octagon.tsx": () => import("../components/mockups/compass-layouts/Octagon.tsx"),
  "./components/mockups/tabbar/ElevatedFAB.tsx": () => import("../components/mockups/tabbar/ElevatedFAB.tsx"),
  "./components/mockups/tabbar/ExpandingChip.tsx": () => import("../components/mockups/tabbar/ExpandingChip.tsx"),
  "./components/mockups/tabbar/FloatingPill.tsx": () => import("../components/mockups/tabbar/FloatingPill.tsx"),
  "./components/mockups/screens/DoshAnalysis.tsx": () => import("../components/mockups/screens/DoshAnalysis.tsx"),
  "./components/mockups/screens/DoshDashboard.tsx": () => import("../components/mockups/screens/DoshDashboard.tsx"),
  "./components/mockups/screens/KundliMilan.tsx": () => import("../components/mockups/screens/KundliMilan.tsx"),
  "./components/mockups/screens/KundliMilanRing.tsx": () => import("../components/mockups/screens/KundliMilanRing.tsx"),
  "./components/mockups/screens/RiskAlert.tsx": () => import("../components/mockups/screens/RiskAlert.tsx"),
  "./components/mockups/screens/RiskAlertBold.tsx": () => import("../components/mockups/screens/RiskAlertBold.tsx")
};
