import React from "react";
import LegalScreen, { Section, P, Bullet, Strong, Callout } from "@/components/LegalScreen";

export default function DisclaimerScreen() {
  return (
    <LegalScreen
      title="Astrology Disclaimer"
      subtitle="Important — please read"
      lastUpdated="17 April 2026"
    >
      <Callout tone="warn">
        Cosmic Lens is intended for <Strong>spiritual exploration, self-reflection,
        and entertainment purposes only</Strong>. It is not a substitute for
        professional medical, legal, financial, psychological, or relationship
        advice.
      </Callout>

      <Section title="1. Nature of Astrology">
        <P>Vedic astrology (Jyotish) is an ancient art and philosophical
        tradition. The interpretations, predictions, dashas, doshas, muhurats,
        and remedies provided in Cosmic Lens reflect classical principles and
        modern algorithmic analysis. They are interpretive in nature and
        <Strong> not scientifically verifiable</Strong>.</P>
      </Section>

      <Section title="2. No Guaranteed Outcomes">
        <P>No astrological prediction or insight is guaranteed to come true.
        Outcomes in life depend on many factors — your free will, choices,
        actions, environment, and circumstances — that astrology cannot fully
        capture.</P>
      </Section>

      <Section title="3. Not a Substitute for Professionals">
        <P>Cosmic Lens content must <Strong>never</Strong> be used as the sole
        basis for important life decisions. Always consult appropriately
        qualified professionals:</P>
        <Bullet><Strong>Health concerns</Strong> — see a registered medical doctor. Do not stop or alter medication based on astrological readings.</Bullet>
        <Bullet><Strong>Mental health</Strong> — speak to a licensed psychologist or psychiatrist. If you are in crisis, call iCall (India) at 9152987821 or your local helpline.</Bullet>
        <Bullet><Strong>Legal matters</Strong> — consult a qualified lawyer.</Bullet>
        <Bullet><Strong>Financial / investment decisions</Strong> — consult a SEBI-registered investment advisor.</Bullet>
        <Bullet><Strong>Relationship & marriage</Strong> — consult a counsellor; compatibility scores should never replace open communication and consent.</Bullet>
      </Section>

      <Section title="4. AI-Generated Content">
        <P>The “Ask” feature uses automated software (rule-based and AI) to
        analyse your kundli. Answers are generated by code and may contain
        errors, omissions, contradictions, or culturally inappropriate phrasing.
        They are not endorsed by any individual astrologer.</P>
      </Section>

      <Section title="5. Remedies">
        <P>Suggested remedies (mantras, gemstones, donations, fasting, pujas)
        are drawn from classical texts. We do not guarantee any specific result
        from following them. <Strong>Consult a qualified Vedic astrologer or
        guru before adopting any remedy</Strong>, especially gemstones and
        mantras with seed-syllables (beej mantras).</P>
      </Section>

      <Section title="6. Birth-Data Accuracy">
        <P>Astrological calculations are highly sensitive to your time and
        place of birth. Even a 4-minute error in birth time can change your
        ascendant. We recommend verifying your birth time from a hospital
        record or birth certificate. Inaccurate input will produce inaccurate
        results.</P>
      </Section>

      <Section title="7. Cultural & Regional Differences">
        <P>Cosmic Lens uses traditional Vedic (Lahiri / Chitrapaksha) ayanamsa.
        Western, Tropical, KP, Krishnamurti, and Tantric astrologers may use
        different systems and arrive at different conclusions. None of these
        systems is “wrong” — they are different lenses.</P>
      </Section>

      <Section title="8. Emergency Situations">
        <Callout tone="danger">
          If you are experiencing a medical emergency or thoughts of self-harm,
          <Strong> please call your local emergency services immediately</Strong>.
          Do not rely on this app for crisis support. India: 112 (emergency),
          iCall 9152987821 (mental health).
        </Callout>
      </Section>

      <Section title="9. Acceptance">
        <P>By using Cosmic Lens you acknowledge that you have read and
        understood this disclaimer and agree to use the Service responsibly.</P>
      </Section>
    </LegalScreen>
  );
}
