"""100 real-life health/bimari Hindi questions — routing audit corpus."""
from __future__ import annotations

QUESTIONS: list[tuple[str, str]] = [
    # ── 1. Disease Diagnosis & Bimari Kab Shuru Hui? (25) ────────────────────
    ("Main pichle kaafi samay se bimar hoon, meri bimari sahi se kab detect (diagnose) hogi?", "diagnosis"),
    ("Doctor bimari pakad nahi paa rahe hain, kya yeh koi aisi bimari hai jo reports me nahi aayegi?", "diagnosis"),
    ("Kya meri bimari ka kaaran koi grah dosh (jaise Rahu ka bhram) hai ya sach me physical problem hai?", "diagnosis"),
    ("Mujhe achanak se health issues shuru ho gaye hain, iska main astrological reason kya hai?", "diagnosis"),
    ("Kya meri kundli me koi purani ya pustaini bimari (genetic disorder) active hone ka yoga chal raha hai?", "diagnosis"),
    ("Mujhe mansik tanaav (depression/anxiety) pichle kuch mahino se bohot zyada hai, isse rahat kab milegi?", "diagnosis"),
    ("Mere pet (stomach) ki samasya kab tak theek hogi? Kuch bhi khana hazam nahi hota.", "diagnosis"),
    ("Baar-baar thakan aur weakness rehna kab band hoga? Badani takat wapas kab aayegi?", "diagnosis"),
    ("Mujhe jo skin allergy ya infection hua hai, woh kab tak poori tarah saaf hoga?", "diagnosis"),
    ("Kya mere dental (daant) ya aankhon (eyes) ka chashma/problem isi dasha me badhne wala hai?", "diagnosis"),
    ("Haddiyon aur jodon ka dard (arthritis/joint pain) kab se shuru hua aur kab tak thama rahega?", "diagnosis"),
    ("Kya mujhe heart ke mamle me ya blood pressure (BP) ko lekar abhi se savdhan ho jana chahiye?", "diagnosis"),
    ("Hair fall aur hormonal imbalance ki problem kab tak control me aayegi?", "diagnosis"),
    ("Kya mujhe koi aisi bimari hone ke chances hain jiske liye mujhe life-long dawai khani pade?", "diagnosis"),
    ("Reports normal aa rahi hain par main andar se bimar feel karta hoon, yeh darr kab khatam hoga?", "diagnosis"),
    ("Kya meri dasha me koi food poisoning ya sudden allergy ka yoga chal raha hai?", "diagnosis"),
    ("Meri nind na aane ki bimari (insomnia) kis mahine tak theek ho sakti hai?", "diagnosis"),
    ("Kya bacho ki health ko lekar jo tension chal rahi hai, woh unke lagna lord ke strong hone se door hogi?", "diagnosis"),
    ("Weather change hote hi main bimar pad jata hoon, meri immunity kab tak strong hogi?", "diagnosis"),
    ("Kya mujhe apni diet ya lifestyle badalne ki sakht zaroorat is dasha me dikh rahi hai?", "diagnosis"),
    ("Spine ya back pain ki wajah se jo bed rest chal raha hai, woh kab tak chalega?", "diagnosis"),
    ("Meri kundli ka kaun sa paap grah is samay mere lagna ko peedit (afflict) kar raha hai?", "diagnosis"),
    ("Kya mujhe apni mental health ke liye kisi counselor ya psychiatrist ke paas jana padega?", "diagnosis"),
    ("Diabetes ya thyroid jaisi lifestyle bimariyo ka asar meri body par kab tak control hoga?", "diagnosis"),
    ("Kis specific planet ke gochar badalne se meri health me positive change aana shuru hoga?", "diagnosis"),
    # ── 2. Recovery, Ilaaj aur Doctor Badalta (25) ───────────────────────────
    ("Jo dawai main abhi kha raha hoon, uska asar kab se shuru hoga?", "recovery"),
    ("Kya mujhe maujuda doctor ko badal kar kisi doosre specialist ke paas jana chahiye?", "recovery"),
    ("Naya doctor jo ilaaj (treatment) shuru karega, kya woh mere liye safal (successful) rahega?", "recovery"),
    ("Meri health me improvement (sudhaar) kis mahine se dikhna shuru ho jayega?", "recovery"),
    ("Kya mujhe ayurvedic ya homeopathic ilaaj ki taraf shift ho jana chahiye? Fayda kab hoga?", "recovery"),
    ("Jo physical therapy ya rehab chal raha hai, usse recovery kab tak expected hai?", "recovery"),
    ("Kya meri reports agle check-up me normal aane ke chances hain?", "recovery"),
    ("Meri bimari me chal raha kharcha (medical bills) kab tak kam hoga?", "recovery"),
    ("Kya mujhe ilaaj ke liye apne shahar se door kisi bade hospital me jana padega?", "recovery"),
    ("Hospital se discharge kab tak milega? Genuinely ghar wapas kab aa paunga?", "recovery"),
    ("Kya mujhe doosre doctor se second opinion lena chahiye ya chal raha treatment sahi hai?", "recovery"),
    ("Dawaiyon ke side-effects se jo pareshani ho rahi hai, usse kab tak rahat milegi?", "recovery"),
    ("Kya dasha ke anusar meri health me koi miracle recovery (unexpected improvement) likhi hai?", "recovery"),
    ("Parivaar ke log jo meri dekhbhal kar rahe hain, unka support kab tak asar dikhayega?", "recovery"),
    ("Meri chronic illness (lambe samay ki bimari) kab tak completely control me aa jayegi?", "recovery"),
    ("Kya naye treatment ke liye bank se medical loan lena padega ya insurance claim pass ho jayega?", "recovery"),
    ("Insurance company policy ka paisa dene me delay karegi ya asani se pass hoga?", "recovery"),
    ("Mujh par chal raha koi purana grah dosh (jaise Mahadasha ka ant) kab ho raha hai taaki dava asar kare?", "recovery"),
    ("Kya yoga aur meditation karne se meri healing process fast ho sakti hai?", "recovery"),
    ("Meri weight loss ya weight gain ki journey me results kab se dikhne shuru honge?", "recovery"),
    ("Kya mujhe apni healing ke liye kisi dharmik sthal ya natural environment me thode din bitane chahiye?", "recovery"),
    ("Blood test aur scans ke aane wale naye results positive honge ya negative?", "recovery"),
    ("Kya body ke kisi organ ka transplant (jaise kidney/bone marrow) successful ho payega?", "recovery"),
    ("Doctor ne jo naya parhez (strict diet restrictions) bataya hai, use kab tak follow karna padega?", "recovery"),
    ("Meri body apni natural energy aur stamina kis saal tak poori tarah wapas paa legi?", "recovery"),
    # ── 3. Surgery & Operation Timing (25) ───────────────────────────────────
    ("Kya meri bimari bina operation ke sirf dawaiyon se theek ho sakti hai?", "surgery"),
    ("Agar surgery zaroori hai, toh operation kis mahine ya kis date ko karwana sabse safe rahega?", "surgery"),
    ("Surgery ke dauran koi complication ya blood loss ka khatra toh nahi dikh raha kundli me?", "surgery"),
    ("Kya operation ke baad infection hone ke chances hain, ya recovery smooth rahega?", "surgery"),
    ("Operation safal (successful) hone ke baad main kitne dino me dobara khada ho paunga?", "surgery"),
    ("Kya surgery par hone wala kharcha mere budget se bahar chala jayega?", "surgery"),
    ("Mujh par Mangal (Surgeon/Scars) aur Shani ka jo asar hai, kya woh surgery ko delay karwayega?", "surgery"),
    ("Kya mujhe emergency me operation karwana padega ya yeh planed surgery hogi?", "surgery"),
    ("Operation ke liye jo surgeon main select kiya hai, kya uske haath me mere liye shifa (healing) hai?", "surgery"),
    ("Kya operation ke baad body par koi permanent nishaan (scar) ya deformity reh jayegi?", "surgery"),
    ("Laser treatment ya minor surgery se kaam chal jayega ya badi open-surgery karni padegi?", "surgery"),
    ("Anaesthesia ke asar se hosh me aane me koi dikkat ya complication toh nahi hogi na?", "surgery"),
    ("Kya mujhe operation ke liye kisi acche mahurat (shubh lagna) ka wait karna chahiye?", "surgery"),
    ("Gallbladder, appendix ya kidney stone ki surgery kab tak final phase me pahuchegi?", "surgery"),
    ("Knee replacement ya joint surgery karwane ka sahi saal aur samay kab ban raha hai?", "surgery"),
    ("Kya surgery ke baad mujhe baar-baar hospital ke chakkar kaatne padenge?", "surgery"),
    ("Kisi purani surgery ke infection ka dobara active hone ka yoga toh nahi chal raha?", "surgery"),
    ("Kya operation ke baad meri dependent life khatam ho jayegi aur main independent ho jaunga?", "surgery"),
    ("Meri family me se kisi aur ki surgery ka yoga toh nahi ban raha is dasha me?", "surgery"),
    ("Kya surgery ke baad mujhe naye shehar ya foreign me aakar rest karna padega?", "surgery"),
    ("Operation theater me jaane se pehle mujhe kaun sa paath ya daan (remedy) karna chahiye?", "surgery"),
    ("Kya eye surgery (jaise Lasik ya Cataract) poori tarah safe rahegi mere liye?", "surgery"),
    ("Surgery ke baad pain-killers aur heavy dosage kab tak chalegi?", "surgery"),
    ("Kya doctor ki laparwahi (medical negligence) ki wajah se koi nuksan hone ka darr hai?", "surgery"),
    ("Kis nakshtra ke active hote hi meri surgery ka zakhm (wound) jaldi bhar jayega?", "surgery"),
    # ── 4. Mental Health, Longevity & Critical Care (25) ───────────────────────
    ("Is dasha me chal raha mansik tanaav aur rona-dhona kab band hoga?", "mental_critical"),
    ("Kya mujhe hamesha darr laga rehta hai ki mujhe koi badi bimari (jaise cancer ya kidney failure) toh nahi?", "mental_critical"),
    ("Meri kundli ka Rahu/Ketu ya Shani mere dimaag me overthinking aur panic attacks kab tak chalayenge?", "mental_critical"),
    ("Kya ICU ya critical care me chal rahe mere relative/family member ki jaan bachegi?", "mental_critical"),
    ("Doctor ne jawab de diya hai, kya ab sirf dua aur chamatkar (miracle) hi unhe bacha sakta hai?", "mental_critical"),
    ("Mere upar chal raha Mrityunjaya yoga ya bal-arishta dosh kab tak active hai?", "mental_critical"),
    ("Kya meri kundli me Alpayu (short life), Madhyayu (medium life) ya Deerghayu (long life) ka yoga hai?", "mental_critical"),
    ("Is dasha me chal rahi Markesh ya Badhakesh ki antardasha kab khatam hogi?", "mental_critical"),
    ("Kya gair-kanooni ya galat dawaiyon ke lene se meri mental aur physical health kharab ho rahi hai?", "mental_critical"),
    ("Memory loss (yaadash kam hona) aur dimaagi kamzori se kab tak mukti milegi?", "mental_critical"),
    ("Kya ghar ke vastu dosh ya kisi negative energy ki wajah se pariwar me sab bimar rehte hain?", "mental_critical"),
    ("Pichle janam ke paap (Karmic debt) ki wajah se kaun si bimari mujhe jhelni pad rahi hai?", "mental_critical"),
    ("Kya mujhe apni health ko theek rakhne ke liye apni job ya business se thode din ka break lena padega?", "mental_critical"),
    ("Paralyzed ya coma me gaye hue patient ke hosh me aane ke chances kis mahine me sabse strong hain?", "mental_critical"),
    ("Mujh par chal rahi Shani ki Saade Saati ya Dhaiya meri health ko aur kitna pareshan karegi?", "mental_critical"),
    ("Kya bache ke janam ke baad maa (mother) ki health poori tarah theek ho payegi?", "mental_critical"),
    ("Purani buri aadtein (jaise smoking, drinking ya bad addiction) kab tak chhoot payengi?", "mental_critical"),
    ("Bed-ridden (bistar par pade rehna) hone ke yoga se kab tak mukti milegi?", "mental_critical"),
    ("Kya aane wale samay me koi sudden accident ya physical injury ka darr toh nahi hai?", "mental_critical"),
    ("Meri dasha nath (dasha lord) kab mere 8th ya 12th house ke prabhav se mukt hoga?", "mental_critical"),
    ("Kya health theek na hone ki wajah se mera career aur career ka paisa dono barbad ho jayenge?", "mental_critical"),
    ("Mujh par chal rahe tantra-mantra ya nazar dosh ka asar kab khatam hoga?", "mental_critical"),
    ("Kya aatmavishwas (self-confidence) ki kami meri physical health ko aur down kar rahi hai?", "mental_critical"),
    ("Pariwar ke sabse bade sadasya (elderly member) ki health critical chal rahi hai, unka aage ka samay kaisa hai?", "mental_critical"),
    ("Life ka woh turning point year kaun sa hoga jab main poori tarah 'Disease-Free' (rog-mukt) ho jaunga?", "mental_critical"),
]

assert len(QUESTIONS) == 100
