"""100 real-life litigation / court / FIR Hindi questions — routing audit corpus."""
from __future__ import annotations

QUESTIONS: list[tuple[str, str]] = [
    # ── 1. Case Shuru, Police & FIR (25) ─────────────────────────────────────
    ("Mere khilaf jo FIR ya complaint hui hai, kya woh cancel (quash) ho payegi?", "fir_police"),
    ("Kya police mujhe arrest (giraftar) karne ke liye mere ghar ya office aayegi?", "fir_police"),
    ("Mujhe Anticipatory Bail (agrim zamanat) kab tak milegi? Approval ke kitne chances hain?", "bail"),
    ("Kya yeh mamla court jaane se pehle hi police station ke level par sulajh sakta hai?", "fir_police"),
    ("Kya mujhe jhoothe case (false implication) me fasaya gaya hai? Mera naam is case se kab hatega?", "fir_police"),
    ("Mujhe police investigation me kab tak support milega, ya police dushman ka sath degi?", "fir_police"),
    ("Kya mujhe court se summons ya notice kab tak serve hoga?", "fir_police"),
    ("Kya is case ki wajah se meri job chali jayegi ya suspend ho jaunga?", "fir_police"),
    ("Jo inquiry chal rahi hai (departmental ya police inquiry), uska report mere hit me aayega kya?", "fir_police"),
    ("Kya mujhe is legal case ke chakkar me jail (imprisonment) jaana padega?", "jail"),
    ("Jail me kitne din katne padenge aur regular bail kab tak manzoor hogi?", "bail"),
    ("Kya mere dushman ne police ko rishwat (bribe) dekar mere khilaf galat evidence banwaye hain?", "fir_police"),
    ("Kya mujhe court me peshi (hearing) ke dauran apni safety ka khatra hai?", "court_progress"),
    ("Is case ki wajah se mera passport zapt (seize) ho jayega kya? Main videsh ja paunga ya nahi?", "fir_police"),
    ("Mere khilaf look-out notice ya warrant kab tak jaari hone ka darr hai?", "fir_police"),
    ("Kya koi apna hi insaan (close relative/friend) mere khilaf gawaahi (evidence) dene wala hai?", "court_progress"),
    ("Police custody se mujhe kab tak rahat milegi?", "bail"),
    ("Kya digital evidence (CCTV, WhatsApp chats) court me mere haq me saboot banenge?", "court_progress"),
    ("Yeh case shuru kis grah ki dasha ya gochar ke chalte hua hai?", "fir_police"),
    ("Kya mujhe dushman ki taraf se physically harm pahunchane ki dhamki mil rahi hai, yeh kab rukega?", "fir_police"),
    ("Kya mujhe apna ghar chhodkar kuch dino ke liye underground hona padega?", "fir_police"),
    ("Police mere ghar par raid (chhapemari) kab tak kar sakti hai?", "fir_police"),
    ("Kya mere parivaar ke doosre sadasyo (parents/siblings) ka naam bhi is FIR me ghaseeta jayega?", "fir_police"),
    ("Jhootha case lagane wale par counter-case (defamation) kab aur kaise karun?", "fir_police"),
    ("Kis mahine me chal raha gochar mujhe is shuruaati legal tanaav se thodi rahat dega?", "fir_police"),
    # ── 2. Court Case Progress, Dates & Lawyers (25) ─────────────────────────
    ("Court me agli tareekh (hearing date) par kya hone wala hai? Kya judge faisla sunayega?", "court_progress"),
    ("Mera case pichle kayi saalo se latka hua hai, isme speed (tezi) kab aayegi?", "court_delay"),
    ("Jo vakeel (lawyer) maine kiya hai, kya woh sach me mehnat kar raha hai ya dushman se mila hua hai?", "lawyer"),
    ("Kya mujhe apna lawyer badal dena chahiye? Naya lawyer case ka rukh badal payega kya?", "lawyer"),
    ("Kya mujhe kisi bade ya expensive Senior Advocate ko hire karne ki zaroorat hai?", "lawyer"),
    ("Gawah (witness) court me mukar toh nahi jayega (turn hostile)? Gawaahi kab hogi?", "court_progress"),
    ("Court me jo cross-examination chal raha hai, usme hamara paksh kab tak mazboot hoga?", "court_progress"),
    ("Kya judge mere prati strict hai ya sympathetic hai? Judge ka mood mere haq me kab hoga?", "court_progress"),
    ("Kya mujhe court se koi Stay Order (injunction) mil payega taaki meri property/job bach sake?", "court_progress"),
    ("Case ke chakar me jo lagatar kharcha (vakeel ki fees, court fees) ho raha hai, usse kab tak rahat milegi?", "court_progress"),
    ("Kya mujhe free legal aid (sarkari madad) leni chahiye ya private hi sahi hai?", "lawyer"),
    ("Dushman court me baar-baar nayi dates (adjournments) le raha hai, yeh tareekh pe tareekh kab band hogi?", "court_delay"),
    ("Kya dushman ke paas koi aisa pukhta saboot hai jo mujhe hara sakta hai?", "court_progress"),
    ("Court ke paperwork me koi technical error toh nahi hai jisse mera case kamzor ho jaye?", "court_progress"),
    ("Kya mujhe lower court se harne ke baad High Court ya Supreme Court jana padega?", "court_progress"),
    ("Appeal file karne ka sahi samay kab ban raha hai?", "court_progress"),
    ("Kya court ke chakkar me mera business aur career poori tarah thapp (ruin) ho jayega?", "court_progress"),
    ("Court me jo arguments chal rahe hain, unka main turning point kis mahine me aayega?", "court_progress"),
    ("Kya meri kundli ka 6th lord (mukadma) is samay 10th house (judge) par bhaari pad raha hai?", "court_progress"),
    ("Kya case ke dauran mujhe court me mental trauma ya beizzati jhelni padegi?", "court_progress"),
    ("Gawaahon ko dushman dara-dhamka raha hai, unhe court tak surakshit kaise laya jaye?", "court_progress"),
    ("Kya court case me naye documents submit karne ki permission judge se kab tak milegi?", "court_progress"),
    ("Kya mera case fast-track court me shift ho sakta hai jaldi faisle ke liye?", "court_progress"),
    ("Kundli ka kaun sa shubh grah mere lawyer ke dimaag ko sahi strategy banane me madad karega?", "lawyer"),
    ("Court ki agli sunwai me kya mujhe khud physically present hona zaroori hai?", "court_progress"),
    # ── 3. Out-of-Court Settlement & Compromise (25) ───────────────────────
    ("Kya is case ko court ke bahar aapas me baithkar suljhana (compromise) sahi rahega?", "settlement"),
    ("Dushman khud compromise (samjhauta) karne ke liye kab tak mere paas aayega?", "settlement"),
    ("Mediation (madhyasthata) ya Lok Adalat me case sulajhne ke kitne percent chances hain?", "settlement"),
    ("Samjhauta karne ke liye dushman kitne paise (settlement amount) ki demand karega?", "settlement"),
    ("Kya mujhe dushman ki shartein maan leni chahiye ya court me ladte rehna chahiye?", "settlement"),
    ("Agar main paise dekar mamla khatam karoon, toh kya woh aage chalkar dobara case toh nahi karega?", "settlement"),
    ("Middleman (bicholiya) jo compromise kara raha hai, kya woh trustworthy (bharosemand) hai?", "settlement"),
    ("Mutual consent se divorce ya property partition ka agreement kab tak sign hoga?", "settlement"),
    ("Kya dushman thak-haar kar case wapas (withdraw) lene ke liye taiyar kab tak hoga?", "settlement"),
    ("Settlement ke paper sign karte samay koi dhoka ya shart chupayi toh nahi gayi na?", "settlement"),
    ("Kya out-of-court settlement isi mahine me hona likha hai ya abhi aur intezar hai?", "settlement"),
    ("Pariwar ke bade-buzurg is jhagde ko kab tak aapas me baithkar suljha payenge?", "settlement"),
    ("Kya mujhe settlement ke liye thoda jhukna padega ya mera paksh bhaari rahega?", "settlement"),
    ("Compromise hone ke baad court se case officially kab tak terminate/close hoga?", "settlement"),
    ("Kya dushman sirf time-waste karne ke liye compromise ka naatak kar raha hai?", "settlement"),
    ("Rahu ki dasha me chal raha yeh settlement kya aage chalkar koi naya vivad toh khada nahi karega?", "settlement"),
    ("Kya mujhe apne ego ko chhodkar khud samjhauta ka haath aage badhana chahiye?", "settlement"),
    ("Business partner ke sath chal raha dispute bina court gaye kab tak khatam ho sakta hai?", "settlement"),
    ("Kya arbitration (madhyasthata) ke zariye business deal ka jhagda sulajh jayega?", "settlement"),
    ("Settlement ke baad jo alimony ya compensation dena hai, uski dasha kab tak clear hogi?", "settlement"),
    ("Kya compromise ke baad dono paksh ke beech purani dushmani poori tarah khatam ho jayegi?", "settlement"),
    ("Kis date ko baithkar baat karna settlement ke liye sabse best rahega?", "settlement"),
    ("Kya dushman court ke samne apni galti manne ko taiyar hoga?", "settlement"),
    ("Settlement ki wajah se mera kitna paisa aur samay bachne wala hai?", "settlement"),
    ("Shani ka gochar badalte hi dono paksh me shanti ki baatein kab se shuru hongi?", "settlement"),
    # ── 4. Final Verdict, Jeet-Haar aur Penalty (25) ───────────────────────
    ("Is case ka final judgment (faisla) kab tak aayega?", "verdict"),
    ("Faisla mere hit (favour) me aayega ya main case haar jaunga?", "verdict"),
    ("Kya court mujhe poori tarah se dosh-mukt (acquit/babaazat bari) karega?", "verdict"),
    ("Agar haan, toh kya dushman is faisle ke khilaf upper court me appeal karega?", "verdict"),
    ("Case haarne par mujhe kitna fine, penalty ya compensation (muavza) dena padega?", "verdict"),
    ("Kya court meri property attach (seize/kurki) karne ka order de sakta hai?", "verdict"),
    ("Case jeetne ke baad mujhe dushman se kitna hargana (damages/compensation) milega?", "verdict"),
    ("Court ka jo faisla aayega, use implement (execute) hone me kitna samay lagega?", "verdict"),
    ("Kya mujhe court ke faisle se poora nyay (justice) milega ya adha-adhura?", "verdict"),
    ("Kya dushman ko uske jhoote case aur dhokhadhadi ke liye court saza sunayega?", "verdict"),
    ("Check bounce (Section 138) ke case me final decision aur recovery kab tak hogi?", "verdict"),
    ("Property dispute ka final partition decree court kab tak paas karega?", "verdict"),
    ("Labour court ya service tribunal se meri naukri aur back-wages ka faisla kab tak aayega?", "verdict"),
    ("Kya dasha ke anusar mere upar chal raha Shatru Hanta Yoga mujhe jeet dilwayega?", "verdict"),
    ("Final verdict ke din meri kundli ka chandra-bal (moon strength) mere paksh me hoga ya nahi?", "verdict"),
    ("Case jeetne ke baad jo relief milega, kya usse mera khoya hua samman (reputation) wapas aayega?", "verdict"),
    ("Court case ka yeh aakhiri daur meri life ka kitna bada turning point saabit hoga?", "verdict"),
    ("Kya final judgement ke dauran court room me koi hungama ya vivad hone ke chances hain?", "verdict"),
    ("Kya sarkar ya department court ke order ko manne se mana kar sakta hai?", "verdict"),
    ("Marital dispute (Section 498A/Maintenance) me court final maintenance kitna fix karega?", "verdict"),
    ("Kya dushman court ka faisla aane se pehle hi haar maan lega?", "verdict"),
    ("Court case ke is poore chakkar se mujhe aakhiri me kab tak poori tarah se mukti (closure) milegi?", "verdict"),
    ("Kis nakshtra aur tithi me aane wala faisla mere jivan ke is legal grahan ko khatam karega?", "verdict"),
    ("Kya final order ke baad bhi mujhe koi legal formalities poori karni padengi?", "verdict"),
    ("Life ka woh kaun sa saal (year) hoga jab main bina kisi court-kachhari ke darr ke chain ki nind so paunga?", "verdict"),
]
