"""English-only marriage copy templates (lang=en)."""
from __future__ import annotations

TEMPLATES_EN: dict[str, list[str]] = {
  "band_strong": [
    "Honestly, {name}'s chart shows a solid base for marriage — timing and choices still matter.",
    "This is the kind of chart where the marriage axis usually looks supportive; the bond grows with steady effort.",
    "Good news: marriage structure looks strong. Not perfectly effortless, but the foundation is solid.",
    "By chart, long-term partnership signals are mostly green — the rest depends on both of you.",
    "Marriage readiness shows clearly here — with patience, the relationship can deepen.",
    "Your chart supports the partnership house — that naturally gives a commitment-friendly tone.",
    "Marriage here looks both possible and promising — keep ego and rush under control.",
    "The chart backbone for marriage is strong — daily habits will decide how smooth it feels.",
  ],
  "band_moderate": [
    "Marriage is workable here — not perfectly effortless, but not doomed if you stay conscious.",
    "Mixed signals: some areas are strong, some need work — that's normal; don't panic.",
    "The chart says marriage can happen, but patience and clear talk will both be needed later.",
    "This is a middle-ground chart — good days and tense days will both come; communication is your best tool.",
    "The foundation is okay but not perfect — realistic expectations help marriage work.",
    "Some planets support, some test — balance comes from conscious effort.",
    "Marriage here feels like 'maybe with work' — don't rush the decision.",
    "The chart is neither very easy nor very hard — steady effort can make a workable match.",
  ],
  "band_strained": [
    "Straight talk: marriage is possible here but will ask for heavy effort — don't ignore red flags.",
    "The chart gives a strained tone — take compatibility and remedies seriously before wedding.",
    "This isn't an easy-pass chart — without patience, remedies, and realistic talk, friction can grow.",
    "Pressure on the marriage axis is high — not impossible, but blind optimism is risky.",
    "High-effort zone — if you move forward, maturity will be needed on both sides.",
    "The chart says a bond can form but will be tested — timing and partner choice are critical.",
    "Strained band means marriage won't feel easy by default — conscious work is required.",
    "The chart warns: proceed, but keep your eyes open and handle friction early.",
  ],
  "h7_benefic_only": [
    "Supportive planets ({benefics_in_7}) sit in the marriage zone — warmth and cooperation come more naturally.",
    "Soft influence on the 7th house ({benefics_in_7}) — building harmony with a partner is relatively easier.",
    "Good sign: benefic energy ({benefics_in_7}) in the marriage house — the relationship gets cushion.",
    "The partner house has support from {benefics_in_7} — this often gives a caring, balanced tone.",
    "The marriage zone is cushioned ({benefics_in_7}) — fights can happen but repair is usually possible.",
    "Planets {benefics_in_7} strengthen the marriage area — a signal of long-term softness.",
  ],
  "h7_malefic_only": [
    "Tough planets ({malefics_in_7}) press the marriage zone — fights or delay are common without effort.",
    "{malefics_in_7} in the 7th house — temper, ego, or distance themes need handling.",
    "Hard planets ({malefics_in_7}) press the marriage house — avoid rushed decisions.",
    "In the partner house, {malefics_in_7} — friction can feel higher if boundaries are weak.",
    "The chart says the marriage zone is tested ({malefics_in_7}) — patience and cool-down rules help.",
    "Malefic load ({malefics_in_7}) on the 7th — can create dramatic ups and downs.",
  ],
  "h7_mixed": [
    "Soft and hard planets mix in the marriage zone — good days and stressful days will both feel normal.",
    "Mixed 7th-house energy — closeness one day, distance the next; it's a chart pattern, not personal failure.",
    "The partner house has both plus and minus — daily communication tone will decide a lot.",
    "A mixed 7th house means chemistry is possible but stability needs conscious effort.",
    "The chart says the marriage zone is neither purely smooth nor purely harsh — balance is in your hands.",
  ],
  "h7_empty_strong_lord": [
    "The marriage house is empty but ruler {seventh_lord} is strong — the bond rests on the lord, clean but dependent.",
    "Empty 7th + strong {seventh_lord} — partnership results follow that planet's strength.",
    "No direct planets in the marriage zone, but {seventh_lord} is well placed — hidden strength.",
    "An empty 7th can keep things simple — with a strong {seventh_lord}, promise still looks good.",
    "Even if the marriage zone looks empty, {seventh_lord} gives backbone — keeping the lord strong matters.",
  ],
  "h7_empty_weak_lord": [
    "The marriage house is empty and ruler {seventh_lord} looks weak — the bond needs a clear anchor.",
    "Empty 7th + weak {seventh_lord} — relationship direction can feel unclear at times.",
    "No planet in the 7th and the lord under stress — build clarity and habits before marriage.",
    "Both the marriage zone and its ruler look soft — bring extra structure into the relationship.",
    "Empty partner house with weak {seventh_lord} — boundaries matter along with patience.",
  ],
  "lord_strong": [
    "Marriage ruler {seventh_lord} (house {seventh_lord_house}) is well placed — commitment capacity looks solid.",
    "{seventh_lord} is your marriage ruler and looks strong — long-term direction gets support.",
    "7th lord {seventh_lord} in supportive house {seventh_lord_house} — good marriage backbone.",
    "The chart says {seventh_lord} can carry marriage themes well.",
    "Strong {seventh_lord} placement — a natural base for stability in partnership.",
    "{seventh_lord} well placed in house {seventh_lord_house} — solid structural promise for marriage.",
  ],
  "lord_average": [
    "Marriage ruler {seventh_lord} sits in an average zone — neither very easy nor very hard by default.",
    "{seventh_lord} in house {seventh_lord_house} — outcome will mostly depend on choices and timing.",
    "The 7th lord is neither hero nor villain — daily effort sets the marriage tone.",
    "{seventh_lord}'s placement is neutral-ish — habits and partner match shape the final result.",
  ],
  "lord_weak": [
    "{seventh_lord} as marriage ruler is under stress — delays or tests in partnership may be more common.",
    "7th lord {seventh_lord} in a weak zone (house {seventh_lord_house}) — avoid unrealistic expectations.",
    "The chart says {seventh_lord} can't easily carry marriage promise — remedies and patience help.",
    "Weak marriage ruler {seventh_lord} — a bond can form but slowly and with conscious work.",
    "{seventh_lord} pressured in house {seventh_lord_house} — timing and partner chart both matter.",
    "Main marriage planet {seventh_lord} is in a struggle zone — a signal for effort, not an ending.",
  ],
  "lord_combust": [
    "The marriage ruler sits too close to the Sun — promise exists but delivering consistently may be harder.",
    "Combust 7th lord means the marriage significator can fade — you'll need to prove it through actions.",
    "The Sun overshadows the marriage ruler — steady behaviour matters more than words.",
  ],
  "lord_retrograde": [
    "The marriage ruler is retrograde — old patterns repeating or delay is a common trend.",
    "Retrograde 7th lord often replays karma — the same fight can return if the lesson is missed.",
    "Retrograde marriage ruler — don't rush; decide with slow clarity.",
  ],
  "d9_supportive": [
    "Inside the chart, long-term married life looks supportive — the bond can deepen over the years.",
    "The inner chart gives good marriage maturity — growth is possible even after the honeymoon phase.",
    "Post-wedding tone looks generally positive — the relationship can mature with realistic effort.",
    "Long-term marriage base is strong — even after early friction, settling in is likely.",
    "At Navamsa level, marriage theme is supportive — a signal of comfort years later.",
  ],
  "d9_mixed": [
    "Long-term tone is mixed — early phase and later years may feel different.",
    "The inner chart says married life will have ups and downs — adaptability is needed.",
    "Post-wedding life is neither purely smooth nor purely hard — phases will keep changing.",
    "D9 gives mixed signals — early marriage and life 5–7 years later may feel unlike each other.",
    "Long-term chart shows balance — patience can make the second phase better.",
  ],
  "d9_weak": [
    "The inner marriage chart looks strained — extra care and remedies help after wedding.",
    "Long-term married tone looks tested — keep expectations realistic and allow repair time.",
    "At Navamsa level, marriage theme is weak — possible friction signal years later.",
    "Post-wedding life shows chart pressure — conscious nurturing is necessary.",
    "The inner chart says a bond is possible but the long run will ask for more effort.",
  ],
  "manglik_active": [
    "Mangal dosh is active — anger, rush, or timing delay need handling; partner match matters.",
    "Manglik pressure is in the chart — channel fiery energy and avoid blind arguments.",
    "Active Mangal dosh — checking balance with the partner's chart is smart.",
    "Mars touches the marriage axis — remedies and cool-down habits genuinely help.",
    "Mangal dosh is on — not a curse, a warning: work on temper and timing.",
  ],
  "manglik_reduced": [
    "Mangal dosh is present but reduced by cancellation rules — still worth checking partner balance.",
    "Manglik is present but partly cancelled — normal caution, not panic.",
    "Mangal dosh in reduced form — remedies can smooth it further.",
    "Mars theme is in the chart but not fully active — still match consciously.",
  ],
  "karaka_strong_male": [
    "Venus (wife significator) is well placed — spouse-related promise looks naturally supportive.",
    "In a male chart, strong Venus — a good base to build partnership warmth.",
    "Wife karaka Venus is supportive — nurture romance and respect consciously.",
    "Good Venus placement — a natural chance to bring softness into marriage.",
  ],
  "karaka_weak_male": [
    "Venus (wife significator) is under pressure — appreciation and patience must be given consciously.",
    "In a male chart, Venus sits in a weak zone — don't ignore spouse themes.",
    "Wife karaka stressed — small gestures regularly, not only grand promises.",
    "Venus needs support — Friday rituals and genuine appreciation help.",
  ],
  "karaka_strong_female": [
    "Jupiter (husband significator) is well placed — husband theme looks supportive.",
    "In a female chart, strong Jupiter — wisdom and stability help in partner choice.",
    "Husband karaka Jupiter is supportive — respect and clarity both stay important.",
    "Good Jupiter placement — a base for guidance and growth in marriage.",
  ],
  "karaka_weak_female": [
    "Jupiter (husband significator) is under pressure — wisdom and patience are both needed in partner choice.",
    "In a female chart, Jupiter sits in a weak zone — don't commit in a rush.",
    "Husband karaka stressed — elders' input and Thursday discipline can help.",
    "Jupiter needs remedy support — align values before big decisions.",
  ],
  "kp_strong": [
    "The precision marriage layer is strong — commitment can solidify over time.",
    "KP signal is good — marriage promise gets structural support.",
    "Marriage cusp chain is supportive — shows capacity for a serious relationship.",
    "KP strong verdict — good long-term lock-in potential if behaviour matches.",
  ],
  "kp_weak": [
    "The precision marriage layer is weak — commitment will need time and proof.",
    "KP signal is soft — 'forever' may not feel immediate; it builds slowly.",
    "Marriage promise layer is tested — avoid rushed engagement.",
    "KP weak — a bond is possible structurally but trust must be earned.",
  ],
  "upapada_stable": [
    "The marriage manifestation point looks stable — wedding has a good chance to translate into real life.",
    "Upapada is supportive — focus on actual life partnership more than ceremony alone.",
    "Marriage manifestation axis is stable — good trend to settle into routine after the wedding.",
  ],
  "upapada_strained": [
    "The marriage manifestation point looks strained — practical life talk before wedding is necessary.",
    "Upapada shows pressure — plan reality more than fantasy.",
    "Marriage manifestation is tested — handle timing and family dynamics consciously.",
  ],
  "dasha_stress": [
    "The current phase is a bit sensitive — handle trust, temper, or confusion carefully.",
    "The current dasha window brings stress — slow big relationship decisions if you can.",
    "Life phase is testing now — pausing beats escalating fights with your partner.",
    "Dasha says friction may feel higher now — not permanent, but real.",
    "Stress window active — use a 24-hour cool rule before a communication break.",
    "Current timing may feel heated or confusing — repair is often easier later.",
  ],
  "dasha_repair": [
    "The current phase is a good window for repair and warmth — talk and clarify.",
    "Current dasha supports reconnection — if there's distance, reaching out now is worth it.",
    "Life phase is healing-friendly — small gestures can have a big impact.",
    "Dasha window is warm — a good time to clear misunderstandings.",
    "Repair phase active — honest conversation without ego helps.",
  ],
  "dasha_neutral": [
    "Current life phase is neutral — daily effort decides relationship tone.",
    "Dasha is neither extreme stress nor extreme romance — steady habits matter.",
    "Timing sits in a neutral zone — your behaviour shapes the final result.",
    "Life phase is balanced — stay consistent and avoid drama.",
  ],
  "dk_spouse": [
    "Spouse-sign planet {dk_planet} in house {dk_house} — you often attract this type of partner.",
    "{dk_planet} is your partner signature (house {dk_house}) — hints at their energy style.",
    "Darakaraka {dk_planet} says partner energy links to house {dk_house} themes.",
    "You tend to pull {dk_planet}-type partner energy — house {dk_house} shows where it plays out.",
    "{dk_planet} is the spouse marker — their nature will show house {dk_house} themes.",
    "Partner pattern: {dk_planet} influence with house {dk_house} flavour — explains attraction style.",
  ],
  "watchout_separation": [
    "The chart has distance/separation theme — keep repair time consciously; don't ignore it.",
    "Separation yoga pattern — don't turn small distance into a big break; talk early.",
    "Distance theme active — address physical or emotional gaps immediately.",
  ],
  "watchout_saturn_7": [
    "Saturn presses the marriage zone — delay, duty, or maturity tests are common.",
    "Saturn on the 7th axis — slow-burn relationship; don't expect instant fireworks.",
  ],
  "positive_generic": [
    "No major structural plus is missing — keep building daily trust.",
    "The chart has workable positives — don't ignore them.",
    "Foundation isn't completely broken — conscious love can keep improving it.",
    "Supportive hints are present — focus on them.",
  ],
  "watchout_generic": [
    "No big red flag, but open talk before major decisions is smart.",
    "No major warning, still keep patience and boundaries.",
    "The chart gives soft caution — don't rush.",
    "No extreme alert — still don't ignore small friction patterns.",
  ],
  "friction_saturn": [
    "Main friction: delay and distance theme — avoid ultimatums; keep patience.",
    "Saturn-type friction — relationship may feel slow; that's timing, not rejection.",
    "Duty-heavy or distant feel can appear — steady presence improves it.",
    "Main issue is a patience test — Saturday discipline and calm talk help.",
    "Friction feels Saturn-like — give time; don't force.",
  ],
  "friction_mars": [
    "Main friction: anger and impatience — use a cool-down rule before replying.",
    "Mars-type heat — fights can escalate fast if ego is active.",
    "Temper theme is strong — Tuesday calm rituals genuinely help.",
    "Main issue is heated arguments — channel Mars energy through physical activity.",
    "Friction is fiery — choose peace over winning the argument.",
  ],
  "friction_rahu": [
    "Main friction: confusion or impulsive decisions — clarity first, action later.",
    "Rahu-type confusion — overthinking or sudden choices can hurt the relationship.",
    "Trust and clarity can both be tested — avoid secrets and assumptions.",
    "Main issue is mental noise — Thursday quiet time improves decision quality.",
    "Friction is confusion-based — slow down before big promises.",
  ],
  "friction_venus": [
    "Main friction: appreciation gap or romance imbalance — express love; don't keep score.",
    "Weak Venus theme — small loving gestures regularly.",
    "Friction is about love language — effort will need to show.",
    "A gap in romance or respect may appear — fill it consciously.",
  ],
  "friction_jupiter": [
    "Main friction: wisdom or values mismatch — handle elders/respect themes carefully.",
    "Jupiter pressure — values clarity is needed in partner choice.",
    "Friction is about growth and values — align before you commit.",
    "Husband-sign theme stressed — patience and Thursday charity help.",
  ],
  "friction_generic": [
    "Main friction: daily communication — don't ignore small talks.",
    "Primary issue is habit-based — consistency will improve it.",
    "Friction is manageable if you discuss it early.",
    "Main tension point needs conscious effort — it's doable.",
    "This isn't a permanent block — it's a pattern that can change.",
    "Friction is real but not final — realistic talk makes it better.",
  ],
  "remedy_saturn": [
    "Simple remedy: Saturday sesame-oil lamp, patience ritual, and no ultimatums on Saturdays.",
    "Saturn remedy — slow steady effort, respect for elders, Saturday discipline.",
    "Try: keep Saturdays calm, sesame charity, and give your partner time.",
    "Remedy: Saturday light + patience — force won't calm Saturn.",
  ],
  "remedy_mars": [
    "Simple remedy: Tuesday Hanuman Chalisa, don't reply in anger, walk/cool down first.",
    "Mars remedy — Tuesday discipline and an anger pause rule.",
    "Try: Tuesday Hanuman path + channel heat through exercise.",
    "Remedy: ten minutes of silence before a fight — Mars energy settles.",
  ],
  "remedy_rahu": [
    "Simple remedy: Thursday Vishnu quiet time; avoid impulsive relationship decisions.",
    "Rahu remedy — clarity first; reduce social/media noise.",
    "Try: eleven minutes calm on Thursday + delay big decisions 48 hours.",
    "Remedy: don't commit while confused — Thursday discipline helps.",
  ],
  "remedy_venus": [
    "Simple remedy: Friday white sweets + say appreciation — stop score-keeping.",
    "Venus remedy — Friday ritual and a genuine compliment.",
    "Try: thank your partner on Friday without needing a reason.",
    "Remedy: put romance on the calendar — Venus responds.",
  ],
  "remedy_jupiter": [
    "Simple remedy: Thursday yellow charity; wisdom and elder respect in partner choices.",
    "Jupiter remedy — Thursday discipline + values clarity.",
    "Try: small donation Thursday + honest values talk with partner.",
    "Remedy: don't rush commit — Jupiter wants time and wisdom.",
  ],
  "remedy_generic": [
    "Simple remedy: light ritual on the 7th lord's weekday + weekly 20-min honest talk.",
    "Generic remedy — consistent small ritual + weekly check-in conversation.",
    "Try: small donation on the planet weekday + one shared habit with partner.",
    "Remedy: keep a weekly joint ritual — often the most practical fix.",
    "Simple fix: daily gratitude + weekly boundary talk — more powerful than chart fear.",
  ],
  "pro_lock_teaser": [
    "🔒 {hidden_count} hidden chart alerts + exact marriage dasha window — unlock in Pro.",
    "🔒 {hidden_count} deeper factors for {name} (timing, synastry, remedies) only in Pro report.",
    "🔒 Basic read the surface — {hidden_count} more layers locked in Pro PDF.",
    "🔒 Marriage timing, full friction map and remedy chain — Pro unlocks them.",
    "🔒 {hidden_count} karmic/detail points hidden — Pro gives the full picture.",
  ],
  "remedy_teaser": [
    "You got a small remedy hint — full remedy chain is in the Pro report.",
    "Basic gives direction only — exact weekday ritual + full remedy in Pro.",
    "Remedy preview here — personalized full remedy PDF in Pro.",
    "Surface tip isn't enough — complete remedy plan is locked in Pro report.",
  ],
  "pro_strip_partner": [
    "Pro for {name}: deep 7th read · dasha windows · synastry · full remedies · PDF",
    "{name}'s full read in Pro — timing, hidden alerts, remedy chain, PDF download",
    "Unlock {name}: deep 7th analysis + dasha + remedies — Basic is only a summary",
    "Want {name}'s complete marriage consultation? Everything is in the Pro report",
  ],
  "couple_gap_promising": [
    "Together score {couple_score} — promising base, but cross-chart depth is still locked.",
    "Both show good signals individually, but couple synastry + timing confirms in Pro.",
    "Couple band {couple_band} — surface match shown; full together-read is in Pro.",
  ],
  "couple_gap_workable": [
    "Together {couple_score}/100 — workable, but combined friction map is in Pro.",
    "Individual cards are clear — the full couple picture unlocks in Pro.",
    "Couple is workable but exact weak points across charts are in the Pro report.",
  ],
  "couple_gap_high_effort": [
    "Together {couple_score} — high effort match. How serious is it? Full synastry + timing in Pro.",
    "You've read both charts separately — combined risk score is only in Pro.",
    "High effort couple — don't step blind; Pro PDF gives full risk + remedy map.",
  ],
  "couple_gap_alerts": [
    "⚠ {alert_count} hidden alerts in this match — detail only in Pro report.",
    "Together: {alert_count} locked warning(s) across both charts — unlock in Pro.",
    "Cross-chart flagged {alert_count} sensitive points — Basic intentionally hides them.",
  ],
  "couple_pro_cta": [
    "Unlock Full Match Report — synastry · dasha · remedies · PDF",
    "Get Pro — full couple marriage consultation that Basic keeps short",
    "Full Pro PDF = complete engine read for your marriage decision",
  ],
}
